### ISSUE TITLE
Performance issue with Redis Adapter (2.0.1)

### ISSUE THREAD

**Issue by CharlesMcMillan** [danmayer/coverband#115]
At one point previously, we used 1.5.4 with success on our code base, and we wanted to reintroduce coverband with the newer version, 2.01...however we are seeing performance issues when coverband is enabled and collecting/sending data to redis... Here is a gist that demonstrates the problem (runnable in a `bundle console` session) https://gist.github.com/CharlesMcMillan/6bc239429761adc70ef738d05e82de6b

The goal of the gist here is to simulate the cost associated with a single page load in our app, which might include something like 10 requests where the 'report' being sent will include 2394 files with 24 lines of code each (hopefully this demystifies some of the number choices in the gist!)

The results indicate that we are losing between 1-1.5 seconds per request (I got that number by dividing 11.558872 / 10), given the above assumptions/guesstimations

It appears that saving a 'report' to redis is pretty costly here. Did something major change between 1.5.4 and 2.0.1 that would explain this?

**Comment by danmayer** [comment]
hmm @CharlesMcMillan see some of my notes on the ticket https://github.com/danmayer/coverband/pull/117#event-1844761550 I am happy to merge that in and test it as I was about to release the next version of Coverband and I could try to get this in first. Take a look and let me and @kbaum know if you think that would help.

I believe it would help the issue you are having but I am also worried that the optimal config settings aren't being used.... could you tell me the config settings you are using (making sure to keep out any host / password details)... Particularly seeing the collector, store, percentage settings.

**Comment by danmayer** [comment]
OK try again with memory store configured and using the 2.0.2 release. 

You can see it in action here https://coverband-demo.herokuapp.com/
and the config enabling memory caching here https://github.com/danmayer/coverband_demo/blob/master/config/coverband.rb
