### ISSUE TITLE
No more sampling?

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#121]
The release notes for 2.0.0 say:

> Opposed to sampling this is now a reporting frequency, when using Coverage collector

Does this mean that coverband now runs for _all_ requests/jobs, and that the percentage doesn't apply anymore? If so, is the new collection method so fast that it's completely un-noticeable? (I know that previously we had to keep our sampling percentage _super_ low because coverand overhead was significant, and every additional percentage point that we added would show up on our monitoring tools as a slow down of average response times.)

**Comment by danmayer** [comment]
Sorry for the slow response @jagthedrummer I was away on travel 

yes, I don't know how to make things clear enough to folks but tracepoint did sampling the impacted performance both on the collection of coverage and when reporting it... The new `coverage` collector is ALWAYS collecting it only changes the frequency of reporting. There is no way to turn on and off the standard lib coverage and the perf impact is so low you wouldn't want to.

* tracepoint collector: sample rate limited both collection and reporting frequency
* coverage collector: sample rate limits reporting frequency

in general, coverage is much faster, and I have been able to run it with a very low reporting frequency but it is capturing 100% of the usage. I report 0.1% of the time. For large apps the reporting can still be slow, so it is worth checking that but on a fairly large rails app it doesn't even register as a blip in NewRelic anymore.

please see the demo for the example setup: https://github.com/danmayer/coverband_demo

**Comment by danmayer** [comment]
yep @kbaum @jagthedrummer I have a branch and am working on removing Tracepoint entirely, but am also doing a number of other refactorings. I am thinking I will probably have something ready in 2-3 weeks.
