### ISSUE TITLE
AWS dependency for non-dev environments

### ISSUE THREAD

**Issue by jared** [danmayer/coverband#131]
This may turn out to be an edge case, but I've run into an issue where I'm looking to use Coverband in a non-dev environment, and I'm encountering the following error: 

```ruby
NameError: uninitialized constant Coverband::Utils::S3ReportWriter::Aws
```

This seems to stem from the fact that Coverband only specifies an aws-sdk dependency of `~> 2` in development, and does not enforce a particular aws-sdk version at runtime.  My (admittedly legacy) application is tied to aws-sdk 1.5.7, which isn't being pulled forward by the coverband .gemspec

**Comment by danmayer** [comment]
Thanks, @jared for reporting... AWS shouldn't be required or needed as a dependency unless you are using the S3 features for reporting. It isn't required by the gem as it is an optional feature. I might accidentally be loading it even if the S3 settings aren't being set, in which case I definitely need to fix that. 

Coverband is expected to be run in production, I think you are using it for the right use case.

Are you trying to use the S3 integration?
   * ie: you added the S3 config options to your Coverband config?
   * you aren't planning on using the feature to write the report to S3, so you wish to not load the `aws-sdk` at all 

In the case where you are trying to use it but versions don't match, I might be able to detect this at runtime and output a warning and document how to resolve, which I think would involve adding a compatible version of `aws-sdk` to your `Gemfile`

If you don't want to use that feature, I think I have a bug and need to ensure I don't try to load the `aws-sdk` unless a user specifically configured it

**Comment by jared** [comment]
Hi @danmayer , thanks for the speedy response!

This is currently in our business analysis environment, but my plan is to roll out Coverband to both QA (so we can see what their tests might be overlooking) and production (so we can see which areas our users are neglecting). 

I am trying to use the S3 integration, I've added the config.s3_xxx lines to coverband.rb.  The application is already using S3 in conjunction with paperclip, so I know that the AWS side of things is working, I think that somewhere between the 1.x.x and the 2.x.x release of the aws-sdk gem, some of the classes were restructured or renamed.  

Specifically, the [aws-sdk migration guide ](https://github.com/aws/aws-sdk-ruby/blob/master/MIGRATING.md) indicates that the top-level class changed from `AWS` (all caps in v1.x) to `Aws` (title caps, v2.x), which is the way it's used in `s3_report_writer.rb`

This is the full backtrace from my application:
```ruby
NameError: uninitialized constant Coverband::Utils::S3ReportWriter::Aws
/var/www/private-app-name/shared/bundle/ruby/2.5.0/gems/coverband-3.0.0/lib/coverband/utils/s3_report_writer.rb:49:in `s3'
/var/www/private-app-name/shared/bundle/ruby/2.5.0/gems/coverband-3.0.0/lib/coverband/utils/s3_report_writer.rb:55:in `bucket'
/var/www/private-app-name/shared/bundle/ruby/2.5.0/gems/coverband-3.0.0/lib/coverband/utils/s3_report_writer.rb:40:in `object'
/var/www/private-app-name/shared/bundle/ruby/2.5.0/gems/coverband-3.0.0/lib/coverband/utils/s3_report_writer.rb:27:in `persist!'
/var/www/private-app-name/shared/bundle/ruby/2.5.0/gems/coverband-3.0.0/lib/coverband/reporters/simple_cov_report.rb:47:in `report'
/var/www/private-app-name/shared/bundle/ruby/2.5.0/gems/coverband-3.0.0/lib/coverband/utils/tasks.rb:12:in `block (2 levels) in <top (required)>'
/home/private-app-name/.rvm/rubies/ruby-2.5.3/bin/bundle:30:in `block in <main>'
/home/private-app-name/.rvm/rubies/ruby-2.5.3/bin/bundle:22:in `<main>'
/home/private-app-name/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/home/private-app-name/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```

If it's possible for Coverband to detect an outdated version of aws-sdk and emit a warning, that'd probably be pretty helpful.  Alternately, if Coverband was able to detect the installed version of aws-sdk and switch between `AWS::` and `Aws::` on the fly, that'd probably make my week :)

**Comment by jared** [comment]
@danmayer -- thanks!  Please let me know if there's anything I can do to help.

@kbaum -- Since the s3 report writer is optional, I can understand why listing the aws-sdk gem in the gemspec as a runtime requirement isn't ideal.  Users who won't ever use the s3 feature shouldn't be required to bring in the whole aws-sdk gem as a part of Coverband.  I just happen to live in a weird middle ground where I have aws-sdk in place for something else, but it's not a new enough version to mesh with what the Coverband gem uses.  I don't know if there's a way to write a gemspec file that says "This other gem isn't required, unless you do 'X,' in which case, it is required, but it has to be at least version 'Y.'"  If nothing else, part of the reason I surfaced this was because if I hit it, someone else might come along and run into it as well.

I clearly have legacy issues here, since the version of aws-sdk I'm using is particular to the way in which I have Paperclip implemented.  Newer versions of Paperclip use the newer aws-sdk syntax as well, and honestly, with Paperclip now being deprecated, I need to get it out of my app anyway :)  There's a cautionary tale here about letting technical debt accumulate, I guess!

**Comment by danmayer** [comment]
ha yeah we are just now trying to move off paperclip as well. I think I understand the issue and given it is only a few lines of code I think I can detect and support but the 1.x and 2.x AWS versions. I will let you know more after I play around with it this weekend...

**Comment by danmayer** [comment]
ok try this @jared https://github.com/danmayer/coverband/pull/133 it should work on both versions

**Comment by jared** [comment]
Thanks, I'm trying it out this morning.  I had set up a new S3 bucket for this testing, and I'm just waiting for the endpoint to finish propagating through DNS (right now, I'm getting back errors that I should be using the temporary endpoint rather than the original one).

**Comment by jared** [comment]
Your fix allowed me to move past the undefined constant issue.  I set up a bucket with appropriate permissions, and made sure that Coverband had access to my AWS credentials.

Unfortunately, I wasn't able to read or write to that bucket unless I enabled global access (everyone can read/write to it).  I was getting a 403 / access denied error back from AWS:

```
[AWS S3 403 0.13655 0 retries] put_object(:bucket_name=>"my-coverband-bucket",:data=>#<String "<!DOCTYPE html>\n<html xmlns='http://www.w3.org/1999/xhtml'>\n  <head>\n    <title>Code coverage for 20181112201156</title>\n    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n    <script src='application.js' type='text/javascript'></script>    \n    <link href='application.css' media='screen, projection, print' rel='stylesheet' type='text/css'>\n    <link rel=\"shortcut icon\" type=\"image/png\" href=\"favicon_red.png\" />\n    <link rel=\"icon\" type=\"image/png\" href=\"favicon.png\" />\n  </head>\n  \n  <body>\n    <div id=\"loading\">\n      <img src=\"loading.gif\" alt=\"loading\"/>\n    </div>\n    <div id=\"wrapper\" style=\"display:none;\">\n      <div class=\"timestamp\">Generated <abbr class=\"timeago\" title=\"2018-11-12T20:22:29+00:00\">2018-11-12T20:22:29+00:00</abbr></div>\n      <ul class=\"group_tabs\"></ul>\n\n      <div id=\"content\">\n        <div class=\"file_list_container\" id=\"AllFiles\">\n  <h2>\n    <span class=\"group_name\">All Files</span>\n    (<span class=\"covered_percent\"><span class=\"red" ... (3895521 bytes)>,:key=>"coverband/index.html") AWS::S3::Errors::AccessDenied Access Denied
```

I did test out connecting to the same bucket (with permissions locked to just the bucket owner) using the v2 aws-sdk gem, and was able to read and write without any problem.  The bucket in question had a similar policy to the buckets we use for Paperclip via the v1 aws-sdk gem, so as far as I know, the policy is accurate for v1 of the gem.

**Comment by danmayer** [comment]
hmmm it is weird that you are getting some permission error, I guess there is a chance I didn't pass in the credentials correctly I will see if I can setup a bucket myself and a script that exercises this for real against it.

**Comment by danmayer** [comment]
I am traveling a bit so might be a couple days

**Comment by danmayer** [comment]
OK @jared I confirmed with the the aws-sdk 1.x that I can write / read S3 buckets that aren't public. Check your bucket settings and the coverband config options.

```
  # configure S3 integration
  config.s3_bucket = 'coverband-demo'
  config.s3_region = 'us-east-1'
  config.s3_access_key_id = ENV['AWS_ACCESS_KEY_ID']
  config.s3_secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
```

Worked for me. I merged the code in so it will be part of the 3.0.1.alpha release

**Comment by danmayer** [comment]
OK sorry @jared perhaps try on a personal or other test AWS account to play around with some bucket settings...

The access control list on the bucket permissions for "Access for your AWS account" for my bucket looks like below and doesn't need public access.

```
  | Account | List objects | Write objects | Read bucket permissions | Write bucket permissions
-- | -- | -- | -- | -- | --
  | ACCOUNT_ID | Yes | Yes | Yes | Yes
```

I have a totally empty bucket policy.

Best guess would be that the AWS user account you are using doesn't have the right S3 permissions on the bucket in question...

Anyways hope you figure something out, don't think there is much else I can think of.

**Comment by jared** [comment]
Understood -- this is now my problem and not yours :-D 

It's strange because the same bucket, with the same policy, has no problem with reading & writing via the aws-sdk gem v2.x series, it's only failing in the v1.x series.  So it's probably a misconfiguration between the older gem and settings at the organization level.
