### ISSUE TITLE
near zero config Rails integration via Railsties

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#132]
adding as an issue so we can start to connect PRs and code to it.

I guess quick question what do you think is worth tackling first Railsties or trying to sort out the MS5 coverage drift stuff @kbaum I can likely start on either one this week, but can't decide which folks would find more helpful.

**Comment by kbaum** [comment]
Tough call... I would say md5 checksum is the one to start on first. 

Have background reporting thread already works with coverband2. Just need a short snippet of code which kicks off a reporting thread on startup. Not sure if the same would work with coverband 3 but most likely.

**Comment by danmayer** [comment]
Cool sounds good, I will look at integrating the MD5 work and trying to inject the metadata on first/last recorded Coverage next.

Cool if you want to give it a shot on the background stuff @kbaum I left a stub for it here: https://github.com/danmayer/coverband/blob/master/lib/coverband/integrations/background.rb

I think basically a config option if set should just load integration and start it's thread loop when `Coverband.start` is called and then document to never set up the middleware.

**Comment by kbaum** [comment]
@danmayer - been looking into adding an end to end test that tests both rails5 and rails4. I think this is related to this so i wanted to check in with you to make sure we weren't doing the same work. TBH, i haven't had time to get very far but might have some time to dig into it this weekend.

**Comment by danmayer** [comment]
Cool @kbaum I haven't started anything on the Railsties yet, I am thinking I am going to cut a 3.0.1 pre-release with what we have and possibly get that released early next week. I don't think I will be able to work on the Railsties until late next week. So I am thinking that might be the major thing for 3.0.2...

The Rails / Rack detection will definitely be helpful for the Railsties stuff... 

If you had some ideas we could perhaps try to split it up, if you get tests on detection and all the hooks needed to start and send coverage, I could work on how to use Railsties to hook into Rails and kick off the calls at the right places... perhaps.

**Comment by kbaum** [comment]
Sounds good. I was thinking of just installing two rails dummy_apps configured with coverband in the standard way we recommend today. Then would create a test that hits a controller and then verifies that the store has the data. Eventually would be cool if the end to end test actually generates a report and verifies the controller method is covered within the report.

**Comment by danmayer** [comment]
gotcha, I was wondering if there is any good way to do the full Rails tests without having to check the full apps into the git repo. If you have any ideas all ears.

As for the end to end if we don't need to check in for Rails 5 we could perhaps have some test in or added to `coverband_demo` which is a pretty vanilla Rails app. 

I guess we could do something like the existing perf tests that check out classifier-reborn for testing, https://github.com/danmayer/coverband/blob/master/test/benchmarks/benchmark.rake#L38

**Comment by danmayer** [comment]
OK, 3.0.1.alpha is live if anyone else wants to test https://coverband-demo.herokuapp.com/coverage?

**Comment by danmayer** [comment]
cool, we can take a look

**Comment by danmayer** [comment]
OK, I should be able to work on the Railties stuff over the next few days. I am going to release 3.0.1 now as it resolves a few things and makes all the new stuff available for anyone looking to give it a shot. 

I think as the Railties work gets done, I will also try to add background jobs and rake tasks to show how they are supported to Coverband demo.

**Comment by kbaum** [comment]
Sounds great.

One thought. If background thread becomes the default setup eventually,
then background jobs and rake tasks are supported out of box with no extra
coverband code. Pairs nicely with the railties work because then truly we
could have no configuration needed when using rails.

Speaking of background thread, should we add that to the readme?

**Comment by danmayer** [comment]
yeah, that is why I want to have them on the demo so we can prove / show how that all works without additional configuration. We will definitely want to clean up a bunch of the readme removing tips on how to integrate into all the other various services.

I think depending on how the work goes we either have one more release of 3.0.x where none of this is the default, no breaking changes, but one can opt into it... or we end up making the next release 4.0.x and make the new background thread the default.

Once I have a bit more of the code done, I think it will help make the decision clear.

**Comment by kbaum** [comment]
RE: making the railties backwards compatible. Think the challenge there is not conflicting with an existing setup where the rials project is calling configure, start, and adding middleware already and coverband will automatically be doing this:

https://github.com/danmayer/coverband#3-configure-rack-to-use-the-coverband-middleware

I don't believe calling Coverband.start more than once is problematic. Calling Coverband.configure more than once should also not be a problem although as a side note, we have to consider that some people may actually have their coverband.rb located somewhere else besides the configure directory. I think adding the middleware more than once is problematic and this might be difficult to avoid depending on when our railties hook runs compared to the application. One idea would be to create a second middleware class that coverband uses internally from the Railtie. This middleware class could checkout `Rails.application.middleware` and do nothing if `Coverband::Middleware` is already in the chain.

**Comment by danmayer** [comment]
yeah the middleware is hard we can make the railtie not add it if it is already there but basically if they add it at a later point than when the railtie ran we end up with two middlewares... I think given that and moving from documenting to have the gem require: false, no longer needing to include the rake file, etc... it is probably best to move to 4.x and require some small changes for folks doing the integration.

* I don't think I will have the Railtie setup the web component/routes as one generally needs to hook into their auth and permissions system to make that safe.
* I think we will need to make a pass to remove various config options no longer needed.

**Comment by danmayer** [comment]
ok @kbaum first version to look at

* Coverband changes: https://github.com/danmayer/coverband/pull/146
* Rails integration changes: https://github.com/danmayer/coverband_demo/pull/2

**Comment by danmayer** [comment]
closing this out
