### ISSUE TITLE
Coverage data lost on puma and unicorn fork

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#134]
Hopefully we'll be able to address this but I noticed that when unicorn or puma forks, it loses all coverage data. The result is that rails initializers has no coverage. I have gotten around this by calling save in the before_fork of unicorn. Haven't tried this on puma yet but imagine it will also work.

**Comment by danmayer** [comment]
ha both doing a bit of work at the moment... yeah I have something similar in m rails app for puma, I think I can address this as part of the Railties effort, I am pretty sure the Railties integration and do Coverband.start before initialization and then do a 1-time Coverband.record post initialize prior to fork.

**Comment by kbaum** [comment]
Makes sense.

**Comment by danmayer** [comment]
This has been resolved in the Railtie branch https://github.com/danmayer/coverband/pull/146
