### ISSUE TITLE
Verification steps might be off

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#135]
Looking at this line in the readme:

https://github.com/danmayer/coverband/blame/master/README.md#L197

I think you would not see initializers at this point because saving report data is only done in the middleware and would require at least one request to the rails server.

**Comment by danmayer** [comment]
yep thanks, resolved: https://github.com/danmayer/coverband/commit/9d90e2b737713782c5fabd8d2a364fe2da0233de
