### ISSUE TITLE
add in coveralls CI code coverage tracking

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#136]
While our tests output code coverage it is a bit had to visualize and compare coverage over time... Let's add in https://coveralls.io/ support to our CI test runs to make it easy to see that we are maintaining and increasing our coverage.

added as `help wanted` / `good first issue` to see if we can get some more contributors ;)

**Comment by dondonz** [comment]
Hello! If this hasn't already been taken, I would like to help.

**Comment by danmayer** [comment]
That would be awesome @dondonz let us know if you need anything to get started

**Comment by dondonz** [comment]
Thanks!

I've given it a go (PR #157), please let me know what you think.  

I have two questions.

1. Could someone please log into Coveralls and add the Coverband repo? Perhaps you've already done this 😄
2. Could I confirm - would you like to retain `SimpleCov` in the `test_helper.rb` file? I have not changed any `SimpleCov` settings.
