### ISSUE TITLE
Better documentation/clearer actions on the web UI

### ISSUE THREAD

**Issue by bbugh** [danmayer/coverband#152]
Hi, Coverband seems quite nice and useful. Thanks for making it!

We've set up the web UI and it's working fine, however the buttons and usage are vague and I'm uncertain what they all do.

```
Coverband Web Admin Index
collect data, update report, & view
view coverage report
update coverage data (collect coverage)
update coverage report (rebuild report)
clear coverage report
reload Coverband files
```

What is the use case for each of these? Some of them seem to be repeats, and some seem to be dangerous but don't say so. `clear coverage` in particular seems to remove **all** coverage info, but doesn't have any confirmation - that's pretty bad if we've been collecting for weeks and misclick.

Improving either the UI for these with text explanations (and adding confirmation for destructive actions) or improving the documentation would be **very** helpful.

I'd be happy to PR but I don't understand it enough to do so.

**Comment by danmayer** [comment]
ok yeah . @bbugh  sorry about the confusion this is a newer feature to Coverband and isn't as well documented or explained as other parts of the project. We actually have a big branch going to improve on this feature at the moment... I will try to update the readme with some documentation tonight to make things clear.

**Comment by danmayer** [comment]
OK, @bbugh let me know if this covers your questions...

https://github.com/danmayer/coverband#coverband-web-endpoint

as for improvement to the actual UI and preventing destructive actions, I will build that into the better web frontend we are currently developing. Figured I could at least get the current feature set document first though ;)

**Comment by danmayer** [comment]
ok, check out the new web UI in the 4.0.1.beta release @bbugh this should be much more clear and easy to understand / use.

https://coverband-demo.herokuapp.com/coverage/#_AllFiles

**Comment by danmayer** [comment]
live in release 4.0.1, overall should be much easier to understand I will update the readme to reflect the new UI
