### ISSUE TITLE
Specify aws-sdk-s3 gem to reduce dependency list

### ISSUE THREAD

**Issue by dondonz** [danmayer/coverband#153]
Hello! I have recently installed Coverband and it has been very useful. Thanks for building it!

I am storing my results in an S3 bucket. When I installed the `aws-sdk` gem, all of the dependent gems were installed, which added almost 700 lines to my `Gemfile.lock` file.

What do you think about requiring only the specific `aws-sdk-s3` gem instead of `aws-sdk`? I understand there may be backwards compatibility considerations here, so I thought I'd ask first 😄

I think the key changes to the code would be the [`require` in `initialize` in `s3_report.rb`](https://github.com/danmayer/coverband/blob/master/lib/coverband/utils/s3_report.rb#L27) and the gem itself ([from Amazon's SDK for Ruby Version 3 Upgrading Guide](https://github.com/aws/aws-sdk-ruby/blob/master/V3_UPGRADING_GUIDE.md)).

**Comment by dondonz** [comment]
Cool! I'll close this issue then.

**Comment by danmayer** [comment]
yeah I think S3 will soon be optional for folks that want to run via CI but guessing most won't need it so we can make it an optional dependency. That being said as we do that we can likely move to `aws-sdk-s3` to reduce the gems. Thanks for the suggestion.
