### ISSUE TITLE
Oneshot coverage support for ruby 2.6

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#154]
Better performance for ruby 2.6 if coverband user only cares that the line was hit at least once:

https://bugs.ruby-lang.org/issues/15022

**Comment by danmayer** [comment]
Nice, this will be really awesome, glad there has been some continued interest from the Ruby team, this follows up on the previous tickets I had about some issues on Coverage.

**Comment by zwalker** [comment]
I've opened a PR that implements a first pass at implementing oneshot_lines coverage

**Comment by danmayer** [comment]
closing this out
