### ISSUE TITLE
Coverage data since...

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#158]
The longer code has gone without being hit, the more confident we are to delete it. Let's add the coverage start date to each file in our coverage report. Something like?

![image](https://user-images.githubusercontent.com/96786/50548444-84e82480-0c1a-11e9-933b-3cc2a0d0d0fd.png)

**Comment by danmayer** [comment]
yep we have the data and now own the full rendering... I guess should we add this in before 4.0.1 as it is a pretty cool new feature to add to the list? @kbaum

**Comment by danmayer** [comment]
I might be able to knock it out today

**Comment by danmayer** [comment]
ok take a look https://github.com/danmayer/coverband/pull/160

**Comment by danmayer** [comment]
live in release 4.0.1
