### ISSUE TITLE
Travis CI / Bundler 2.0 not happy

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#162]
I have all the tests passing except 2.3 as Travis-CI doesn't seem to let us install bundler 1.3.x but keeps trying to use 2.0... 

https://travis-ci.org/danmayer/coverband/builds/476105586

I followed directions here and it works for everything except Ruby 2.3

https://docs.travis-ci.com/user/languages/ruby/#bundler-20

**Comment by kbaum** [comment]
Judging by the errors, it looks like rails 4 flat out does not support bundler 2.0. Can't make much sense of why ruby 2.3 doesn't work with bundler 1.3.x. Feel like it might be a little early to drop support for rails 4.x?

**Comment by danmayer** [comment]
OK it took way longer than it should have and it would have been cleaner to do my tests on a branch... but I got everything passing with bundler 1.17.3 on travis-ci... 

https://travis-ci.org/danmayer/coverband/builds/476675778

travis-CI file:
```
before_install:
  - rm /home/travis/.rvm/gems/ruby-2.3.7@global/specifications/bundler-2.0.1.gemspec || true
  - gem uninstall bundler || true
  - gem install bundler -v '1.17.3'
  - bundler --version
```
cleaner version: https://travis-ci.org/danmayer/coverband/builds/476677975

This had some good tips but the find trick didn't work for me: https://github.com/travis-ci/travis-ci/issues/8717

**Comment by kbaum** [comment]
Well done!
