### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by jaysonvirissimo** [danmayer/coverband#163]
The readme links to [here](https://github.com/danmayer/coverage_demo), but that 404s. It's possible that it is a private repo that needs to be made public.

**Comment by kbaum** [comment]
Good catch! I think this is the one we meant? https://github.com/danmayer/coverband_demo

**Comment by danmayer** [comment]
thanks fixing

**Comment by danmayer** [comment]
I think that was an older demo which was replaced by coverband_demo... Anyways, I updated the link in the readme and thanks again @jaysonvirissimo

**Comment by jaysonvirissimo** [comment]
👍
