### ISSUE TITLE
support coverage on app gems

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#180]
Beyond just reporting application coverage it would be good to support Gem usage. This would let one find gems that are loaded and not used as well as underutilized and possibly a good target for removal.

**Comment by danmayer** [comment]
I need to do lots of refactoring and some serious work on performance, but this is a first version that works / shows the UX I am thinking about. Let me know thoughts @kbaum 

![gem_example](https://user-images.githubusercontent.com/24925/51883445-1cd34e00-2340-11e9-8743-e5ae628b8857.gif)

**Comment by danmayer** [comment]
There is an impact on measuring, I will get some benchmarks on that for now hard to say how much of an issue. I don't think much honestly mostly because of the background thread reporting... The actual measurements were always taking place basically in the STDLIB coverage we were just filtering it out.

The primary perf issue is viewing the report... the page with all the gem source gets so big and slow that the page weight, dom, and JS is slow and sluggish. I am thinking I will break it up into multiple pages and render subsets per page... so drop the all files tab, then render app and gems as different pages.

**Comment by kbaum** [comment]
I can see performance issues with pushing to redis because we are pushing so much more data given we are not filtering the gems directory. Not sure how much of a real impact that would have considering we are pushing to redis in a background thread.

RE: The report. I think this is super valuable without that much detail on per line usage for gems. I imagine that might speed up the report itself and we could add in per line usage of gems later.

**Comment by danmayer** [comment]
yeah that would definitely be one way to reduce the load just not load gem source... in terms of if a gem is used or not that works great... one thing I have been doing more lately is a gem that has very light use just porting the needed functions directly into the app and dropping the gem. I think the source code view would be really helpful in that case... 

Basically, that is what we did with Coverband, pulled out a small subset of SimpleCov. I am thinking this tool could help one do that with their Rails apps on a larger scale to reduce dependencies. 

Anyways, I might make that a configurable option as some folks might just want the overall Gem percent which is likely already fast enough.

**Comment by danmayer** [comment]
OK take another look @kbaum I believe there should be

on collection:
* no perf impact if this feature isn't enabled
* small impact to the collection of gem data, generally OK because of the background reporting

on web report load:
* no perf impact if this feature isn't enabled
* small impact if just listing gem and percentages (this feels usable already)
* large impact to list gem and all gem source files (further perf work needed to make this usable on large apps)

I am thinking I am ready to do some perf testing to see if this is ready for initial release... So I will cut an alpha gem (generally required for some of the perf testing).

Since it is all off by default I think the first release will let me get some feedback and then further work on perf. 

The only other feature that might be worth fixing before the first version of this is supporting gems in multiple paths which I believe could be an issue depending on ruby tooling (rvm, rbenv, etc some of them set multiple gem paths and it is a supported feature, but I haven't been able to really find a setup that needs to support multiple paths yet)

thoughts?

**Comment by danmayer** [comment]
The test release is running on production without issue and helped find at least one gem that never should have been loaded on production.

**Comment by danmayer** [comment]
making this closed as it is in 4.1.0.beta and the 4.1.0 release should go live this week
