### ISSUE TITLE
Coverage status badge broken on readme

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#182]
![image](https://user-images.githubusercontent.com/96786/51917338-568e6e00-23ad-11e9-9e38-113f07115daa.png)

**Comment by danmayer** [comment]
hmm works for me right now @kbaum is it still broken for you? Any chance it was just broken while coveralls was updating?

<img width="1224" alt="screen shot 2019-01-29 at 9 38 41 pm" src="https://user-images.githubusercontent.com/24925/51958698-6db17800-240e-11e9-9f30-cdb8e51bf8c3.png">

**Comment by kbaum** [comment]
Ack it's working for me now... hmmm.. could this be happening when we run a build?

**Comment by danmayer** [comment]
yeah thinking it might have some brief outage between builds, we are using very standard coveralls setup so I don't know what exactly we would change. I will close for now but if you notice a pattern re-open...

note there is a bug out when viewing markdown in the Atom.io editor where it caches old images for a very long time and can do weird things.
