### ISSUE TITLE
ENV["REDIS_URL"] isn't picked up?

### ISSUE THREAD

**Issue by gingerlime** [danmayer/coverband#185]
I'm seeing a weird issue, and would appreciate some help on how to troubleshoot.

On my dev environment everything is working fine, with or without `config/coverband.rb`. There's a `ENV["REDIS_URL"]` set and it's picked up correctly by coverband (4.0.1)

On my staging environment however, I also have the `ENV["REDIS_URL"]` set, but somehow it's not picked up, and when I go to `/coverage`, I'm getting an error:

```
#4410 Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
```

I tried to set a `config/coverband.rb` with:

```ruby
Coverband.configure do |config|
  config.store = Coverband::Adapters::RedisStore.new(
    Redis.new(:url => ENV["REDIS_URL"])
  )
  config.ignore = %w[config/application.rb
                     config/boot.rb
                     config/puma.rb
                     config/environments/test.rb
                     config/environments/development.rb
                     config/environments/staging.rb
                     config/environments/production.rb
                     lib/tasks/*]
end
```

But the same problem appears... If I check the rails console on staging (also dev), I can see that `REDIS_URL` is there inside `ENV`

```ruby
irb(main):001:0> ENV["REDIS_URL"].present?
=> true
```

(it has the correct, full URL set, I just didn't paste it for security reasons)

We're using [`dotenv`](https://github.com/bkeepers/dotenv) to set those environment variables. Maybe this is causing the issue? How can I make sure coverband picks up the redis URL ?

**Comment by kbaum** [comment]
Interesting.. not sure what's happening. You should no longer need to set the store as it will default to looking for REDIS_URL environment url:

https://github.com/danmayer/coverband/blob/master/lib/coverband/configuration.rb#L67

If you start your console environment in staging, try executing:

```ruby
Coverband.configuration.store
```

In dev, mine looks like:

![image](https://user-images.githubusercontent.com/96786/51988612-185b8200-2473-11e9-8836-9a51d457df9d.png)

Looks like that is what's being passed to the web reporter:

https://github.com/danmayer/coverband/blob/master/lib/coverband/reporters/web.rb#L49

**Comment by gingerlime** [comment]
Thanks @kbaum. Yes, I'm aware that it should pick it up, but I set it up explicitly, just in case. It didn't work either way.

... Unfortunately I'm just about to go offline for a few days, so can't really test it... Which isn't ideal for trying to troubleshoot this and keeping the conversation going on Github. Feeling a bit silly for opening the issue as I'm about to disappear.

I should be back on track in a week from now, and would try it out (somehow didn't think about running it). I did run it on my dev box (it shows `@redis=#<Redis client v4.0.1 for redis://redis:6379/0>`, which is correct for my dev box and matches the `REDIS_URL` there).

```ruby
[6] pry(main)> Coverband.configuration.store.send(:redis)
=> #<Redis client v4.0.1 for redis://redis:6379/0>
[7] pry(main)> ENV["REDIS_URL"]
=> "redis://redis:6379"
```

Coincidentally, that's how I discovered the base key mismatch (see #184).

But now the code isn't on staging, so I won't be able to test it there until next week most likely... :(

Could it be because we're using `rediss` (secure redis) on staging and production? (although I suspect it's more likely to be something related to the `dotenv` gem I mentioned above, but I'm not sure either way).

**Comment by kbaum** [comment]
Tough for me to say as I am not all that familiar with dotenv but it looks like it's only meant for dev?
https://github.com/bkeepers/dotenv#rails
No rush on figuring this out.. we'll still be here a week from now 😄 .

**Comment by gingerlime** [comment]
Thanks @kbaum !

I think dotenv can be used in production, even though originally it was intended for development. https://github.com/bkeepers/dotenv#can-i-use-dotenv-in-production

Having looked at the dotenv readme again, there's [something](https://github.com/bkeepers/dotenv#note-on-load-order) I might try, because I suspect this is the culprit... (but it'll have to wait unfortunately)

Might be a good opportunity to ask, even though it might be off-topic, but how do you guys manage your environment variables for rails on production? (assuming you use rails)

**Comment by danmayer** [comment]
@gingerlime / @kbaum I think that you need to ensure that dotenv is required before Coverband. Since both use railties I believe your dotenv isn't set by the time Coverband is looking for it...

Dotenv has some options on how to controll load order
https://github.com/bkeepers/dotenv#rails

I would try to change order in Gemfile and use the magic require line to ensure it is loaded before Coverband...

```
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'gem-that-requires-env-variables'
```

**Comment by danmayer** [comment]
ha we both found the load order issue at about the same time @gingerlime no worries we will leave the ticket open until you can test.

**Comment by gingerlime** [comment]
Thanks @danmayer!

I was able to test on my dev box, and I think this is it. I'll be able to confirm in about a week from now on staging, but I'm 99.9% sure adding the `require: 'dotenv/rails-now'` does the trick.

The only thing I'm a bit unsure about is whether this has any negative effect on being able to measure coverage in some ways, but I hope it would only mean that the `dotenv` gem itself won't be, erm, covered, but that's not an issue as far as I'm concerned.

I think we can close this for now. I would report back either way in about a week.

Thanks again for your help @danmayer and @kbaum. Much appreciated. (still curious to learn how you manage your env variables on production though, if you're willing to share, but that's kinda off-topic)

**Comment by IsabelleLePivain** [comment]
Just adding that dotenv changed their syntax to force load the gem since then, to `gem 'dotenv-rails', dotenv/load` as of March 2024.
