### ISSUE TITLE
Eager loading of files skews the coverage percentages

### ISSUE THREAD

**Issue by CharlesMcMillan** [danmayer/coverband#186]
In our coverband results, we are often seeing files that are mostly unused, but showing percentages above 60% or so...the reason being that the method definition `def method_name` and `end` are counted as being covered...which makes sense because the file is loaded.

In production, we use `eager_load = true` on our rails server, and I _think_ that might be related to what we're seeing here.

Is there some way that coverband could filter out the lines that are apart of the method definition (like `def method_name`) so that the percentages aren't skewed to be so high?

**Comment by danmayer** [comment]
yeah I have been thinking about this a lot lately @CharlesMcMillan ... it is good to know they are run... but it is very different what is executed at load time vs run-time... Basically, the standard-lib of Coverage doesn't know the difference, but I think Coverband could figure this out by diffing eager load lines... to what it gets past initial file load during runtime. This kind of difference also needs to show when a file last had any usage in Coverband right now the last_file_activity metric shows last time file loaded, which isn't helpful.

Thanks for the report, I am thinking about this and have some ideas, but I think it will take a bit longer to work out a good solution. Not likely to make it in the 4.0.2 release but this might be a good primary feature to drive our 4.0.3 release.

**Comment by kbaum** [comment]
@danmayer That sounds like a great way to handle it. Another thought i had here is that what we really want to know is percent method body execution. I wonder if there is a way to calculate that?

**Comment by danmayer** [comment]
hmm could you explain more... would this be kind of like a new breakdown of the file... right now we have relevant lines which is non-white-space, non comment, etc lines... is 'method body' kind of like even more interesting relevant lines?

Are method body lines somehow different than `on load` / when required lines... or just better naming?

I think the idea is good something like below...

existing
`| % coverage | lines | RELEVANT LINES | Lines Covered | Lines Missed |`

new
`| % coverage | % BODY COVERAGE | lines | RELEVANT LINES | METHOD BODY LINES | Lines Covered | Lines Missed |`

**Comment by kbaum** [comment]
My last idea was not well thought out. I was just thinking that most often method bodies are missed and only class definitions such as constants, macros, and method signatures are hit on app load. This is not 100% true though and aside from that it would probably be difficult for coverband to know which lines of code are inside a method body.

@danmayer I like your idea of tracking what lines are hit during application initialization. Rails offers after_initialize for this and other ruby applications can manually tell coverband when the code has finished loading. Just thinking we could have separate data structures in redis for eager loaded code coverage and runtime code coverage. This will give us the ability to drill into runtime only code coverage only.

**Comment by kbaum** [comment]
Was thinking about how this issue impacts the gem reporting feature. Because bundler eagerly requires all of the gems, it will be challenging to know which gems are not being used since they will all have some coverage.

**Comment by danmayer** [comment]
yeah agreed at the moment it is really hard to know things just loaded vs used.

**Comment by danmayer** [comment]
for progress on this @CharlesMcMillan see the work in progress PR https://github.com/danmayer/coverband/pull/219

**Comment by danmayer** [comment]
closing as this is on master and the 4.2.0.rc2 release

**Comment by danmayer** [comment]
ok @CharlesMcMillan if you check out the 4.2.0 release this is now fixed https://github.com/danmayer/coverband/blob/master/changes.md#coverband-420
