### ISSUE TITLE
refactor tests to match directory structure of lib folder

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#187]
This should wait until the gem support PR is merged, but our tests are a bit messy and refactoring to have integration/unit and then having everything match the folder structure in lib would be helpful.

**Comment by kbaum** [comment]
What do you think of organizing like:

```
tests/
  integration/
  coverband/
    adapters/
    collectors/
    reporters/
```

The idea would be if it mimics the lib directory structure and is under test/coverband, then it's a unit test. If it's under test/integration, then it's an integration test.

**Comment by danmayer** [comment]
yep that is exactly what I am thinking
