### ISSUE TITLE
Any way to disable coverband via config or ENV var?

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#189]
With older versions that required manual config we would use an ENV var to control whether coverband was activated or not. This allowed us to turn it on/off without requiring a new deploy. Is there any way to so something similar with the new rail tie?

**Comment by kbaum** [comment]
Great question and we should definitely document this on the README. I believe you can set `COVERBAND_DISABLE_AUTO_START` environment variable.

https://github.com/danmayer/coverband/blob/master/lib/coverband.rb#L60

Let me know if that works for you.

Another way I have done it is setting `require: false` in the Gemfile and then requiring coverband at whatever point you want.

**Comment by jagthedrummer** [comment]
Wow, you're fast, @kbaum! Thanks for the info. `COVERBAND_DISABLE_AUTO_START` looks like exactly what we need. Cheers!
