### ISSUE TITLE
Gem files on demo blank

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#190]
I noticed the gem files are showing up under the app tab:

![image](https://user-images.githubusercontent.com/96786/52480910-05cfff80-2b7b-11e9-9bf5-097a74aba176.png)

Clicking on one of those files shows a blank modal:

![image](https://user-images.githubusercontent.com/96786/52481348-40866780-2b7c-11e9-8c25-83719bcca44f.png)

https://coverband-demo.herokuapp.com/coverage?#69851ffa22c0b74c15d95bbc2d79d526382ee2e8

**Comment by danmayer** [comment]
Thanks, I will look the blank issue isn't really a problem when gem details are disabled they aren't rendered... At the moment that is disabled on coverband_demo

https://github.com/danmayer/coverband_demo/blob/master/config/coverband.rb#L49

So the bug seems to be that it is filtering some gems into the app folder... I will take a look, should be an easy fix.

**Comment by danmayer** [comment]
OK, committed a fix for this on the gem branch https://github.com/danmayer/coverband/commit/f678cd71250b4e83e276727c7ad9d2c37b965d48

after tests pass I will release beta gem to test that on Coverband demo. This only impacted gems that use a vendor deployment style that is under the application directory like heroku, so it didn't show up on my production app.

**Comment by danmayer** [comment]
hmmm OK fixed, but the 'vendor' issue causes another problem... where standard lib files show up in APP

https://coverband-demo.herokuapp.com/coverage/#_App

to make gems work on heroku, I removed 'vendor' from the default ignore... I think I will need to remove vendor but add something back to ignore standard lib... So I guess this is only partially fixed for now

**Comment by danmayer** [comment]
oh yeah forgot about the vendor issue working on that now.

**Comment by danmayer** [comment]
ok fixed and pushed to the gem branch
