### ISSUE TITLE
data size can balloon under certain conditions

### ISSUE THREAD

**Issue by gingerlime** [danmayer/coverband#193]
Relates to the discussion on #188.

If the folder structure of the app changes when code is deployed (e.g. incremental release id sub-folders), the data size can grow unbounded, with every deploy.

This is due to the fact that keys are based on the full path.

There are a few options for resolving this (still in discussion):

* when [merging](https://github.com/danmayer/coverband/blob/2f0785eac742c0d28d2e55761f78eb573f309712/lib/coverband/adapters/base.rb#L64) coverage data, merge files that have the same md5 signature (this will keep old code versions though, but not all files)
* canonicalize the full path when storing file keys (similar to what's happening with `root_paths`, would incur a fixed "penalty" for each key, but depending on the complexity of the `root_paths` regex complexity)
* create a rake task to clean-up duplicates (based on which criteria?)
* something else?

**Comment by danmayer** [comment]
yeah, I like the idea of using relative paths while reporting opposed to merging... Both solutions would generally be in the background thread and shouldn't case to much of a performance issue.

@kbaum I think you also preferred relative paths vs merging.

One thing to note, is this likely doesn't work for gem and stdlib Ruby files as their paths aren't always relative to the app.

* gems we could do relative to the gem_home, or we could do nothing and assume it doesn't change per deploy
* std-lib while Coverage tracks at the moment Coverband doesn't support or care about reporting std-lib so they should just be ignored and never make it to the store.

**Comment by danmayer** [comment]
thoughts @gingerlime / @kbaum I can start working on an implementation.

**Comment by kbaum** [comment]
I think relative paths within our store (redis) is a solid solution. I don't think performance should be an issue either. Could always optimize with an in memory cache of absolute path to relative if it became an issue.

**Comment by gingerlime** [comment]
just to clarify, reporting means when coverage data gets pulled from coverage and stored? (as opposed to the web interface report). Sorry, I'm not entirely familiar with your terminology :)

Yes, intuitively it makes the most sense to me. 

The only downside I can think of is if you change your `root_paths` regex at some point, you also need to clear your data, because it won't be able to "backport" things if there was already a regex applied. It's a very odd edge case though, so not something to worry about in my opinion (and easily "fixed" by clearing data). 

👍 from me!

**Comment by danmayer** [comment]
yeah sorry the terminology could be improved runtime reporting is when we send data to the store... client reports are when we view the data... There has to be some better names for that. Runtime collection is what I used for a while but collecting the data in memory is different than submitting it to a persistence layer.

Anyways, I have a first version working locally. I need more time to clean it up and get some tests but I like the approach I will have something more to share soon.

**Comment by gingerlime** [comment]
Awesome! Thanks @danmayer.

Suggestion for naming:

* collection (getting coverage data in memory)
* storage or persistence - storing it in redis (or another data store)
* consolidation or processing or transformation - any merges, updates that might not happen on collection or storage (not sure if it's a thing)
* reporting - when displaying data or storing coverage reports (I guess there's online reporting and report generation? e.g. if you push reports to S3 etc, so maybe this can be split)

Just from my perspective as a not-yet-even-user of coverband :)

**Comment by kbaum** [comment]
I like this naming and it happens to mostly already agree with how the files and classes are named.

**Comment by danmayer** [comment]
ok sorry for the delay got a bit side tracked take a look @kbaum / @gingerlime 

https://github.com/danmayer/coverband/pull/195

**Comment by danmayer** [comment]
> * storage or persistence - storing it in redis (or another data store)

add the moment the code folder is called adapters with the idea we could store to more than redis... perhaps storage_adapters or persistence_adapters would be better

**Comment by bf4** [comment]
To consider: I just discovered coverband was storing 25MB in our redis instance. It would be trivial to show the data size in the UI, no?

**Comment by danmayer** [comment]
That is a great idea @bf4 that also sounds like a big number, I could likely reduce / compress. Is that with the gem tracking enabled or without?

Also, what mechnism did you use to find the size, guessing not just the full redis size as it is often shared. Did you call some command to get the space on the coverband namespace? If you could share that it would be great. I can add it to the UI to help people understand usage and possibly even break it down a bit more to help them with adding `coverband.ignores` which would reduce the size.

**Comment by bf4** [comment]
@danmayer it's just a rails app with no config.  I zipped it and emailed it to myself before clearing it.  Then I set up a separate Redis for coverband

```ruby
Coverband.configure do |config|
  if ENV.key?('REDIS_URL') && !ENV.key?('COVERBAND_REDIS_URL')
    Rails.logger.warn "You really should put Coverband in its own Redis instance. Set COVERBAND_REDIS_URL, or COVERBAND_DISABLE_AUTO_START"
  end

  config.ignore.concat [
    'config/application.rb',
    'config/boot.rb',
    'config/puma.rb',
    'config/environments/*',
    'lib/tasks/*',
    'lib/generators/*',
    'config/initializers/*',
    'db/*'
  ]

  if config.respond_to?(:add_group)
  config.add_group 'Controllers', 'app/controllers'
  config.add_group 'Models', 'app/models'
  config.add_group 'Mailers', 'app/mailers'
  config.add_group 'Serializers', 'app/serializers'
  config.add_group 'Validators', 'app/validators'
  config.add_group 'Policies', 'app/policies'
  config.add_group 'Workers', 'app/workers'
  config.add_group 'Resources', 'app/resources'
  config.add_group 'Helpers', 'app/helpers'
  config.add_group 'Libraries', 'lib'
  config.add_group 'Concerns', %w[
    app/controllers/concerns
    app/mailers/concerns
    app/models/concerns
    app/policies/concerns
    app/resources/concerns
  ]
  end

```

and ensured the old data was deleted

```ruby
redis_url = ENV['REDIS_URL']
redis_store_options =
{ ttl: Coverband.configuration.redis_ttl,
redis_namespace: Coverband.configuration.redis_namespace }

store = Coverband::Adapters::RedisStore.new(Redis.new(url: redis_url), redis_store_options)
base_key = store.send(:base_key)
  => coverband3_1
data = store.send(:redis).get(base_key); data.bytesize
  => 25789930 -> 25 MB
store.clear! 
```

**Comment by gingerlime** [comment]
@bf4 perhaps you're bumping into the same issue I was having, with multiple folders? then each deploy would increase the size.

I just did a quick check with the version in #193, after several deploys and running for some time

```ruby
redis.get("coverband_3_2").bytesize
=> 119925
```

Comparing to the main version, size was an order of magnitude higher. So I guess this is another :+1: for getting #193 out.

**Comment by danmayer** [comment]
Thanks all this is great. I will take a look... I need to fix the duplicate ignores issue... Then I can add a view for this... Thinking we should get the release out with these fixes... Then I think there will be some further improvements around this and a big refactoring related to paths, storage, migrations, etc in the next release.

@bf4 do you have the deployment changing directories thing that @gingerlime had?

**Comment by bf4** [comment]
@danmayer I hadn't looked very carefully at the JSON. We're on heroku.... yup here's a simple grep, 66 lines

```
  "/app/app/controllers/application_controller.rb": {
  "/tmp/build_fbd2966febd67105ec97158eedccf434/app/controllers/application_controller.rb": {
  "/tmp/build_d6aff3def5010c1122214081afbc3b02/app/controllers/application_controller.rb": {
  "/tmp/build_a1e8fa4664c079bd36ddd1290dc7f176/app/controllers/application_controller.rb": {
  "/tmp/build_4ed1b493828908cdec0221ed95fc1959/app/controllers/application_controller.rb": {
  "/tmp/build_2e849a4c13670774dac5ed0bfecce787/app/controllers/application_controller.rb": {
  "/tmp/build_0742db40a4b2421d54245195b3a712a1/app/controllers/application_controller.rb": {
  "/tmp/build_8766284cec538e31601d5d26ce67403f/app/controllers/application_controller.rb": {
  "/tmp/build_e09500a0ea2bf808c2349893f0f4218f/app/controllers/application_controller.rb": {
  "/tmp/build_3bea599d2e52550f59308d6468dd2ce3/app/controllers/application_controller.rb": {
  "/tmp/build_a21c39b409e273422941f6f44ce78892/app/controllers/application_controller.rb": {
  "/tmp/build_af6db5c1fb6adcf77f86102a39af1cd0/app/controllers/application_controller.rb": {
  "/tmp/build_76fce1ba02a064e08a4c28ead3087b2f/app/controllers/application_controller.rb": {
  "/tmp/build_61d3c7a8a0657e7dfe713a33c6f677b1/app/controllers/application_controller.rb": {
  "/tmp/build_5a01654ac973fccdc238d1ff2ffacb8b/app/controllers/application_controller.rb": {
  "/tmp/build_f3ec60f3d3d40631a8783e096460c230/app/controllers/application_controller.rb": {
  "/tmp/build_041b678e18cfbfdf736ba5412f2dd555/app/controllers/application_controller.rb": {
  "/tmp/build_38391825cf835bcc3682902b373d4c03/app/controllers/application_controller.rb": {
  "/tmp/build_340a49a4d12d88e6329d0118344dab61/app/controllers/application_controller.rb": {
  "/tmp/build_6338e8bc7d7ea7df3c99688e28c861c7/app/controllers/application_controller.rb": {
  "/tmp/build_19410fb865ba8e2650090b023ac98a02/app/controllers/application_controller.rb": {
  "/tmp/build_bedcbcc006afae1a7bd98756543a5423/app/controllers/application_controller.rb": {
  "/tmp/build_55aa56fcdbc7573c11c163735609dcdb/app/controllers/application_controller.rb": {
  "/tmp/build_214989b3b8ca5271b6e8b40f8c2e445e/app/controllers/application_controller.rb": {
  "/tmp/build_713b4a62b3d1aa040b8d4dc44104692e/app/controllers/application_controller.rb": {
  "/tmp/build_c082992d02394f1b7c814fe558f76d57/app/controllers/application_controller.rb": {
  "/tmp/build_71274e41240f0cedb6dd5424118e2c5b/app/controllers/application_controller.rb": {
  "/tmp/build_db2d5d4ce6ffd4284efde083c885c101/app/controllers/application_controller.rb": {
  "/tmp/build_da90ac23bcf15c1c91402a5ac5ec984a/app/controllers/application_controller.rb": {
  "/tmp/build_5e3ecd8fed1ef8f6cce5d1cf1d3233ac/app/controllers/application_controller.rb": {
  "/tmp/build_7b6a9ac685571a8ab6e03fffbd6eda99/app/controllers/application_controller.rb": {
  "/tmp/build_6aeab6b62f3600543bf82c850c022f3b/app/controllers/application_controller.rb": {
  "/tmp/build_f89ad4f5bea60381a179d1db95121cdb/app/controllers/application_controller.rb": {
  "/tmp/build_737c4e59f0453cb09676e7e7e7fc3aa7/app/controllers/application_controller.rb": {
  "/tmp/build_04bec11fc650f10230716cd3a41c2845/app/controllers/application_controller.rb": {
  "/tmp/build_7107180177d618bd50b1c4a47d3213e1/app/controllers/application_controller.rb": {
  "/tmp/build_d3a47aee7c37f888f2a23ef957419082/app/controllers/application_controller.rb": {
  "/tmp/build_a8acf825b7c8fa859ad7420414e46978/app/controllers/application_controller.rb": {
  "/tmp/build_3163759b0c527b7ce02ff8b8b93cbec7/app/controllers/application_controller.rb": {
  "/tmp/build_a8fa7f89ddde2d7b634a685570b47d7f/app/controllers/application_controller.rb": {
  "/tmp/build_5b606925c48d8e6c7f771590de98bef2/app/controllers/application_controller.rb": {
  "/tmp/build_f66f1ae38eb28973c741e098acdd51c3/app/controllers/application_controller.rb": {
  "/tmp/build_3b55a393c0aaa77190828a2954dc1bc5/app/controllers/application_controller.rb": {
  "/tmp/build_4476598564c1de469b0d36930f940d34/app/controllers/application_controller.rb": {
  "/tmp/build_0f7e5e840cba56271ffeeb5eda571355/app/controllers/application_controller.rb": {
  "/tmp/build_34339938698786a7652286a7ace1a7b6/app/controllers/application_controller.rb": {
  "/tmp/build_456fb41cc6cca3e83b940c4f500f7d7f/app/controllers/application_controller.rb": {
  "/tmp/build_0234559f6e195682b3aa44f08ea992b7/app/controllers/application_controller.rb": {
  "/tmp/build_a503e07151c1a988962bd7513baa8946/app/controllers/application_controller.rb": {
  "/tmp/build_22142e74783b043579cd85236fe92c3c/app/controllers/application_controller.rb": {
  "/tmp/build_25275236269fbe541c7677b8d53c5f52/app/controllers/application_controller.rb": {
  "/tmp/build_71dff9ff899557ccfc10ee07c7f87a15/app/controllers/application_controller.rb": {
  "/tmp/build_80f8a336cba52bb225c6ed1019dd7404/app/controllers/application_controller.rb": {
  "/tmp/build_afd0f8deaf6e337e1c27d23c6fc3489a/app/controllers/application_controller.rb": {
  "/tmp/build_c220be10c3273cddcde77e50e6088b07/app/controllers/application_controller.rb": {
  "/tmp/build_3f5f77d2056a99a728f901f1384b806b/app/controllers/application_controller.rb": {
  "/tmp/build_9c88f32fc7be3311c63a0f880f4ba8ee/app/controllers/application_controller.rb": {
  "/tmp/build_2858ef2eb35d79927081b9c606f017c2/app/controllers/application_controller.rb": {
  "/tmp/build_d244fce6d4ccf966749520d09078ef09/app/controllers/application_controller.rb": {
  "/tmp/build_f5aabe01f741bc343f7cec0136d5dacd/app/controllers/application_controller.rb": {
  "/tmp/build_2ceed2d0cc1fa857a4e7163dade66d35/app/controllers/application_controller.rb": {
  "/tmp/build_3841200f315d6826717907aa773b7dbb/app/controllers/application_controller.rb": {
  "/tmp/build_0b528c0c9a12fc639a4d4b599246c43c/app/controllers/application_controller.rb": {
  "/tmp/build_927af964fa6935629ff27e410483a413/app/controllers/application_controller.rb": {
  "/tmp/build_1fd7d7ee5cb3cb4f13946add4f37d148/app/controllers/application_controller.rb": {
  "/tmp/build_3637d19f9643c20400ba34bfb53e3b6f/app/controllers/application_controller.rb": {
```

**Comment by CharlesMcMillan** [comment]
I assume the relative path fix discussed above would fix this issue, but I just wanted to note that somehow mysteriously we are not seeing this issue on our heroku app...On inspecting our redis, I don't see the /tmp/build_.../ directory structure but rather just something like app/...

@bf4 What buildpacks do you have on your app? I wonder how your app code is nested under that tmp/build_.../ directory

**Comment by danmayer** [comment]
I have seen the `/tmp` thing on heroku before I am thinking we could add that directory to the default ignores and document files are run from there during heroku build / deploy process. I think it might be during asset compilation or something like that.

**Comment by bf4** [comment]
@CharlesMcMillan 

```
1. https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
2. heroku/metrics
3. https://github.com/rails-sqlserver/heroku-buildpack-freetds#v1.1.1
4. https://github.com/heroku/heroku-buildpack-ruby
```

it could be the freetds one

**Comment by danmayer** [comment]
so basically I think we want only the first entry...

```
 "/app/app/controllers/application_controller.rb": {
  "/tmp/build_fbd2966febd67105ec97158eedccf434/app/controllers/application_controller.rb": {
```

and ignore all the `/tmp` runs

**Comment by danmayer** [comment]
I confirmed that if you have asset building on with heroku it will run the code in this `/tmp` folder and add a bunch of files to Coverband... once per deploy... 

```
"/tmp/build_ea82da9bb491a5dbb557c4454058ddfd/vendor/bundle/ruby/2.5.0/gems/sass-rails-5.0.7/lib/sass/rails/railtie.rb":{"first_updated_at":1549843538,"last_updated_at":1549843553,"file_hash":"7c150bee04300b8f6e32060220420153","data":[4,4,4,null,4,4,4,null,null,null,4,null,4,null,4,null,4,null,4,null,4,null,null,null,null,null,4,null,4,0,null,null,null,4,3,null,null,4,null,3,3,3,null,null,3,null,null,3,null,null,3,null,3,null,null,3,6,6,6,6,null,6,6,6,null,null,6,6,null,6,null,null,null,6,6,6,null,null,null,3,null,null,4,3,null,0,null,null,null,3,null,null,null,null]},"/tmp/build_ea82da9bb491a5dbb557c4454058ddfd/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb"
```

I am adding to the default ignore.

**Comment by danmayer** [comment]
OK, size of data used in Redis by Coverband is now available on the webview both in bytes and Mb

**Comment by danmayer** [comment]
OK, ignoring `/tmp` is in... so I guess the only think needed for release would be the first 'migration' task.

**Comment by danmayer** [comment]
if anyone wants to verify the /tmp or the duplicate roots issue feel free to run against master branch by updating your `Gemfile`

```
# Current Coverband Master branch
gem 'coverband', '>= 4.1.0.beta', git: 'https://github.com/danmayer/coverband.git'
```

**Comment by danmayer** [comment]
changes are also deployed to demo site

https://coverband-demo.herokuapp.com/coverage/settings

**Comment by danmayer** [comment]
ok @gingerlime and @kbaum first version of migration is up as a PR, I tested it on coverband_demo running it on an old version and a new one and verifying the results combined.

https://github.com/danmayer/coverband/pull/198

**Comment by danmayer** [comment]
ok closing this, as it should be addressed with all the fixes in the 4.1.0 release

**Comment by gingerlime** [comment]
Thanks a lot for fixing this. Excited to roll it out to staging next week, and hopefully production soon after.

**Comment by danmayer** [comment]
great let me know if you find any other issues @gingerlime
