### ISSUE TITLE
Add gem coverage to README

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#201]
We just recently added ability to track gem coverage from the report using track_gems and gem_details.

**Comment by kbaum** [comment]
Was thinking about taking a stab at revisiting this section in the readme:

https://github.com/danmayer/coverband#collecting-gem--library-usage

@danmayer - that section currently mentions:

> ensure you call require 'coverband' which triggers Coverband.start before loading all your gems

I guess this would be done by including coverband first in your Gemfile? Just did some quick searches and it looks like bundler requires gems in order they are listed within the Gemfile.

**Comment by danmayer** [comment]
Should we close this with your recent PR @kbaum?

**Comment by kbaum** [comment]
Good call!
