### ISSUE TITLE
Add gem load ordering section to README

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#203]
Based on our recent discussions, I think we should add a section on Gem ordering to the documentation.

1. coverband must come before any gem you wish to track
2. coverband must come after gems with custom integrations like rails and resque

It looks like the coverband Railtie will be skipped over if coverband does not see Rails defined:

https://github.com/danmayer/coverband/blob/master/lib/coverband.rb#L22

Not sure of a way around that problem.

**Comment by danmayer** [comment]
Only thing I could think of is trying to attach a listener and if those objects are loaded AFTER Coverband it could trigger the integrations... but it is a lot of complexity so probably better to just document the order/expectations.

**Comment by danmayer** [comment]
I think you covered this well enough we should close @kbaum ?
