### ISSUE TITLE
include certain gems in coverage

### ISSUE THREAD

**Issue by apsoto** [danmayer/coverband#21]
We have some common code in our own gems.  I wish there was a way to include certain gems in the coverage while still ignoring all others in /vendor.

The only way I see to do it is to list all the gem paths in ignored _except_ the ones I want to include.  That's a lot regex patterns to check when it's checking whether to ignore the file or not.

**Comment by danmayer** [comment]
Thanks for the comment. I think I could add a feature to allow this. I am currently moving and about to start up a job, so it will likely take me a couple weeks to get to this. I do have some plans to add a few new features and some performance improvements to Coverband. I will keep this on the list.

Thanks

**Comment by kbaum** [comment]
+1 for this.  I think it would be very helpful to be able to see what Gems are actually still being used.  Does anyone else's Gemfile just keep growing? :wink:

**Comment by dmitry** [comment]
@kbaum you can use a standard coverage tools to check if gem is used or no.

**Comment by kbaum** [comment]
@dmitry - I guess you could know if it's being hit in tests, but you don't know if anything is actually using it in production.

**Comment by dmitry** [comment]
@kbaum I guess it's possible with coverband:

```
config.root_paths       = ['/server/apps/my_app/releases/\d+/'] 
```

**Comment by kbaum** [comment]
Currently there is a hardcoded exclude of gems:

https://github.com/danmayer/coverband/blob/master/lib/coverband/base.rb#L45

**Comment by danmayer** [comment]
yeah we could make that configuration optional... @dmitry could you share more about why you want to see gem usage in a project. I always imagined people caring about the application under development. Is this to view internal company gems and rails engines etc?

**Comment by dmitry** [comment]
The idea of @kbaum was to check if the gem is still used or no. From my side I think it would be very good to check what places of the gem are overused, so they could be optimized directly in the gem (we don't have any internal gems).

**Comment by apsoto** [comment]
My original request for this issue was because of shared internal gems/engines

**Comment by danmayer** [comment]
OK, so I am going to close this one out with some notes...

* You can record gems on the old tracepoint by setting `Coverband.configuration.include_gems` this will not filter them out. After that you need to make sure you have them loaded and covered by your watch patterns and not ignored by your ignore patterns. So by default, it should be very easy to get this with the TracePoint collector
* The new Coverband Coverage collector also will record Gems, it always collects all things loaded before `Coverband.start` so you would just need to call it prior to requiring all your gems, or using the `safe_reload_files` config options to force gem files to reload.
* While the above feature works to display gems it requires all the paths of all the gems. I think to capture and report ALL gem usage, one would need to ensure that Coverband is loaded PRIOR to loading the rest of the Gems included in the Gemfile. 

I added some documentation to the readme to help make this more clear.

https://github.com/danmayer/coverband/commit/462c1e2b4d45260db364a6e7769d9882dec7a102
and
https://github.com/danmayer/coverband/commit/5f2827301c897dfd91fffe7234d67ee850bc28b4

Thanks @apsoto / @dmitry / @kbaum
