### ISSUE TITLE
Build failing for rails 4 ruby 2.5.X

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#212]
Looks like rails needs bundler to be < 2.0. We are trying to install an older version of bundler but for some reason travis is not having it.

![image](https://user-images.githubusercontent.com/96786/54475099-d9378500-47c3-11e9-85ac-2add9c3e36ba.png)

**Comment by danmayer** [comment]
fixed, had to add another line to the circleCI hack to delete 2.0.1 on another version of Ruby
