### ISSUE TITLE
re-investigate view layer support

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#215]
While stdlib Coverage doesn't support correct runtime line coverage of compiled view templates. I believe you can get a number of hits to an individual view file. This would still be very helpful in finding dead view files. We could likely give something similar to the Gem index view without the details layer for view files... the number of times eager loaded / executed for the full file.

If we could add any support for view files back, it would be a compelling feature.

**Comment by danmayer** [comment]
This, by the way, was a real-world request for folks using the gem at my work ;)

**Comment by danmayer** [comment]
My first attempt at this didn't go well... I will rethink this and perhaps give it another go

**Comment by jjb** [comment]
Would definitely be interested in stats on if a file got 0 hits.

**Comment by danmayer** [comment]
I believe I now have a good working model for this... but need to get the current memory issues/release under control first.

**Comment by felix91gr** [comment]
Would love it if coverband could track view files usage. Not even in production: just in local development would be enough for me (not sarcastic at all: if there is a way to make it track views, I don't know it x3). Although in production would of course be awesome.

I found the gem precisely whilst looking for this functionality... will keep tabs on the thread, just in case you manage to make it work @danmayer <3

**Comment by danmayer** [comment]
I have found a good solution and our other release is out, I should be able to work on this sometime in the next couple weeks.

**Comment by danmayer** [comment]
You can follow along with the spike here, but view layer tracking at the file level at least should make the next release. https://github.com/danmayer/coverband/pull/306

**Comment by danmayer** [comment]
The view tracker is live and probably could be considered out of alpha/beta as it has significant real-world production usage. 

Closing this
