### ISSUE TITLE
Add rubocop to the project

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#220]
It's always nice to have rubocop on a ruby project so everyone is following the same rules.

 I use vim ale which autocorrects based on rubocop settings. I'm sure other editors have the same type of help.

**Comment by danmayer** [comment]
yeah, I have been using Rubcop on the project already, I just haven't setup CI to enforce or checked in the ruleset which means often things deviate from my rules... Good call that we should just get it checked in and configured so everyone can use it the same.

**Comment by kbaum** [comment]
@danmayer - should we add codeclimate? I think this includes rubocop checks.

**Comment by danmayer** [comment]
yeah we could add that since we are open source it should be free

**Comment by kbaum** [comment]
Agreed. I tried to add but i don't think i have permission.

**Comment by danmayer** [comment]
This is coming after the next release because we will want to do a large refactoring to match the initial default rules pretty quickly and I didn't want to add that into the fairly large code changes.

**Comment by danmayer** [comment]
OK, beyond rubocop on CI we also have code climate attached and following the repo. I didn't move code coverage over to Code climate yet but we can perhaps move over to that in the future.

https://codeclimate.com/github/danmayer/coverband
