### ISSUE TITLE
Coverband Needs A Logo

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#221]
Anyone from the design world looking to contribute to an open source project? My design skills are not good. I would love to have a cool logo for Coverband's readme, favicon, and web-ui

Happy to help review, answer questions, etc if someone wants to work on this.

![Your_Logo_Here_Round_Ornament_300x300](https://user-images.githubusercontent.com/24925/55005480-b1090c80-4fa1-11e9-80bc-1c93d95ba284.jpg)

**Comment by davewoodall** [comment]
Hey @danmayer! Dave, from LS / Boulder office days. We had a good walk around the block, once 😄 
I'm not a logo designer but I like to doodle. I'd be willing to give it a shot if you'd like. Take a look at [some of my old doodles](https://dribbble.com/fakefarm/) and see if what I can do matches what you are thinking for 'skill level'.

**Comment by danmayer** [comment]
Yeah man that would be great. I love the little animals perhaps a few playing instruments as a band? Open to whatever direction you want to give it a go.

**Comment by mirzazulfan** [comment]
Hi @danmayer I've designed a logo, what do you think? if you have an idea please share with me, it would be better for me. Best regard. :)
![coverband](https://user-images.githubusercontent.com/36124339/55536488-17013c80-56e4-11e9-9a6a-34b64ebd2c75.png)

**Comment by danmayer** [comment]
Thanks @mirzazulfan these are cool. I like how the colors would work well to indicate coverage or percentage good. Might need a red to cover the bad cases. 

I really appreciate you submitting some designs, thanks so much.

I am trying to decide if the `</>` in the middle makes it too busy. I like the idea of trying to make the logo play off the idea of small local bands that play cover songs, or perhaps just music like vibe... Not sure if that gives you something directionally to think about. The current one doesn't quite have a music feel to me, but a bit more of an electronics...

**Comment by davewoodall** [comment]
Those are creative. Nice work @mirzazulfan!

I have a music concept in mind that I'm going to work on later today. @danmayer, would you happen to have a few sizes in mind of where you'd ideally be using this?  What's the biggest _and_ smallest you'd see using this?

**Comment by danmayer** [comment]
smallest is a favicon but that could continue to just be green, yellow, red squares to indicate status... nav bar would be the most common and visible in the UI. Think the top left of a nav bar to go "home"... Then on the readme, demo site, and promotional stuff as a bigger hero like logo.

some could be logo only some could be logo and text

**Comment by mirzazulfan** [comment]
Thank you guys. I made the 2nd version, hope you like it.
![cbv2](https://user-images.githubusercontent.com/36124339/55620026-1fc93f80-57c4-11e9-8376-981f3bad54be.png)

**Comment by danmayer** [comment]
Cool, thanks @mirzazulfan  I think I like the bottom design best with the circle, although that makes it harder to tell it is a 'b'.

What formats do you have the designs in? 

Any update @davewoodall would still love to see what you were thinking as well...

**Comment by mirzazulfan** [comment]
Glad to know. I'll send the .svg .png format and all the files and sizes needed. So what color do you prefer? @danmayer 
![cb2](https://user-images.githubusercontent.com/36124339/55671594-de1bc000-58bb-11e9-9ddd-8a0c6d0d520d.png)

**Comment by davewoodall** [comment]
Hey Dan,

I'm trying to incorporate the 3 colors of the app (red, yellow, green) with the music concept. Included are the black and white concepts as well as a 2nd copy with loose coloring to see where I might take the vector art. So far, I have put together 24 concepts which really fall into 3 main idea;

## Idea 1. Instruments
Incorporating C & B into instruments. I thought about the C fitting into a banjo, and the B into an 80's guitar. 

## Idea 2. Music Poster
Then, I thought about a music poster, where the tacks are the 3 color dots. 

## Idea 3. Musicians
I also thought about a cover band being the musicians. 

## From here, options as I see it...

- [ ] 1. As you can see, I'm still at the concept phase. So, if you are in a rush, I'd suggest going with @mirzazulfan's ideas. (I like the red / black one the best). 
- [ ] 2. If you like any of these 24, I'd be happy to proceed with 1 or 2 of these concepts into vector art
- [ ] 3. Or, if these influence you to think of a new direction, I'd be happy to sketch another page of concepts.
- [ ] 4. Another direction?

![cover_band_sketches_1](https://user-images.githubusercontent.com/587705/55686967-a9e4e580-5935-11e9-8ecf-c9500023795d.jpeg)

![cover_band_sketches_color_1](https://user-images.githubusercontent.com/587705/55686966-a9e4e580-5935-11e9-9abc-db1a7fb9e02f.jpg)

**Comment by danmayer** [comment]
I think it could we worth exploring a bit more before making a final decision, haven't had a logo for 7 years so no reason to rush into it ;) @davewoodall 

I like 1, 6, 2 1

I think 21 could be the most fun an allow for some interesting UI like a different person / circle for each color (or status)... Also, having people allows for changing them up a bit from time to time, like the Octocat for GitHub. I guess if you wanted to take that and make a vector version it would be cool to check out.

**Comment by davewoodall** [comment]
Sounds good, @danmayer. I'm thinking we start with 21. Because I agree with your vision and that one is my favorite as well. Depending on how it turns out we can move onto the next. @mirzazulfan, any interest in collaborating / working on these concepts?

![Screen Shot 2019-04-08 at 6 35 30 PM](https://user-images.githubusercontent.com/587705/55761388-1db5e980-5a2d-11e9-8abb-6392364e1632.png)
> I think 21 could be the most fun an allow for some interesting UI like a different person / circle for each color (or status)... Also, having people allows for changing them up a bit from time to time, like the Octocat for GitHub. I guess if you wanted to take that and make a vector version it would be cool to check out.

**Comment by danmayer** [comment]
cool looking forward to seeing what you come up with

**Comment by davewoodall** [comment]
How's this?
![v1](https://user-images.githubusercontent.com/587705/56163767-29f5f580-5f9d-11e9-8221-93fdae184951.jpg)

**Comment by danmayer** [comment]
Nice, I dig it. 

Thoughts...

* perhaps try a font alternative (if you already have and this is best no worries)
* I assume the vector files we could pull out any of the circle / colors to use for favicon / status

I like how versatile it can be I can see using it a number of different ways, which is really cool.

Any thoughts or word @mirzazulfan ?

**Comment by danmayer** [comment]
So @davewoodall thoughts for next steps? I am thinking a PR that

* adds the vector files to /docs
* inserts image near top of the readme
* then I can set the logo to be the social image for the git repo: https://twitter.com/natfriedman/status/1118590385180200961?s=19

**Comment by davewoodall** [comment]
@danmayer, 

Great to hear!

> perhaps try a font alternative (if you already have and this is best no worries)

I did poke around with some fonts but nothing stood out. How about this idea... if you're okay with this font for now, then I will PR this one. If a better font comes to mind, then I can swap it out then?

> I assume the vector files we could pull out any of the circle / colors to use for favicon / status

Yep, and if you want me to put different hues, I'm happy to do that as well. 

> Thoughts for next steps? 

If you have any specific sizes / arrangements to use, I can format them and provide for easy consumption. 
Otherwise, I can just upload the logo as is.  (I'm happy to help until further notice.) 

>  I am thinking a PR

Will do! I will post a PR tomorrow, I don't have the assets on this machine.

**Comment by danmayer** [comment]
sounds good on the font

yeah if you can put in a few different hues on the red -> green type failed -> success scale that would be great.

On sizing whatever you think looks best for the readme logo size to start once I work with the files I can show you where they are used in the UI and you can perhaps make adjustments as needed

**Comment by davewoodall** [comment]
Today got away from me. I will do it first thing next week!

**Comment by danmayer** [comment]
no worries thanks @davewoodall

**Comment by danmayer** [comment]
awesome @davewoodall merged and updated the social share image, I will start to work on using it in the web-ui as well.

Closing this out thank!

**Comment by danmayer** [comment]
OK @davewoodall Your logo made it into the 4.2.0 release! https://github.com/danmayer/coverband/blob/master/changes.md#coverband-420

I called out the logo on twitter, but I can't find you anymore on twitter did I miss you? Or somewhere else I can give you some credit?

**Comment by davewoodall** [comment]
Great to hear! I'm not on twitter and I didn't do this for credit but if you insist, feel free to share my homepage. 😊 [davewoodall.com](http://www.davewoodall.com). Thanks, @danmayer!

**Comment by danmayer** [comment]
yep understood not for the credit, but always nice to share when someone does something awesome. I update the readme and changes log to thank you and link to davewoodall.com
