### ISSUE TITLE
Following README instructions to "Ignore Files" causes gems to be tracked

### ISSUE THREAD

**Issue by bhb** [danmayer/coverband#230]
Environment: 
* Rails 5.2.3
* Coverband 4.2.0.rc1

Repro:

1. In new Rails app, add config file at `config/coverband.rb` with contents
1. Set up route to view coverage report https://github.com/danmayer/coverband#coverage-report

```ruby
Coverband.configure do |config|
end
```
1. According to [these instructions](https://github.com/danmayer/coverband#ignoring-files), add the following config changes

```ruby

config.ignore =	['config/application.rb',
                   'config/boot.rb',
                   'config/puma.rb',
                   'config/schedule.rb',
                   'config/environments/test.rb',
                   'config/environments/development.rb',
                   'config/environments/staging.rb',
                   'config/environments/production.rb',
                   'lib/tasks/*']
```

1. Boot Rails app, load a page
1. Visit coverband page  at `/coverage`

Expected: Gem should not be tracked
Actual: Gems are tracked. Adding `config.track_gems = false` has no effect, since this is already the default

My solution was to change `config.ignore =` to `config.ignore +=`. Not sure if this is the correct workaround (and therefore it's just a question of a 1-line change to the README) or if this behavior is not expected.

**Comment by kbaum** [comment]
Thanks for reporting this issue. I think this seems like a straight forward solution in that allows for maximum flexibility for someone to actually overwrite the defaults if that's what they wanted. @danmayer  update the readme to match the `+=` approach?

**Comment by danmayer** [comment]
yeah makes sense, I will update the readme now, it is actually how I update the config in the demo app. I am wondering if we should give a warning if someone actually fully overwrites ignore since it can have unexpected consequences.

https://github.com/danmayer/coverband_demo/blob/master/config/coverband.rb#L19

**Comment by danmayer** [comment]
updated the readme to match the `+=` usage.

https://github.com/danmayer/coverband/commit/f5bbf02462c2d8dca37a149eb4e307306f4e58ed

**Comment by danmayer** [comment]
fixed this so that the next release either `=` or `+=` will work without any confusion. see details https://github.com/danmayer/coverband/commit/e6b944b593f8ac572b6b56d5ed703b4f905b4aa1

//cc @bhb
