### ISSUE TITLE
Add runtime percentage to Gems tab

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#237]
![image](https://user-images.githubusercontent.com/96786/56772771-5ffb5c80-6789-11e9-8114-c80c3c392381.png)

Since gems are required on eager load, it would be great to see which gems are used at runtime. If a gem is not used at runtime, it's a good candidate to remove from Gemfile.

**Comment by danmayer** [comment]
good call and this will be easy to add basically I just didn't update / refactor the gem templates to share and be more like the standard file templates.

**Comment by danmayer** [comment]
We can definitely get this in the next release.
