### ISSUE TITLE
Coverband not started when rails app is running

### ISSUE THREAD

**Issue by cawel** [danmayer/coverband#24]
I have tried to set up Coverband in my rails project (as a middleware) following the readme's instructions. I managed to create an HTML report for the baseline (using the rake task), but I'm not able to create a report for the requests done while my app is running.

Running `rake middleware` shows that the middleware is loaded, because I see `use Coverband::Middleware` in the middleware listing output.

My hypothesis was that Coverband was never started, because I see `coverage disabled` in my rails server console output for every request. So I tried to force a start with `Coverband::Base.instance.start` in the `config.ru` file, but it didn't change anything.

Also, I noticed that `rake coverband:clear coverband:coverage` gives me the same report as the report for the baseline. But I would have expected no coverage at all (no lines hit whatsoever).

So then I tried to force it another way. I added an `around filter` in my `application_controller`:

```ruby
around_filter :force_coverage

def force_coverage
  Coverband::Base.instance.start
  yield
  Coverband::Base.instance.stop
  Coverband::Base.instance.save
end
```

And finally, that gave me some coverage at runtime. But from what I understand, I shouldn't be required to add that code. 

Can you help me figure out what am I missing?

**Comment by danmayer** [comment]
Have you setup a `config/coverband.rb` file?

My guess is you just need to setup the coverage percentage

` config.percentage        = Rails.env.production? ? 30.0 : 100.0`

See configuring [coverband section](https://github.com/danmayer/coverband#configure-coverband-options) section of the readme for more details.

you might also want `config.startup_delay     = Rails.env.production? ? 15 : 2`

 Let me know if that works for you. I would remove your `around_filter` as that is basically what the middleware does with some additional logic.

**Comment by cawel** [comment]
I did setup the `config/coverband.rb` file. But you were right, I omitted that line:

`config.percentage = Rails.env.production? ? 30.0 : 100.0`

I guess I assumed the default value would be 100%.

I removed my `around_filter`. It works as expected now. Thanks!

**Comment by danmayer** [comment]
yeah perhaps I should output config settings on boot or something the default is actually 0.0 because it could cause unexpected perf issues if you haven't tuned things and understand the system.
