### ISSUE TITLE
Coverband::Reporters::HTMLReport.fix_reports method is incorrectly setting filtered_report_files

### ISSUE THREAD

**Issue by ckumar1** [danmayer/coverband#242]
The [`fix_reports`](https://github.com/danmayer/coverband/blob/v4.2.0/lib/coverband/reporters/html_report.rb#L51-L61) method is setting the value of `self.filtered_report_files` to `reports` instead of `filtered_report_files` so it is missing all the files that were not tracked by coverband. This causes the generated report to be inaccurate and only count files that were tracked by coverband.

The `fix_reports` method should look like this:

```
def self.fix_reports(reports)
  # list all files, even if not tracked by Coverband (0% coverage)
  tracked_glob = "#{Coverband.configuration.current_root}/{app,lib,config}/**/*.{rb}"
  filtered_report_files = {}

  reports.each_pair do |report_name, report_data|
    filtered_report_files[report_name] = {}
    report_files = Coverband::Utils::Result.add_not_loaded_files(report_data, tracked_glob)

    # apply coverband filters
    report_files.each_pair do |file, data|
      next if Coverband.configuration.ignore.any? { |i| file.match(i) }

      filtered_report_files[report_name][file] = data
    end
  end
  filtered_report_files
end
```

**Comment by danmayer** [comment]
Thanks looks good I will add tests and get this added in soon.

**Comment by danmayer** [comment]
Files that aren't showing then have 0 load or runtime coverage, which we should help surface so folks can delete

**Comment by danmayer** [comment]
Just added some tests on a branch that will make it much easier to verify and fix this issue, likely will get to that tomorrow

**Comment by ckumar1** [comment]
Sounds good, I'll continue to test this use case and let you know if any other issues come up.
