### ISSUE TITLE
Clearing coverage generates coverage

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#249]
Start with an empty redis using redis-cli:

```
redis-cli
127.0.0.1:6379> flushdb
OK
```
Execute clear coverage task:
```
bundle exec rake coverband:clear
```
Then look in redis using cli:
```
redis-cli
127.0.0.1:6379> get "coverband_3_2"
```
And there will be some data.

The same issue occurs with `coverband:coverage`.

This can be very problematic if someone is generating coverage from their local machine while pointing at production. In my case this is needed since our rails server is api only and I cannot host the report within the production application. I end up writing coverage data from my local dev machine into production.

**Comment by danmayer** [comment]
hmm, interesting, guessing that `at_exit` on the rake task writes coverage AFTER clearing it. I think having the internal Coverband tasks disable `at_exit` on load is the best approach here. I will take a look at that.

**Comment by danmayer** [comment]
confirmed it is `at_exit` fixing for all rake tasks
