### ISSUE TITLE
Issue with ruby coverage and || statement spanning 2 lines

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#256]
Noticed an issue today with the ruby coverage standard library that I reproduced in this project:

https://github.com/kbaum/coverage_test

See README for more detail. 

I think this is a bug in ruby coverage, but wanted to see what people thought.

Thanks to @CharlesMcMillan for bringing it to my attention.

thx.

**Comment by danmayer** [comment]
I think this could be addressed by adding branch support, which was added in 2.6.0

https://bugs.ruby-lang.org/issues/13901

**Comment by kbaum** [comment]
Oh neat! I didn't know about that.

**Comment by danmayer** [comment]
Just adding a note, we now handle if branching and other newer coverage features are enabled... but Coverband doesn't utilize that data. I think unless we see high demand, I would avoid this as it will add to the CPU, memory, and complexity of the project.

**Comment by danmayer** [comment]
closing as `wontfix` for now
