### ISSUE TITLE
Overall Coverage Since Date

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#260]
I think it's helpful to know when the last time coverage was cleared for the entire project:

![image](https://user-images.githubusercontent.com/96786/57770158-af281380-76dd-11e9-8477-116a2b10c8bb.png)

This might help the user to be more/less confident in the coverage data they are seeing on the summary page.

**Comment by danmayer** [comment]
cool added this feature.

https://github.com/danmayer/coverband/commit/70c9f9a63f8ace7c2d7573fe2c8d1c2706dd47b9

<img width="1675" alt="Screen Shot 2019-05-19 at 10 53 19 AM" src="https://user-images.githubusercontent.com/24925/57985460-9e510800-7a25-11e9-9328-a5996ff06a61.png">

**Comment by kbaum** [comment]
That looks great! Love the human readable date there. Good call!
