### ISSUE TITLE
Runtime percentage calculation seems off

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#262]
This file has 100% overall coverage but only 33.33% runtime coverage:

![image](https://user-images.githubusercontent.com/96786/57883698-fead3300-77f4-11e9-8e84-141b9e9adc42.png)

Here are the details of the coverage:

![image](https://user-images.githubusercontent.com/96786/57883763-2dc3a480-77f5-11e9-9468-14d2cc6c73af.png)

The 33.33% is coming from 2 runtime lines over 6 relevant lines. The relevant lines are including eager_load lines. Would expect that instead 2 out of the 2 runtime lines were covered which would give 100%.  

The 33.33% is misleading here because users of coverband want to find files which have a low percentage of their runtime lines covered. In this case, this file has full coverage on the runtime lines but is still reporting low runtime coverage.

**Comment by danmayer** [comment]
yeah I became aware of this recently the 'runtime' vs not is a bit hard as we don't have a great 'relavent' lines count only for runtime. For a full file that is calculated with all the ignored lines (comments, white space, etc) for this it is similar to the request about detecting bad methods we would need to parse and know the difference between class, method, and namespace definitions. Something that Coverage itself doesn't know.

**Comment by danmayer** [comment]
So one thing we could perhaps do is take relevant lines as all default and then pull out all relevant lines... So this equation.

runtime_relavent =  default_relevant_lines - initialize_relevant_lines

I think this would give the number you are thinking of.

This would make any approaches to lazy loading really hard as the `% runtime coverage` is needed on the index not just on the file details page.

**Comment by kbaum** [comment]
This is a very interesting idea. Lines that are only covered on app initialization are not counted as runtime relevant.

**Comment by danmayer** [comment]
the branch implementing this fix was merged
