### ISSUE TITLE
Listing 0% coverage gems

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#263]
We only list gems that have some type of coverage. Listing the gems with 0 coverage could inform what can be removed.

**Comment by danmayer** [comment]
Can probably parse bundler, are we good making this dependant on bundler?

**Comment by danmayer** [comment]
I guess also I would expect ANY gem that is in bundle file to have load time coverage and therefore appear? How would this case ever occur?

Is this only an issue as it relates to this other bug https://github.com/danmayer/coverband/issues/261

**Comment by kbaum** [comment]
Good questions. I think this may be gems that are listing dependencies in their gemspec that are never required?

**Comment by kbaum** [comment]
Also could be the projects gems with `require:false`.

**Comment by danmayer** [comment]
I believe we could list `Gem.loaded_specs.keys` then list anything in that list that doesn't appear in Coverage.

**Comment by danmayer** [comment]
I merged this in
