### ISSUE TITLE
Exclude tests from coveralls

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#266]
Noticed tests were being counted for coverage within coveralls.
![image](https://user-images.githubusercontent.com/96786/58096805-e5fd9e00-7ba3-11e9-9220-c305e9d6a1e6.png)
Think we should exclude as some of our tests actually fork so it brings our overall coverage numbers down.

**Comment by danmayer** [comment]
good find and agreed

**Comment by danmayer** [comment]
fixed should be easy to add filters for anything we don't consider valuable

https://github.com/danmayer/coverband/commit/371eae4e1b1f6d3fdf1cd3ad41e377036226089c
