### ISSUE TITLE
Rubocop gemspec file paths showing incorrectly in report

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#268]
![image](https://user-images.githubusercontent.com/96786/58356344-39424b80-7e45-11e9-904f-f9b0980165c5.png)
![image](https://user-images.githubusercontent.com/96786/58356421-6bec4400-7e45-11e9-846b-3aed3ed41d97.png)

Looks like this might be a string replace issue since these files have the word "gem" in their path:

`lib/rubocop/cop/gemspec/required_ruby_version.rb`
`lib/rubocop/cop/gemspec/ordered_dependencies.rb`

**Comment by danmayer** [comment]
resolved https://github.com/danmayer/coverband/commit/f0c30d3d8a5e8551beda5968a2da94a4cd148077

**Comment by kbaum** [comment]
Thanks for fixing this. Pulled the latest this morning and noticed that all of the gems have a `.`:

![image](https://user-images.githubusercontent.com/96786/58381917-5d12a800-7f91-11e9-8865-09d549ea9f9f.png)

**Comment by danmayer** [comment]
oops noticed that as well, I will resolve.

**Comment by danmayer** [comment]
resolved and update test 
 https://github.com/danmayer/coverband/commit/da68a4202516e369f033f539ebd8f2e5751a063c
