### ISSUE TITLE
when developing locally coverband tests wipe our local app coverage

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#271]
I wasted about an hour debugging this. As I was working on verifying Coverband changes in local apps, and the data kept getting into really weird states and breaking because runtime data was missing... Turns out this happens because running `bundle exec rake` on Coverband will wipe out any local data you have.

Thinking we could purposefully have all Coverband tests run in a `coverband_test` namespace to avoid colliding with local apps using coverband.

**Comment by kbaum** [comment]
Bummer that you lost time on this. I like the idea of a separate namespace for test though.

**Comment by danmayer** [comment]
resolved with #273
