### ISSUE TITLE
clear runs reporting

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#272]
I thought we fixed this but when I run `bundle exec rake coverband:clear` on the coverband demo app I get the below output.

```
bundle exec rake coverband:clear
D, [2019-05-27T15:10:53.311865 #24757] DEBUG -- : Coverband: Starting background reporting
D, [2019-05-27T15:10:53.375899 #24757] DEBUG -- : Coverband: Reported coverage via thread. Sleeping 30s
```

**Comment by danmayer** [comment]
any ideas, since I think you noticed and resolved last time

**Comment by kbaum** [comment]
Did some investigation. Coverband is being required when rails is required within the Rakefile. Coverband automatically invokes start and background thread is default true.

```ruby
  def self.start
    Coverband::Collectors::Coverage.instance
    # TODO: Railtie sets up at_exit after forks, via middleware, perhaps this hsould be
    # added if not rails or if rails but not rackserverrunning
    AtExit.register
    Background.start if configuration.background_reporting_enabled && !RackServerCheck.running?
  end
```
Kind of a bummer because I like the solution we tried here. Not sure of the best fix yet. 🤔

**Comment by danmayer** [comment]
I have a path forward to at least resolve for the next release as we explore other options... will post PR shortly

**Comment by danmayer** [comment]
resolved
