### ISSUE TITLE
ungrouped gem files added during listing of 0% usage gems

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#276]
looks like that didn't fix all cases, unfortunately, caught this while testing the first published release candidate... So going to have to fix and release rc2

related to
 https://github.com/danmayer/coverband/pull/274

![Screen Shot 2019-05-29 at 9 52 54 PM](https://user-images.githubusercontent.com/24925/58607270-2e7c2200-825c-11e9-9e34-3c2c97be0735.png)

**Comment by danmayer** [comment]
looking quickly now @kbaum  to see if I can get a release candidate out that I can run for overnight testing.

**Comment by danmayer** [comment]
got a fix seeing if I can add a test

**Comment by danmayer** [comment]
OK take a look at this @kbaum  https://github.com/danmayer/coverband/commit/d4388096e652b44f2b29c42197809fa596ec732c

Basically, there was a known issue where I knew there were multiple gem paths but we only defaulted to the first one as I had never seen a usage that needed the others... Well, I guess default gems like Rake and such can use the secondary paths if you have some gems locally and some ruby-version or system wide.

**Comment by danmayer** [comment]
hmm OK so this is fixed but before and after this fix the index with Gem details on is really really slow now. I think because I now report on a ton more gems, most of them seem to be Gems that I don't directly use but must be required or loaded as dependencies of others. While this might be helpful, it also has a high cost on reporting...

Do you think we could add a config option to `display_all_loaded_gems = true` to allow toggling this feature on and off. I was pretty sure I would be able to enable Gems on our app, but with this most recent feature, it is back to being to slow to load the reporting.

Take a look at the reporting...

https://coverband-demo.herokuapp.com/coverage/

Also, feels odd now Arel is listed and shows 0% coverage but shouldn't that be hit by my AR calls under the hood?

**Comment by kbaum** [comment]
> Do you think we could add a config option to display_all_loaded_gems = true to allow toggling this feature on and off.
I like this idea. Would give us a chance to speed up the report in the meantime.

> Also, feels odd now Arel is listed and shows 0% coverage but shouldn't that be hit by my AR calls under the hood?

Definitely odd. It could be because Arel is required before we start tracking coverage.

**Comment by kbaum** [comment]
Starting to wonder whether this feature is worth it. Some gems like rails will never be tracked if they are required before coverband. Since rails has so many dependencies, those gems will also not be tracked. With this new feature, all of those gems will show up as 0% coverage. This may end up confusing people and reducing their confidence in the coverage data.

**Comment by danmayer** [comment]
yeah agreed and that would explain Arel as it is required first...

So I think we can put it behind a flag with default false and work on it as experimental or rip it out for now... Behind the flag we could work on it a bit more and see if we could get it to a valuable point.

Thoughts @kbaum

**Comment by danmayer** [comment]
Still feels like all of the Gems support needs a bit more work, as we got this report as well... Probably need to error on the side of stability and performance while we sort out any remaining perf issues related to Gems... Perhaps also update the Readme that Gem is more experimentally support and recommend all new deployments start with it disabled to verify things work before enabling gem tracking?

https://github.com/danmayer/coverband/issues/277

**Comment by kbaum** [comment]
> So I think we can put it behind a flag with default false and work on it as experimental or rip it out for now.

I think we rip it out 0% gem usage. It doesn't seem useful enough compared to the confusion it introduces for the users and for the developers. I will open up a revert PR.

**Comment by danmayer** [comment]
calling this resolved

**Comment by danmayer** [comment]
perf seems much better on RC3 https://coverband-demo.herokuapp.com/coverage
