### ISSUE TITLE
Multi-threaded environment

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#28]
Been getting more familiar with the code and it does not look like Coverband was meant to be used in a multi-threaded environment.  For example, ```Coverband::Base``` is a singleton keeps state of the current request.  In a multi-threaded environment such as Puma or Sidekiq, the worker threads would step on each other.  

To be honest, i am not sure how possible it would be to make this library thread safe as each request or worker calls set_trace_func.

Just wanted to start a discussion on this as Sidekiq and Puma have become very popular and more rails installations are relying on a multi-thread model.

thx!
-karl

**Comment by danmayer** [comment]
The base would be easy enough to use `Thread.current` variables for all storage needs. I think the question would be more as you mentioned around the `set_trace_func` and  `C_extension` I haven't really explored what issues if any arise in these scenarios, but it is a good point.

**Comment by kbaum** [comment]
I used your comment as a hint:

https://github.com/danmayer/coverband_ext/compare/master...kbaum:use_current_thread

There's not much out there as far as documentation but this seems to work in that it doesn't cause anything to crash :smile:

**Comment by kbaum** [comment]
Closing this as this has been handled.
