### ISSUE TITLE
Tagging conventions for release candidates

### ISSUE THREAD

**Issue by ckumar1** [danmayer/coverband#288]
Hey! In the future could we standardize tagging release candidates in the following format: `v4.2.1.rc.3` instead of `v4.2.1.rc3`?

This will allow bundler to match `~> 4.2.1.rc` to prerelease versions like `v4.2.1.rc.2` and `v4.2.1.rc.3`.

**Comment by danmayer** [comment]
yeah, good call I didn't know bundler would work like that on release candidates. 

Thanks for the tip I will adopt this for the next version.

**Comment by danmayer** [comment]
prepping RC 4.2.2. release candidates and this has been implemented thanks @ckumar1 closing it now
