### ISSUE TITLE
drop old Ruby and Rails versions to clean up code

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#291]
I would like to propose that we drop Ruby 2.3, 2.4 and Rails 4 support in Coverband 5. 

This would allow us to clean up various parts of the code and simplify some of our testing.

I am worried with the growing complexity of Coverband particularly when I look at how much simpler one could build a Ruby 2.6 only version that would be much simpler, faster, with less memory needs... I don't think we could realistically drop Ruby 2.5 yet but we could work towards that and start to optimize for 2.6 and have shims for 2.5.

For example between the new `one_shot` format and `Coverage.line_stub` one could significantly reduce our JSON structure...

moving from an array with an index for each line... `[1,0,nil,0,nil,nil,nil,nil,nil,1] etc` to the spares one_shot format... `[1,12,42]` This would be a huge improvement in our serialization and moves from having to merge_array math to just `(arr1 + arr2).uniq`

**Comment by danmayer** [comment]
Anyone that is a user please let me know if there are good reasons to keep older support...

**Comment by kbaum** [comment]
If we wait until Dec 25th, the policy could be that coverband supports 3 ruby versions. Lines up with what heroku looks to be doing:

https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

That might be longer than we want to wait.

**Comment by danmayer** [comment]
yeah that feels a bit long to me, it isn't a bad idea and I like following a company standard... I know a good number of companies only support the latest two Major versions of Rails / Ruby... 

That feels a bit more sustainable long term, but I would be willing to match Heroku if folks mention running on older versions.

**Comment by danmayer** [comment]
I guess because I would like to make a call, do we want to match Heroku... Make that decision for now and move on with that?

**Comment by kbaum** [comment]
One other way to think about this. An old project with lots of dead code that needs a rails or ruby upgrade would benefit from using coverband more than a fresh lean project that is probably on latest version of ruby or rails. 

I vote for matching what heroku supports.

**Comment by danmayer** [comment]
sounds good, this PR should let us close this @kbaum let me know if the wording could be improved.
