### ISSUE TITLE
is redis TTL in seconds or milliseconds?

### ISSUE THREAD

**Issue by jjb** [danmayer/coverband#293]
I drilled down to figure it out myself but then would have to go over to the client library so I figured I would ask to be sure.

I'll submit a PR with doc changes.

**Comment by danmayer** [comment]
It is called here: https://github.com/danmayer/coverband/blob/master/lib/coverband/adapters/redis_store.rb#L100

and should be seconds
https://www.rubydoc.info/github/ezmobius/redis-rb/Redis:expire

thanks @jjb a PR making this more clear would be welcomed!

**Comment by jjb** [comment]
https://github.com/danmayer/coverband/pull/294
