### ISSUE TITLE
default redis ttl and namespace?

### ISSUE THREAD

**Issue by jjb** [danmayer/coverband#295]
I wonder if a default namespace of "coverband" and ttl of 1 month might make sense?

**Comment by kbaum** [comment]
Agreed on the ttl default.

Not sure we need the default namespace considering the format version is already part of the key

```
REDIS_STORAGE_FORMAT_VERSION = 'coverband_3_2'
```

**Comment by danmayer** [comment]
OK someone want to do a PR with 1 month default TTL
