### ISSUE TITLE
Occasional mix ups on load vs runtime

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#301]
I am seeing occasional bad data where runtime code coverage is marked as load coverage. This seems to happen kind of randomly after a restart of Coverband Demo, also seeing it on production servers.

<img width="1606" alt="Screen Shot 2019-07-21 at 3 06 15 PM" src="https://user-images.githubusercontent.com/24925/61597100-2770f080-abc9-11e9-86f5-a9e6b73c2500.png">

**Comment by danmayer** [comment]
If you have zero runtime that is a different issues @souljadev, sounds like you are never getting to the code that does after-initialize which moves from load to runtime. Could you share your coverband version, rails version, and some of what your `config/coverband.rb` looks like Something isn't setup correctly or is in the wrong order.  

In your Gemfile you have Coverband, and don't have require 'false' set?

**Comment by danmayer** [comment]
also, check that you have ` config.eager_load = true` in production.

If your controllers are also missing coverage data, seems like your app code is getting loaded before Coverband... so something about your gemfile, or initializers is out of order.

See how it is setup in the demo for general best practices https://github.com/danmayer/coverband_demo/blob/master/Gemfile#L87

**Comment by kbaum** [comment]
Just shed some more light on how eager vs runtime is tracked in coverband.

https://github.com/danmayer/coverband/blob/master/lib/coverband/utils/railtie.rb

When eager_load is called by rails, coverband is set to eager_loading mode.

https://github.com/danmayer/coverband/blob/master/lib/coverband/utils/railtie.rb#L6

Once rails finishes initialization, it's set to runtime:

https://github.com/danmayer/coverband/blob/master/lib/coverband/utils/railtie.rb#L29

Are you testing in development environment or production? Keep in mind that development environment does not have eager loading set to true.

**Comment by danmayer** [comment]
this should be fixed in the 5.0 release

**Comment by danmayer** [comment]
This was resolved in the 5.0 release which is now live, closing
