### ISSUE TITLE
How to access admin / clear data?

### ISSUE THREAD

**Issue by jjb** [danmayer/coverband#321]
At mysite.com/coverage, "Coverband Admin" links to mysite.com/coverage, and "Info" links to mysite.com/coverage/settings. clicking Coverband Admin of course takes me to the same place I already was, and clicking on Info takes me to a dump of info.

I think Admin is broken - is this a bug or something wrong with my setup? I remember being able to go somewhere and clear our redis before, I'm guessing this was in Admin, but I can't remember what else was there.

Let me know if you want more info.

coverband 4.2.1

**Comment by danmayer** [comment]
<img width="1676" alt="Screen Shot 2019-09-30 at 8 47 48 AM" src="https://user-images.githubusercontent.com/24925/65889792-17ab2080-e35f-11e9-9f0b-1092e820ec5a.png">

clear should be in the header row see screenshot above ^^

You can also check it out on the demo site, https://coverband-demo.herokuapp.com/coverage?#_AllFiles

If you don't see it anymore, this is controlled by a config setting and is off by default as it is a destructive action. You can set it via `config.web_debug = true` see the example here: https://github.com/danmayer/coverband_demo/blob/master/config/coverband.rb#L22

**Comment by jjb** [comment]
Thank you for the quick and thorough response.

(instead of `web_debug`, i think you mean `web_enable_clear`)

I don't remember ever turning that on when experimenting in dev before, but it's possible.

> is off by default as it is a destructive action

Shouldn't the coverage report be reset when code changes, to reflect new usage patterns? if foo.rb doesn't change, and bar.rb stops calling a method in foo.rb, then the coverage report should reflect hat the method never gets called. but i'm guessing it will say it is getting called, until the cache expires?

So maybe a shorter default TTL (currently 1 month as per my recent PR) would be appropriate for the vast majority of apps that have a good amount of use? maybe 7 days?

**Comment by jjb** [comment]
okay I guess it's easily accessible here `#rtfm`

https://github.com/danmayer/coverband#clear-coverage

**Comment by danmayer** [comment]
oops yep `web_enable_clear` not `web_debug`

Every time code changes it will clear that file, but we allow manual clearing which can be helpful in a number of situations. Also, bey turning on `web_enable_clear` you can clear individual files which is very helpful after deploying a refactoring that might remove the callers to the target but not change the target.
