### ISSUE TITLE
Coverband running during all rake tasks

### ISSUE THREAD

**Issue by bhb** [danmayer/coverband#329]
Environment
* Coverband 4.2.3
* Rails 5.2.3
* Ruby 2.5.5.
 Repro:

1. `bundle exec rake db:version`

Expected: Rake should run without any issues
Actual: 

```
E, [2019-10-04T14:48:15.839750 #36041] ERROR -- : coverage failed to store
E, [2019-10-04T14:48:15.839814 #36041] ERROR -- : Coverband Error: #<Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)> Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
```

This worked without error in '4.2.0'. Is there some change I need to make to our configuration? Perhaps naively, I wouldn't think that coverband would need to check the connection for all rake tasks.

**Comment by danmayer** [comment]
hmm so we have gone a bit back and forth on tracking code run via rake. We try to track most code execution so I believe it is just trying to commit any coverage at the end of the rake task. If you don't have Redis available, it would error.

What has changed making this appear between 4.2.0 and 4.2.3, I am guessing it is related to the fix on the configuration running multiple times on bootup??? This has caused issues for some folks that relied on configuration running multiple times to pick up environment variables or settings that weren't originally available. When we fixed it so configuration only runs once one needs to ensure the environment is configured before Coverband tries to use it.

* fix configuration occurring multiple times: https://github.com/danmayer/coverband/pull/307
* other issues folks had related to the environment not set up before configure: https://github.com/danmayer/coverband/issues/320

We did in the past ignore some tasks like `asset:precompile` as that caused issues on heroku, but generally now we just let that try and fail... You can see skipped tasks and add to them here: https://github.com/danmayer/coverband/blob/master/lib/coverband/configuration.rb#L23

You can see in the past it used to ignore more tasks, https://github.com/danmayer/coverband/pull/275/files

I guess, in this case would you not expect Coverband to try to record data? Is there not a redis setup? Does coverband work in normal cases, but fail for rake?

**Comment by danmayer** [comment]
The other thought would be this was always previously erroring out but logger wasn't set so it never output anything... We changed setup on the logger a bit ago, on the branch before upgrading I am guessing if you add a debug line it will still be trying to run on the rake tasks. I don't normally set the logger to anything on production, but on dev I could see this output if my redis wasn't running or configured correctly.

https://github.com/danmayer/coverband/commit/822f18770228bdf7fffd8992e235285046370109#diff-1f4b05f150269d04438736256c27b0a8R51

**Comment by bhb** [comment]
@danmayer I can totally see the logic in trying to run consistently across all tasks instead of trying to carve out a bunch of exceptions.

The context here is that we run several `rake` tasks on CI (this isn't captured in my original report, since I was going for the simplest repro). I'm not 100% sure why the Redis process isn't up yet at the point this runs, but I can look into it.

Coverband seems to work fine locally, so I expect it's working in all normal cases, although I haven't had a chance to try this version in prod yet. 

If the answer is "this is expected", that's totally fine: I just wasn't sure what to expect since in older versions it worked fine (or, as you noted, maybe was silently failing, which looked like success to the outside observer).

Feel free to close this since it's not clear the behavior should be different.

**Comment by kbaum** [comment]
You could also try using the COVERBAND_DISABLE_AUTO_START env var when running the rake tasks.

https://github.com/danmayer/coverband/blob/master/README.md#manually-starting-coverband

**Comment by danmayer** [comment]
cool, yeah I will close the issue with we now do intend coverband to run on all Rake tasks. Two things

1. For any process, you don't care about as @kbaum said easy to just start it with `COVERBAND_DISABLE_AUTO_START=true bundle exec rake some_task_we_dont_want_to_track. This is the easiest way to avoid any output or startup costs for tasks you don't care about tracking.
2. If you are seeing this output occasionally on CI for the first tasks run in a job, you might want to look at race conditions after Redis starts... https://discuss.circleci.com/t/prevent-race-conditions-by-waiting-for-services-with-dockerize/11215 I have seen this issue for specs and other tasks that run quickly after the Redis docker is initialized. 

Thanks, for reporting the issue.

**Comment by gingerlime** [comment]
I also bumped into it (after upgrading from a previous version? not sure, sorry) in my docker builds... I understand why the disable flag shouldn't be the default, but still wonder if coverband should simply fail gracefully if redis isn't available?? Currently my build runs `asset:precompile` but this fails the entire rake task because there's no redis available...

I see coverband as a very useful, but completely optional tool, and therefore I would say it should try to fail as gracefully as possible without breaking anything else. Yes, it can be undesirable not to collect coverage info, but it's far less undesirable than failing everything else??

**Comment by gingerlime** [comment]
... I'm very unfamiliar with the codebase, so please forgive me if this is totally naive, but maybe wrap [this whole thing](https://github.com/danmayer/coverband/blob/d15bf4dda2fd296854ea7c08055642e369df2a1c/lib/coverband.rb#L103-L108) in a rescue clause and just print an error if it fails?

**Comment by kbaum** [comment]
@gingerlime I do like that idea and your points are valid. The only downside is that issues will be a little more difficult to trace down. Perhaps we specifically catch the error raised when redis isn't available to start?

**Comment by gingerlime** [comment]
as a side note: I really enjoy the discussions on this project, and you guys always present a very measured and thoughtful reasoning while still being open. Thanks so much for being so awesome!

**Comment by kbaum** [comment]
Hah! Thanks @gingerlime!

> I still wonder if failing safe is always a, erm, safer choice for a library like coverband 

I agree that failing safe is a good choice for a library like coverband that is not essential for running your application. That being said, i think startup is a bit different scenario than runtime. Startup is when the developer might benefit from loud feedback that coverband is not configured correctly. If an application completely does not startup because of coverband, it is unlikely that it will make it out to a production environment.

I do think that if redis is unavailable in production for whatever reason, it would be annoying if an application that has no other redis dependencies is unable to boot up. That's why i am landing on only trapping redis errors. It's also more of a baby step and I do like baby steps when i am unsure about something 😄 .

**Comment by danmayer** [comment]
Interesting about the `asset:precompile` issue @gingerlime as we did explicitly ignore that task in the past... Then we change how we handle startup a number of times and thought we didn't need to do that anymore. I haven't been hitting errors on `asset:precompile` with Heroku on the demo project. A couple things...

1. I agree we want to be loud at startup, but handle everything at runtime. That being said we could be loud with large warning messages, vs failing... Although this original ticket was about the logging as well. I think capturing the redis connection error is an OK starting point
2. I think we should perhaps go back to explicitly ignore some rake tasks like `asset:precompile` & `db:*` as DBs are frequently not available or setup during those tasks and they are more often running framework code not application code... We already have a hook to ignore tasks so we would just have to start adding in standard tasks folks have mentioned.

**Comment by gingerlime** [comment]
Sounds great :) 

1. Yes, a big fat warning felt more suitable to me personally. But understand your points completely and absolutely, redis is a likely failure point, and baby steps are usually better. Would be super-happy catching redis exceptions only.
2. I know it's very common in the ruby/rails/rack/sinatra/sidekiq world to do some runtime checks and apply some magic for the user to integrate seamlessly with common libraries and frameworks. It's definitely going to make adoption for users a breeze if coverband just knows what to do. For the sake of a few simple pre-flight checks, I guess it's worth it. It's obviously your call what makes most sense to you guys :)

Thanks again, and please let me know if there's anything I can help with.

**Comment by danmayer** [comment]
> as a side note: I really enjoy the discussions on this project, and you guys always present a very measured and thoughtful reasoning while still being open. Thanks so much for being so awesome!

by the way thanks for this. I really appreciate the comment. We have strived to make a friendly community around Coverband

**Comment by danmayer** [comment]
ok further improvements on how we handle this startup issue are in this PR take a look @bhb and @gingerlime  https://github.com/danmayer/coverband/pull/343

**Comment by gingerlime** [comment]
PR looks really good at a glance. I'll test it at the earliest opportunity (probably next week) and will let you know.

**Comment by danmayer** [comment]
cool @gingerlime I just released `4.2.4.rc.1` to make it easier test this, as I think we have enough small little fixes that we can roll out a release.

**Comment by gingerlime** [comment]
@danmayer I tested it on my dev box without redis and it now fails more gracefully 👍 I left a comment on the PR though, because I think there might be room for further improvement hopefully (particularly, really get coverband out of the way if it's excluded)

**Comment by danmayer** [comment]
cool responded back a bit, I get where you are coming from on making it even more out of the way... but I know one of the hardest things for new folks with Coverband is getting it up and running so I worry without some logging, warnings, and messing it could be confusing for first time users as well... Hoping this is a good enough start for now.

**Comment by gingerlime** [comment]
Yes, absolutely! Thank you @danmayer.

**Comment by danmayer** [comment]
I think we might still iterate on what exactly is in and out, but calling this one closed for now
