### ISSUE TITLE
file hash is null in datastore

### ISSUE THREAD

**Issue by danmayer** [danmayer/coverband#335]
This looks like an issue... seeing it on coverband_demo as well as on the primary production app I work on.

https://coverband-demo.herokuapp.com/coverage/debug_data

file_hash is only stored on the merged data, and it is null in all cases.

**Comment by danmayer** [comment]
Everything appears to be working fine, so I am wondering if this is just an issue with how we pull and display data for the debug_data, or something I am missing.

**Comment by kbaum** [comment]
So I see that merged_reports is inserting file_hash:

https://github.com/danmayer/coverband/blob/master/lib/coverband/adapters/base.rb#L121

But it is not being returned when hash_redis_store#coverage is called:

https://github.com/danmayer/coverband/blob/master/lib/coverband/adapters/hash_redis_store.rb#L112

We are only returning what is in META_DATA_KEYS constant:

https://github.com/danmayer/coverband/blob/master/lib/coverband/adapters/hash_redis_store.rb#L10

The file_hash is actually part of the key of each hash in redis that stores the data.

https://github.com/danmayer/coverband/blob/master/lib/coverband/adapters/hash_redis_store.rb#L64

I'm not sure this is a bug or not. Should we just not return this as part of the debug data?

**Comment by danmayer** [comment]
I think it would be helpful to have it in the debug data, given that is a good way to understand and debug issues seeing the md5_hashes would likely be a good thing, but given it is part of the key, not sure of the best way to support his for the new adapter...

**Comment by danmayer** [comment]
Thinking about this more, I do think we should find a way to include the md5_hashes, as it can really help debugging, and the tool I have been building to automatically do cleanup, should confirm matching md5s before modifying the file... So it would need the data as part of the download. My plan on the download was to just offer this debug data in a way that would prompt the user to save the file opposed t view it.

**Comment by kbaum** [comment]
Ok. I'll work on getting it back in there. It won't be difficult.
