### ISSUE TITLE
Requesting to run the coverband command without redis

### ISSUE THREAD

**Issue by k-jayaraman** [danmayer/coverband#336]
Hello @danmayer ,

Kindly let me know the command / way to execute the "coverband" command with out redis.

Do we really need redis in order to execute coverband command.

Thanks in advance.

**Comment by kbaum** [comment]
Hi. Right now coverband depends on redis for use in production. Is there some type of issue that prevents you from using redis?

**Comment by danmayer** [comment]
yes @k-jayaraman at the moment the production datastore is Redis. The file adapter is for local testing... It would be possible to write an adapter for an alternative data store and there has been interested here and there, but no one has ever really pushed for another storage option.

Please let us know your concerns with redis and what other kinds of storage you think would be a good option.

**Comment by danmayer** [comment]
closing this for now, with Coverband currently requires Redis.
