### ISSUE TITLE
Requesting Clarifications

### ISSUE THREAD

**Issue by k-jayaraman** [danmayer/coverband#339]
Hello @danmayer ,

Still am facing difficulty in understanding the coverband Installation . Exactly where should I put  the coverband gem in order to get the code coverage.

I would request the  detailed explanation.

Kindly provide the step by step guidance to get the code coverage.

**Comment by kbaum** [comment]
Hi. Can you have a run through the installation process on the readme and let us know what part is confusing?

https://github.com/danmayer/coverband#gem-installation
https://github.com/danmayer/coverband#coverage-report

thx.

**Comment by danmayer** [comment]
Also, see @k-jayaraman you can view the usage in coverband_demo which shows how to setup and configure Coverband. https://github.com/danmayer/coverband_demo
