### ISSUE TITLE
Reporting to redis at different times to avoid contention

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#341]
In deployments with numerous ruby processes, coverband may be reporting to redis from multiple projects at the same time. When the HashRedisStore is used this may cause contention on the redis instance since it is single threaded. Perhaps each coverband ruby instance should vary on reporting interval by a random number of seconds?

Might also be able to leverage a redis incr so that the reporting interval is not so random for each process.

**Comment by danmayer** [comment]
good, call. I can take this... On Memcache back in the day we always introduced a random wiggle to avoid this same issue. The peaks we see on our Redis CPU graphs are likely due to this issue...

**Comment by kbaum** [comment]
Yeah.. the only issue is it doesn't solve startup and shutdown as no matter what this will happen at the same time.

One idea i was thinking about is we could separate the redis.set of the data vs the lua processing. So on startup/shutdown, all of the nodes in the server could put all the data as this is pretty easy on the server Then we could handle the processing separately in another thread and that thread can have the wiggle.

Each call to lua will just read a set of data keys from a set and process the data corresponding to all of those keys.

**Comment by danmayer** [comment]
yeah, I guess I would add the easy wiggle to the runtime and check our graphs, if we don't see much improvement likely isn't work working on the startup / shutdown.

Honestly, since most shutdowns let each process & threads finish active requests there should be some built-in wiggle there. So startup would be the hardest one to solve... Have you seen issues on startup related to this?

**Comment by kbaum** [comment]
I actually haven't seen any issues related to this. Just thinking about ways to possibly reduce cpu utilization on redis instance when using HashRedisStore.

**Comment by danmayer** [comment]
We added support for two ways to help control this issue, but I forgot to ever update the issue and close it.

```
# reduce the CPU and Redis overhead, we don't need reporting every 30s
config.background_reporting_sleep_seconds = 300
# add a wiggle to avoid cache stampede this helps flatten out Redis CPU, if you are using the HashRedisStore especially, but helps with any Redis contention
config.reporting_wiggle = 60
```
