### ISSUE TITLE
Regarding Rails version

### ISSUE THREAD

**Issue by k-jayaraman** [danmayer/coverband#342]
Hello @danmayer ,

Our application was builtup with rails (3.2.22.13, 3.2.22.10) version . Can we use coverband 4.2.3 version for our application ?. 

Or should i go for older version of coverband which supported for rails (3.2.22.13, 3.2.22.10) version .

Thanks in advance for all your clarifications.

**Comment by kbaum** [comment]
So we don't run our automated tests against rails 3.x so I can't say for sure. Want to try adding it and let us know what errors you run into?

**Comment by danmayer** [comment]
We don't explicitly support Rails 3 anymore... I believe it would work, if anything doesn't it would be the Railtie which tries to automatically hook into the Rails loading process and call `Coverband.start`. If there were issues with that you could use `require: false` in your Gemfile and explicitly do the startup yourself.

That being said, I don't think we will try to make any additional changes to support Rails 3, we haven't put out official policy, but I would love to support only 2 major Rails versions.
