### ISSUE TITLE
Unable to configure the "safe_reload_files" in coverband

### ISSUE THREAD

**Issue by k-jayaraman** [danmayer/coverband#345]
Hello @danmayer ,

I'm unable to configure the "safe_reload_files" configuration in coverband.  Please find the following exception for your debugging.

config/coverband.rb:34:in `block in <top (required)>': undefined method `safe_reload_files=' for #<Coverband::Configuration:0x007f9e2d67f430> (NoMethodError)
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/coverband-4.2.3/lib/coverband.rb:50:in `configure'
	from /Users/karthicj/Projects/cloudpercept/config/coverband.rb:4:in `<top (required)>'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.13/lib/active_support/dependencies.rb:245:in `load'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.13/lib/active_support/dependencies.rb:245:in `block in load'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.13/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.13/lib/active_support/dependencies.rb:245:in `load'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/coverband-4.2.3/lib/coverband.rb:52:in `configure'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/coverband-4.2.3/lib/coverband.rb:104:in `<module:Coverband>'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/coverband-4.2.3/lib/coverband.rb:37:in `<top (required)>'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `require'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `each'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `block in require'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `each'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `require'
	from /Users/karthicj/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/bundler.rb:114:in `require'
	from /Users/karthicj/Projects/cloudpercept/config/application.rb:17:in `<top (required)>'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.13/lib/rails/commands.rb:53:in `require'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.13/lib/rails/commands.rb:53:in `block in <top (required)>'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.13/lib/rails/commands.rb:50:in `tap'
	from /Users/karthicj/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.13/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by danmayer** [comment]
What are you using that for @k-jayaraman perhaps we need to update some documentation? That feature no longer is needed or exists, so there shouldn't be any need for it. Could you explain what you are trying to achieve? We used to have that feature for files that were missed because we hadn't tapped into the Rails initialization process, but it was removed because we significantly changed how we hande the boot up.

**Comment by danmayer** [comment]
adding some labels to help if other folks find this page. I will wait to get a bit more info before closing.

**Comment by danmayer** [comment]
There was still documentation of that feature in the readme, I have removed the out of date documentation sorry about that if it was confusing @k-jayaraman 

Let me know the issue you are hitting and we should be able to sort it out.

**Comment by danmayer** [comment]
any additional info, @k-jayaraman

**Comment by danmayer** [comment]
ok closing this out as a deprecated feature
