### ISSUE TITLE
coverband setup & gem tracking

### ISSUE THREAD

**Issue by ruba-ruba** [danmayer/coverband#351]
Hi 

i'm trying to setup `coverband` at one of our projects 

so far everything but gem-tracking/gem-details works out of the box.

my config is next: 
- coverband is **not** explicitly required in `application.rb` or anywhere else
- listed below `rails` in Gemfile
- added `config/initializer/coverband.rb`
- mounted `/coverband` to app routes

config sample `config/initializers/coverband.rb`

```ruby
  Coverband.configure do |config|
    config.logger = Rails.logger

    config.verbose = !Rails.env.production?

    config.track_views = true

    config.track_gems = false
    config.gem_details = false

    # Files to ignore
    config.ignore += [ ... ] # list removed for better readibility
  end
```

**Isssue** is that regardless how track_gems / gem_details configs set i can see all gem files listed in coverband

![Screenshot 2019-10-29 at 17 34 07](https://user-images.githubusercontent.com/2625613/67789770-d3519400-fa74-11e9-9514-234592a954ca.png)

#### Question

How do i track only files in `app/*` directory ?

`config.ignore = [...]` could have been an answer but it feels wrong to explicitly ignore all gems if there is config for that.

**Comment by kbaum** [comment]
Thanks for reporting. I believe coverband ignores gems via the vendor directory:

https://github.com/danmayer/coverband/blob/master/lib/coverband/configuration.rb#L43

Not sure why the ones listed above are not being ignored. Would you mind pasting in some of the absolute paths to the gem files that are incorrectly being included within the report?

**Comment by danmayer** [comment]
hmm yeah a little more info would be helpful...

* What version of Coverband are you on?
* Could you give the app path and the path where the gems are on your deployment?
* Are you on heroku, or some sort of custom deployment?

I am guessing your gems are in some sort of non-standard location, and then we can sort it out either wiht the ignore, or we could update the gem to have some other standard directory to ignore.

**Comment by danmayer** [comment]
Are your gems stored in the system folders or your `app/vendor` directory?

**Comment by ruba-ruba** [comment]
Hi, thanks for help, issue seems to be solved now. 

We have dockerized environment and using kubernetes for deployments which is a but customized. 

The issue was that gems are stored not in `app/vendor` as i expected but in `app/gems` 
adding `gems/*` to the `config.ignore = [...]` works as expected.

**Comment by kbaum** [comment]
Thanks for following up. Perhaps we should add something to readme about ignoring gems if they are stored in a custom location?

Or even better could we ignore the gem paths by default?

**Comment by danmayer** [comment]
updated the readme, still like the idea of ignoring based on the actual gem locations which we can dynamically look up based on the bundler / gem meta data.
