### ISSUE TITLE
HashRedisStore report generation giving line count warnings

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#353]
```
Warning: coverage data from Coverage [49] exceeds line count in /Users/karlbaum/workspace/foo/app/workers/bar_worker.rb [45]
```

**Comment by danmayer** [comment]
did we ever figure this out, or see additional reproducible errors of this? @kbaum

**Comment by kbaum** [comment]
I’m not sure I remember writing this. I wish my past self was more thorough and wrote more detail on how and when this occurs. I say we close this out and see if it comes up again.

**Comment by danmayer** [comment]
sounds good closing it out
