### ISSUE TITLE
Is JRuby supported?

### ISSUE THREAD

**Issue by laasem** [danmayer/coverband#361]

**Comment by danmayer** [comment]
I haven't tested with any JRuby apps. I would love to know if it all works out of the box. If someone wants to test it on an app and report back that would be great, any interested in trying it out @laasem . We could add some testing around it going forward if we know it works and know there is interest in supporting JRuby.

I haven't used JRuby on any of my work or personal projects, so I am not super familiar with it.

**Comment by laasem** [comment]
We tried it on our JRuby app in a staging environment and for some reason it doesn't write coverage data to Redis even though it can connect to the Redis instance. We feel it might have something to do with concurrency in JRuby, as we would sometimes (not always) see a `ConcurrentModificationException` Java error when enabling verbose logging.

What's weird though is that it's able to track unused views, but not accurately.

**Comment by laasem** [comment]
Thanks for the fast reply! We tried it on our JRuby app in a staging environment and for some reason it doesn't write coverage data to Redis even though it can connect to the Redis instance. We feel it might have something to do with concurrency in JRuby, as we would sometimes (not always) see a `ConcurrentModificationException` Java error when enabling verbose logging.

What's weird though is that it's able to track unused views, but not accurately.

**Comment by danmayer** [comment]
OK, I guess I will update this issue to being a feature request. I will try to do some investigation and testing around running in JRuby. Sorry it doesn't work out of the box and thanks for testing it.

The view tracking and coverage tracking run on entirely different event sources, so it makes sense that one would work and the other might not. In terms of it not tracking views accurately, best guess along with the ConcurrentModificationException is that only some of the writes are getting through.

 This will likely take me a couple weeks to get to as I have a few other things in my pipeline.

**Comment by laasem** [comment]
That sounds awesome, thank you so much!

**Comment by Ahmed1Ossama13** [comment]
Any update on that?

**Comment by danmayer** [comment]
Sorry I haven't made any progress on JRuby yet... Anyone know of a quick test rails jRuby app, I could clone and get up and running to test things out?

**Comment by danmayer** [comment]
OK, so Jruby doesn't work out of the box... I am currently fixing some failing specs, getting CI to run with Jruby, and getting a branch of coverband_demo to run with JRuby, to get everything working...

It looks like this might not ever work without a performance impact... See

**Comment by danmayer** [comment]
OK, so Jruby doesn't work out of the box... I am currently fixing some failing specs, getting CI to run with Jruby, and getting a branch of coverband_demo to run with JRuby, to get everything working...

It looks like this might not ever work without a performance impact... See these JRuby issues for details

* https://github.com/jruby/jruby/issues/3096
* https://github.com/jruby/jruby/pull/5633

I seem to be able to get most things passing with the `--debug` or with a `.jrubyrc` setting `debug.fullTrace=true`. 

I still need to look at a few more things and get this hooked up to a full Rails app (coverband_demo) to verify.

**Comment by danmayer** [comment]
ok @laasem @Ahmed1Ossama13 the release `4.2.5.rc.2` works with JRuby, checkout the readme for instructions on the JRuby options needed to make it work. I haven't fully benchmarked this so you might want to run on staging or test on an internal system to see if it is performant enough for your needs.

**Comment by laasem** [comment]
Apologies for the super late response and thank you for this!

**Comment by thbar** [comment]
I am curious if anyone here actually ended up using this in production, and what the feedback was?

I have a JRuby production system that has been running for a fairly long time (15 years or so), and tracing dead code would help delete some extra code.

Thanks!

**Comment by danmayer** [comment]
@thbar I had it running for a good while on some example projects and code... I heard from a user who ran it in production for awhile without issues. I don't hear to often about JRuby usage so I can't say that I know anyone currently using it as it seems to come and go in terms of folks interest.
