### ISSUE TITLE
Never switches to runtime 

### ISSUE THREAD

**Issue by maxp-hover** [danmayer/coverband#362]
Hi, I see here https://github.com/danmayer/coverband/commit/ef36526e9588fce4e2f5e539afd6c1ad09da21f4#diff-b37c96a2e8df9a68fcf502aa11920406
that lines 8-10 were removed from railtie.rb

I spent a couple hours so far today debugging our Coverband setup - it was never switching from 'eager_load' to 'runtime' type and I figured out that if I revert the above change to railtie.rb it does work again.

Why were those lines removed? 

By the way, from my breakpoints I discovered that the `RailsEagerLoad#eager_load!` was called _after_ the whole `config.after_initialize` block. Is this abnormal?

Thanks, Max Pleaner @ Hover

**Comment by kbaum** [comment]
Thanks for reporting this. Here is some more context around why those lines were removed:

https://github.com/danmayer/coverband/pull/307

It looks like it's pretty mysterious what triggers eager load but we had assumed that it was done before after_initialize. We have some tests around this with rails 4 and rails 5 in the coverband repo. We should really had rails 6 to that. What version are you using?

**Comment by danmayer** [comment]
hmmm yeah we have had a bunch of issues related to autodetecting runtime... Sadly, it seems across versions of Rails and various plugins, some odd things can occur. I guess we could document an option to force it to switch, or to opt-out of the auto-detect. So the user could add the hooks in their own app.

If we had some option like `config.manual_trigger_runtime`, would that work for you? @maxp-hover 

Beyond rails version, could you share the server you are using, Ruby version... perhaps any config related to eager_load... etc?

**Comment by maxp-hover** [comment]
Hi @danmayer and @kbaum I really appreciate your prompt responsiveness! I think I may have figured out what's going on, a little more. Crucially, there is a place in our application's _routes file_ which is calling `ResqueWeb::Engine.eager_load!` - this appears to be the reason that `def eager_load!` is getting run after `config.after_initialize`. 

I have tested with `config.eager_load = true`, and all the builtin eager_load calls do get run before `after_initialize` (except for this one that we call manually). Seems like there are many of eager_load calls because many gems have rails engines - not sure that's really a problem. 

So, long of the short of it, I think the issue only exists if you call `eager_load` manually. 

I suppose that yes, if I manually change it back to runtime mode after that manual eager_load call, it would resolve the issue. In that case we would have to make a note in the Readme about it.

**Comment by danmayer** [comment]
Nice detective work... That is good to hear and to understand... so it would previously work because we allowed many calls to exists, then we removed them in #307 to reduce all the overhead, but now if there are any manual calls it will be in a bad state. 

Yeah, perhaps we can add some warning to our readme, but it does think that just having your own hook to set coverband to runtime is probably the best solution.

**Comment by kbaum** [comment]
I think updating the readme makes sense. 

Do you know why the manual call to `ResqueWeb::Engine.eager_load!` is needed here?

**Comment by maxp-hover** [comment]
@danmayer - My two cents - I think that making a public hook _and_ adding a note to the readme is the way to go. Say you make a hook - without the note in the readme, nobody will know that they need to call it :)

@kbaum - I do not. I did a git blame and contacted my colleague asking for some clarification on it.

**Comment by danmayer** [comment]
take a look at this comment @maxp-hover https://github.com/danmayer/coverband/commit/824b877bda885b225b4bb3cb54218625bbe19fdb see if that works for you and if you think it sufficiently addresses the issue

**Comment by maxp-hover** [comment]
@danmayer looks good! I guess the public method to switch to runtime already exists. Thanks for all your work.

**Comment by kbaum** [comment]
@danmayer Took a look at the addition to readme. I am wondering if that will fix the issue considering that the railtie already registers an `after_initialize` callback to set coverage type to runtime. Since @maxp-hover was calling `ResqueWeb::Engine.eager_load!` within the routes.rb file, I think the fix would involve ensuring that they switch back to runtime after `eager_load!` is called.

```ruby
Rails.application.routes.draw do
  ResqueWeb::Engine.eager_load!
  Coverband.report_coverage
  Coverband.runtime_coverage!
end
```

**Comment by danmayer** [comment]
cool, yeah I wasn't sure if all the methods were public, but the usage definitely wasn't documented, so it is good to have it in the readme.

Thanks

**Comment by danmayer** [comment]
I just saw @kbaum's comment, I think my solution might work, but given it is in the routes file after initialization @kbaum might be right... in which case, his solution is likely better... Could you give them a try @maxp-hover and let us know what works best for you and then I can modify the documentation if we need to.

**Comment by danmayer** [comment]
The other option would be moving that `ResqueWeb::Engine.eager_load!` out of the routes and into an initializer, which is probably where it should be.

**Comment by maxp-hover** [comment]
Hi @danmayer and @kbaum sorry for the delay, I was out of town for a few days. It is not necessary to use any additional `after_initialize` block, just calling `Coverband.runtime_coverage!` after the manual `eager_load` call works. But yes, I will be removing that unnecessary `eager_load` call altogether since it's not actually needed. 

Thank you guys so much for your help with this.

**Comment by danmayer** [comment]
thanks, I updated the docs to make that fix clear. closing this out.
