### ISSUE TITLE
Stack level too deep error when running certain activejob jobs

### ISSUE THREAD

**Issue by kejordan** [danmayer/coverband#367]
Hello again
We're using your work around for getting the assets for the S3 file, but now we're encountering `Stack level too deep` errors when running certain jobs.  Is there a way to keep the gem from running in our jobs layer, but keep it running in our rails layer? I'm not seeing a config option for that, but I may be missing it.

**Comment by kbaum** [comment]
You can disable auto start with an environment variable when starting your jobs:

https://github.com/danmayer/coverband#manually-starting-coverband

Curious why coverband would cause a stack level too deep error. Haven't come across this before. Would you be able to give us some more info? Perhaps the stack trace you are getting?

**Comment by kejordan** [comment]
We have a few jobs that run throughout the day, so we may not be able to turn coverband on and off intermittently.  We are using a back port of active job - do you know if you've had issues in the past? If not, we can keep digging on our end.

**Comment by kbaum** [comment]
> We have a few jobs that run throughout the day, so we may not be able to turn coverband on and off intermittently.

Was thinking you would disable coverband for the jobs process. I imagine your jobs run on a separate process from web server. In that case, you could just start it like:

```
COVERBAND_DISABLE_AUTO_START=true bundle exec rake jobs:start
```

We have not come across any stack level too deep errors. What job framework are you using besides active job? Active job is usually just an abstraction on top of something like sidekiq.

```

**Comment by danmayer** [comment]
yeah, the stack level too deep is confusing, my best thought on that is that coverband is somehow trying to do coverage on coverband... Other info about gem setup and `coverband.ignores` might be helpful. Like if you have your gems in `app/vendor` perhaps it is trying to do coverage on itse;f.

**Comment by danmayer** [comment]
are you still having this issue @kejordan if so do you have any more details, or did you end up just disabling for jobs? Looking to either help fix this issue, or close it out.

**Comment by hanslauwers** [comment]
I came across the same issue. Resque jobs were no longer executing due too stack level too deep errors. Thought I'd share my findings.

The problem was another gem ([airbrake](https://github.com/airbrake) in my case) was using alias to override the Resque::Job.perform method. The combination with Coverband overriding Resque::Job.perform method using module#prepend was causing a loop in method calls.
I resolved it by temporarily installing an older version of the airbrake gem (older than 9.6).

Code snippets relevant to my case:
[airbrake](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/resque.rb#L40)
[coverband](https://github.com/danmayer/coverband/blob/master/lib/coverband/integrations/resque.rb#L25)

Hope this helps.

**Comment by danmayer** [comment]
awesome this is really helpful @hanslauwers... I should be able to resolve the same way `rack-mini-profiler` handles multiple libs patching the same thing... I had never had enough details to understand the issue... 

https://github.com/MiniProfiler/rack-mini-profiler#nethttp-stack-level-too-deep-errors

I think I can finally fix this once and for all, thanks so much!

**Comment by hanslauwers** [comment]
Cool! That's a very nice way of resolving it. Happy the info helped.
Looking forward to the fix so I can get back to the latest version of airbrake.
Let me know if there's any other info you need.

**Comment by danmayer** [comment]
take a look at this @hanslauwers I haven't tested yet, if you hold off I should be able to test over the weekend

https://github.com/danmayer/coverband/pull/383

**Comment by danmayer** [comment]
@kejordan @hanslauwers this was fixed and is in the 4.2.7 release

**Comment by danmayer** [comment]
I have tested this on a resque production app and it works as expected

**Comment by hanslauwers** [comment]
Nice @danmayer . Thanks!

**Comment by danmayer** [comment]
just wanted to note, I thought this was interesting enough that I turned it into a blog post https://www.mayerdan.com/ruby/2020/07/15/ruby-gems-patching-std-lib
