### ISSUE TITLE
Web reporter should not require trailing slash in URI

### ISSUE THREAD

**Issue by TSMMark** [danmayer/coverband#370]
When visiting the mounted coverband report rack web app in browser:

`/coverband/` loads properly but `/coverband` does not. I thought I mounted the app incorrectly but after digging thru the source a little I found this regex

Looks like this regex requires trailing slash

https://github.com/danmayer/coverband/blob/8cd08418782b901815f41ca0e34eca553c87fc5a/lib/coverband/reporters/web.rb#L65

Ideally it would not 404 on `/coverband`

**Comment by danmayer** [comment]
this was just fixed. https://github.com/danmayer/coverband/pull/369

so you can install 4.2.5.rc.1 to pick up the fix, I will get a full release out sometime soon. thanks for reaching out @TSMMark

**Comment by TSMMark** [comment]
Awesome thanks! Closing
