### ISSUE TITLE
Ignore patterns too aggressive

### ISSUE THREAD

**Issue by thijsnado** [danmayer/coverband#382]
One of the files in our application is being ignored because it ends in `schema.rb`. I understand ignoring `db/schema.rb` but it is ignoring `app/graphql/graphql_schema.rb` which has code we would like covered.

**Comment by danmayer** [comment]
good call, I can fix this in the next day or two and cut a release on the 4.x branch and it will get pulled into the 5.x stuff as well.

**Comment by danmayer** [comment]
I fixed this but want to bundle with one other fix that I need to test over the weekend, I should have a release for you by Monday @thijsnado

**Comment by danmayer** [comment]
this was fixed and is in the 4.2.7 release thanks again @thijsnado
