### ISSUE TITLE
File that isn't loaded shows 100% load and runtime coverage

### ISSUE THREAD

**Issue by yesthesoup** [danmayer/coverband#385]
Not sure why this service is not showing as loaded, but when a file isn't loaded, I don't think it should count as 100% coverage.

![image](https://user-images.githubusercontent.com/2483953/87602077-5890dd80-c6c4-11ea-8dae-1714dc14724d.png)

**Comment by danmayer** [comment]
OK, cool thanks @yesthesoup guessing we recently broke this, we had changed a few things related to how we deal with unloaded files / missing data. I should be able to sort this out. 

Does the file have lines inside it that are Ruby... IE this isn't comment only file or some other odd edge case? Like a file that is empty?

**Comment by yesthesoup** [comment]
Thanks for the quick reply @danmayer. Yes, it's not empty and has only ruby code inside the service.

**Comment by danmayer** [comment]
OK, interesting... I do think for a totally empty file, perhaps we should give some sort of better treatment like `N/A` or just a '-' I will think about it... Thanks for all the info.

**Comment by danmayer** [comment]
OK, I believe this shows better in the 5.0 release closing this one out thanks again
