### ISSUE TITLE
Intended behaviour when Redis is unavailable

### ISSUE THREAD

**Issue by tjvc** [danmayer/coverband#389]
Hi there. Thanks for your work on Coverband!

I'm having trouble understanding the intended behaviour of the gem when Redis is unavailable at boot time. I can see that the gem rescues from a `Redis::CannotConnectError` in `lib/coverband.rb` and `lib/coverband/utils/railtie.rb`, but as far as I can tell these blocks are never hit. Instead, I see the following lines printed in the logs, I think when Coverband attempts to report coverage after initialisation and at intervals when background reporting is enabled:

```
E, [2020-08-12T12:28:51.920605 #338590] ERROR -- : coverage failed to store
E, [2020-08-12T12:28:51.920646 #338590] ERROR -- : Coverband Error: #<Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)> Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
```

I know that I can use `ENV['COVERBAND_DISABLE_AUTO_START']` to manually disable Coverband when Redis is unavailable, so I have a working solution, but it would be good to understand better how the gem is intended to function in this situation. I did look in the docs, but apologies if I've missed an explanation somewhere!

**Comment by danmayer** [comment]
@tjvc good question, basically if we can't connect at startup we try not to have everything starting in the background and such, but it might get loaded or at the very least it will try two attempts one after eager loading is complete and one at application exit. In those cases it should log the error lines.

If you don't want the error lines I think you can do a number of things:

* as you mentioned `ENV['COVERBAND_DISABLE_AUTO_START']=true`
* you can not load coverband in some environment if you aren't expecting to use it (for example in test, I don't recommend coverband yet), often folks don't have everything running for various build tasks in CI which can output the error... 
* you can likely just set a null logger or not set logger, and ensure that the `config.verbose = false`

Let me know if this all helps... If you have some other way you wish this was handled or to have further control let me know @tjvc

**Comment by tjvc** [comment]
Hi @danmayer. Thanks for getting back to me, and apologies for the slow response. Your suggestions were very helpful, so thanks for those.

I think my initial expectation was that if Redis was unavailable at boot, background reporting would not be started. In Rails at least, it doesn't look like that's the case, because the background middleware is always added and the reporting started on the first request (if I'm reading the code correctly...). Thinking about it some more, though, I'm not sure my expectation is a good one: I can envisage situations where Redis might be temporarily unavailable at boot but where you would want to start background reporting on the assumption that it might be reachable later. That seems like a more resilient approach.

I'm interested in your thoughts on this anyway, but happy for you to close this issue if you're content with the current behaviour. Thanks again! :slightly_smiling_face:

**Comment by danmayer** [comment]
yeah, I have seen some cases where trying again later is good specific examples when someone runs a build task in the deployment pipeline with production ENV but doesn't have redis available (building assets, autogenerating api-clients from schemas, etc)... So I think I will keep the approach, but thanks for reaching out and hopefully this issue will help anyone else that might be also confused on why things work this way.
