### ISSUE TITLE
CoverbandAdmin link

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#393]
![image](https://user-images.githubusercontent.com/96786/91656735-fda32200-ea88-11ea-859f-b27f1d9d3227.png)

It's seems like the purpose of the "Coverband Admin" link is to link back to the index listing of files after hitting the "info" link

I don't think it has much to do with administering coverband though. Perhaps we just rename this "Home"?

Also might consider renaming "info" to "Configuration" as it seems to be just spitting out the configuration?

**Comment by danmayer** [comment]
sure I can update these before release

**Comment by danmayer** [comment]
fixed on master
