### ISSUE TITLE
Feasibility: How much memory does coverband require?

### ISSUE THREAD

**Issue by alexspark** [danmayer/coverband#397]
I want to use coverband, but I don't have granular control over our redis instance, or at least, I'll have to go through ticket gymnastics to setup environment variables and redis provisioning. How much memory would you recommend for a medium size rails app? When I run rake routes, I end up with ~600 routes. Will running coverband locally give me an good sense of what to expect in production?

**Comment by danmayer** [comment]
So overall the memory usage can be thought of two ways... 

* redis memory (this should be very low usage) just a few MB of redis memory will be used
* increased memory usage for your app... This is harder to predict and calculate. I don't think development mode gives a great view into this, but I think we have seen memory usage go up around 30mb for fairly normal heroku setups and deployments.

There is another option in Alpha which doesn't require redis and posts to a service, if you are interested in being an alpha user of that let me know and we can email about it and share more details.

**Comment by danmayer** [comment]
oh to be more specific in terms of redis provisioning I have run it on very small redis clusters even the smallest offered by amazon is generally enough memory if it is a dedicated redis.

**Comment by danmayer** [comment]
any other questions or specifics @alexspark? or should I close this out

**Comment by alexspark** [comment]
You can close. Thanks for the insight. I still don't have a redis instance to try this out in, but can't wait to give it a spin. Would you welcome a PR for the README with a note about this memory usage?

**Comment by danmayer** [comment]
yeah feel free to send a PR @alexspark
