### ISSUE TITLE
Coverage data seems a little wonky

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#398]
We're looking at a file that we _know_ has some unused methods in it, but Coverband is saying that it has 100% runtime coverage. Confusingly Coverband _also_ indicates that 17 lines in the file are not covered.

<img width="549" alt="CleanShot 2020-09-17 at 09 23 13@2x" src="https://user-images.githubusercontent.com/58702/93485752-05f0bf00-f8c9-11ea-82ca-7a6909634ee2.png">

Scrolling down that same file there's some confusing data about some method coverage. For instance this method is showing that one of the inner most lines has run more times than the outer lines.

<img width="1010" alt="CleanShot 2020-09-17 at 09 35 47@2x" src="https://user-images.githubusercontent.com/58702/93486276-9f1fd580-f8c9-11ea-91ee-d636c40a7e58.png">

I don't know if it's related but the "coverage first seen data" seems off, or at least reports in an unexpected way. I ran `rake coverband:clear` yesterday, but Coverband is still reporting that it first saw coverage data for this file almost a month ago.

We're on `4.2.7` and our initializer looks like this:

```ruby
coverband_redis_url = ENV.fetch('COVERBAND_REDIS_URL')
Coverband.configure do |config|
  config.store = Coverband::Adapters::RedisStore.new(Redis.new(url: coverband_redis_url))
  config.track_gems = false

  # Experimental view tracking
  config.track_views = true
end
```

**Comment by danmayer** [comment]
hmm OK so this is very odd...

Given another recent bug I found where Coverband was connecting to a different redis than I expected and that you ran a clear and see data that predates the clear I am wondering if you are connected to two different redis's.

This was documented and fixed here: https://github.com/danmayer/coverband/commit/08726b583181767717c6c3580848b7efdc90bf8b

I have a branch where I am adding a bunch of tests around this, but no other changes to the code were made. I have that version running in production 5.1

I am thinking it might be worth upgrading to 5.1 and doing a coverband clear again. If you see any data right after the clear something is clearly up related to connecting to the data stores...

If you wanted to investigate further vs upgrading, I would try to add in some info or logs about what data stores you are connected to for collection and for reporting...

**Comment by jagthedrummer** [comment]
We do have multiple redis instances in play, so that seems like a reasonably likely candidate.

**Comment by jagthedrummer** [comment]
@danmayer Looking into upgrading and I don't find a `5.1` release or branch. `5.0.1` maybe? (Just want to be sure I'm not missing something and am upgrading to the right version.)

**Comment by danmayer** [comment]
hmm it is here on Rubygems, where you looking somewhere else?

https://rubygems.org/gems/coverband/versions/5.0.1

**Comment by danmayer** [comment]
ahh I never tagged it on github or added the notes on the releases tab...

https://github.com/danmayer/coverband/releases/tag/v5.0.1

updated that, let me know if there was anywhere else you were looking

**Comment by danmayer** [comment]
Did you test or figure things out with 5.0.1 @jagthedrummer ?

**Comment by jagthedrummer** [comment]
Sill waiting for the update PR to make it through release processes. Hopefully this week.

**Comment by jagthedrummer** [comment]
Hey @danmayer sorry for the delay. We finally got `5.0.1` into production and our initial tests suggest that this problem is resolved. I'll let you know if we end up discovering otherwise, and I'll close this issue in the mean time.

Thanks again for all your work on this gem. It's one of our primary tools that allows us to feel confident about removing code.

**Comment by danmayer** [comment]
great to hear @jagthedrummer glad things match expectations again.

Also, if you or your company ever has interest we currently have coverband as a service in Alpha testing, it has all the same features and then some new things along with support. y'all would definitely be an ideal group at giving feedback so if you are interested reach out to me via email and we can get it setup. It is pretty easy to switch to/from open source to the service.
