### ISSUE TITLE
View tracking is missing some views

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#399]
We have a handful of view files that aren't showing up in either the used or unused lists. One such file lives at `app/views/backpack/affiliate_commissions/new.html.haml`. My first suspicion was that it's being missed because it doesn't have an `erb` extension anywhere, but there are other similarly named files in the same directory that do appear in the lists. For instance `app/views/backpack/affiliate_commissions/edit.html.haml ` does show up in the "used views" list. (For the record we susptec that `new.html.haml` is not used and should be in the "unused views" list.)

**Comment by danmayer** [comment]
yeah, I have fixed this sort of thing by creating one off dynamic view trackers... but the default one is still pretty hard coded for ERB

https://github.com/danmayer/coverband/blob/master/lib/coverband/collectors/view_tracker.rb#L17

I would be interested in making this more flexible out of the box. I think I would just need to add a list of other common template lib extensions `haml`, `slim`, `etc`

**Comment by markshawtoronto** [comment]
Same problem for me, in my case also `*.html.haml` 👍

**Comment by danmayer** [comment]
ok folks, check out this PR, it should resolve the issue and explain how one could fix in apps if they want to do custom configuration

https://github.com/danmayer/coverband/pull/401

I will work to get a 5.0.2 release with this in it in a couple of days once I get some feedback

**Comment by danmayer** [comment]
release in a day or two sorry for the delay

**Comment by danmayer** [comment]
fixed in release 5.0.2
