### ISSUE TITLE
Coverage not working in production

### ISSUE THREAD

**Issue by mrbongiolo** [danmayer/coverband#404]
Hi, I've added the gem to our project's Gemfile and enabled the WEB UI. It seems to be working on development env, but in production it just collects this data: https://i.imgur.com/YLmFDFo.png

Everything else shows as 0%, not sure what is happening. I've tried manually starting Coverband inside an `after_initialize` hook but it doesn't make any difference.

Coverband: v5.0.1
Ruby: v2.6.3
Rails: v5.2.3

Production deployed to Heroku

**Comment by danmayer** [comment]
Hmmm In develop you see runtime coverage, but in production you are just getting load time on a few files but no additional data after that?

Do you happen to use scoutapp? They have a bug which breaks coverage: https://github.com/scoutapp/scout_apm_ruby/issues/343

You could try turning on verbose logging in production briefly to see if any of the logged output is helpful.

**Comment by mrbongiolo** [comment]
@danmayer thanks for the quick answer. Yes we use Scout and disabling `auto instruments` fixed the issue.

**Comment by mrbongiolo** [comment]
Should I create a PR with something like "Known Issues" sections to the README pointing out that it won't work when Scout APM has `auto_instruments: true`?

**Comment by danmayer** [comment]
yeah that would be great, if you want to send a PR please do, if not I will work on adding that section

**Comment by danmayer** [comment]
noting this was finally fixed in more recent versions of Ruby https://github.com/danmayer/coverband/commit/88c72ea887ec324a0c9b00552a920c6235cde301
