### ISSUE TITLE
undefined method `get_header' for Rack::Request

### ISSUE THREAD

**Issue by kadru** [danmayer/coverband#407]
Hi,

I get that `undefined method 'get_header' for #<Rack::Request:0x000055d27ca26940>` when I set `ENV["COVERBAND_PASSWORD"]` and mount the application on my `routes.rb`

I'm using  coverband 5.0.2, rails 4.2.11 and rack 1.6.13. I suppose the method `get_header` was added on rack 2.0, but I'm unable to update rack on my app at the moment.
 
I report the issue because could help other people who stump with this.

**Comment by danmayer** [comment]
OK, @kadru thanks. Is there an equivalent for rack 1.6.x? If so I am happy to detect and support older methods... If not I guess we could just document how to add passwords and protection other ways beyond `COVERBAND_PASSWORD`. For most apps, I actually end up just using routes and tapping into devise and admin checks. 

Here is an example of that, but I don't know if it works back to Rails 4.2

https://github.com/coverband-service/coverband_demo/blob/master/config/routes.rb#L2

**Comment by kadru** [comment]
I could not use devise so  I solve the problem glueing `Rack::Auth::Basic` with `Coverband::Reporters::Web.new` using ` Rack::Builder.new` and then mouting the resulting application on the desired route.

> Is there an equivalent for rack 1.6.x?

Yes, `Rack::Auth::Basic` is reading from the header  directly from `@env`, check the implementation of [#provided?](https://github.com/rack/rack/blob/1.6.13/lib/rack/auth/basic.rb#L18)

**Comment by danmayer** [comment]
ok now detects if that method is supported and uses old style when not, fixed in the latest release thanks @kadru 

https://github.com/danmayer/coverband/releases/tag/v5.0.3
