### ISSUE TITLE
Only config/coverband.rb being monitored in production

### ISSUE THREAD

**Issue by guicattani** [danmayer/coverband#408]
Hi Dan, I absolutely adore this gem and I'd like to use it in another project I am working on, but I'm facing a weird issue only in production (deploying to Heroku, locally it works fine) where Coverband only checks `config/coverband.rb` and the rest is ignored. Not sure if this is the right place to ask, but I don't know what I can do, I've switched Redis and followed every recommendation I found on the Readme.
I'm running Rails 6 and Ruby 2.6.5. Any help is appreciated.
Thank you so much, and great job on the gem!

**Comment by danmayer** [comment]
If you could post your coverband config, coverband version and if it is using standard gem require info... Along with if you have eager loading `preload_app!` that would help. I assume you are deploying with Puma but let me know if you have a different server.

**Comment by guicattani** [comment]
Sure, it's quite simple
`Coverband.configure do |config|
  config.logger = Rails.logger
  config.verbose = false
end`

Some info:
- I am using Puma and the latest Coverband (5.0.3)
- The project is monolith, front and back in the same Rails app

What I tried:

- Setting a dedicated Redis for Coverband
- Setting `after_initialize` runtime coverage in `application.rb` 

Three things I noticed:

1. Changing `./config/coverband.rb` to display the clear button is not working, even after I deploy and restart the dynos. 
2. Rake::Tasks['coverband:clear'].invoke does not work (I loaded Rake tasks prior, with `Rails.application.load_tasks`, still no avail). I'm not sure if that is connected to the issue.
3. The only code that shows up as covered are the ones I ran in the console. i.e. when I ran `Rails.application.load_tasks`, the project's Rake tasks file popped up as covered.

Thank you for the quick response!

**Comment by danmayer** [comment]
I assume you have your `coverband.rb` in `config/coverband.rb` vs an initializer, correct?

> Setting a dedicated Redis for Coverband

Did you do this via ENV vars, if so which, or did you change your coverband config?

> Setting after_initialize runtime coverage in application.rb
What / where were you doing this?

> 1. Changing ./config/coverband.rb to display the clear button is not working, even after I deploy and restart the dynos.

This makes me think that the Coveband isn't initializing correctly and failing, but it does sound like you can view the admin web UI?

Do you use ScoutApp? It causes issues with Coverage in general: https://github.com/danmayer/coverband/issues/404

**Comment by guicattani** [comment]
Yes `coverband.rb` is correctly set up

![image](https://user-images.githubusercontent.com/13826108/101673058-68bfa580-3a35-11eb-8464-5e516488a067.png)
(just these two are 100%, the rest is pretty much 0%, except for the Rake tasks, as I mentioned earlier)

> Did you do this via ENV vars, if so which, or did you change your coverband config?
I tried both `ENV['COVERBAND_REDIS_URL']` as well as setting it as ` ENV['REDIS_URL'] `, but didn't change it in the coverband config file. When I changed the Redis server it correctly reset the covered files, so I think Redis is ok.

> What / where were you doing this?
I followed your instructions as explained here [Fixing Coverage Only Shows Loading Hits](https://github.com/danmayer/coverband#fixing-coverage-only-shows-loading-hits), because this codebase I started working on has some legacy code, and I didn't know if `eager_load!` was being called somewhere in it.

> This makes me think that the Coveband isn't initializing correctly and failing, but it does sound like you can view the admin web UI?
Yes, the web UI works.

> Do you use ScoutApp? It causes issues with Coverage in general: #404
The closest I am using to ScoutApp is NewRelic, but I got Coverband working ok with it in another project that has NewRelic too. So, unfortunately, no.

**Comment by guicattani** [comment]
Hi Dan! I finally found a workaround: deleting the env var `COVERBAND_DISABLE_AUTO_START`.

I thought it should be either `false` or `true`, but I went through how it was actually called and it expects a bool, not a string. I don't know if that's how you intended it to be, but in `lib/coverband.rb:102` you wrote: 

```
unless ENV["COVERBAND_DISABLE_AUTO_START"]
```

but env vars are actually evaluated as strings. 

With Coverband starting as early as possible the problem was gone, so I guess something was messing with it later on.

Thank you for your quick replies, I really appreciated it.

**Comment by danmayer** [comment]
OK wow thanks @guicattani that is some great bug reporting and debugging work on your end, I am really glad you figured it out... I was trying to think of other ways I could help remote debug... I should update our docs to make the usage of `COVERBAND_DISABLE_AUTO_START` more clear, saying any value... or I could make it check for a specific value like true, but that might be more of a breaking change as I don't know what all values folks are setting out in the wild.

**Comment by kbaum** [comment]
> or I could make it check for a specific value like true

This issue comes up on almost all projects in my experience. My preference is that environment variables follow the rules of ruby truthiness which says that if a string or an env variable value is present, it's true. I find that it's a simple rule for everyone on the team to wrap their heads around. 

That being said, this is just my preference and many people disagree with it 😄 .

**Comment by danmayer** [comment]
OK, I updated the docs to make the intended usage more clear, so I didn't change any behavior just the docs

https://github.com/danmayer/coverband/commit/b5d631982f2a6e307d3f021252d59c894354d8ff

**Comment by guicattani** [comment]
Thank you @danmayer! :smile:
