### ISSUE TITLE
Same instance variable used to store service_dev_mode & service_test_mode

### ISSUE THREAD

**Issue by paulgoetze** [danmayer/coverband#414]
When reading through the configure.rb code I found that both the `#service_dev_mode` & `#service_test_mode` methods use the same instance variable `@service_dev_mode`. 

https://github.com/danmayer/coverband/blob/d4f9c6a3ad353c16e53ed4bb1a38859d879b28fe/lib/coverband/configuration.rb#L233

Is this done on purpose or should it use `@service_test_mode` to be in sync with the attr_writer from above?

**Comment by danmayer** [comment]
I guess it could be in this case it doesn't matter too much it is basically an internal mode for local developers or running in tests. It isn't something I would expect folks outside of those developing on Coverband to need to interact with very much

**Comment by paulgoetze** [comment]
Alright, then never mind :) I just thought setting a `service_test_mode` without any effect might be slightly confusing.

**Comment by kbaum** [comment]
Ok closing for now then.
