### ISSUE TITLE
doesn't work in gitlab-rails,and report a NoMethodError error

### ISSUE THREAD

**Issue by jmp0x7c00** [danmayer/coverband#419]
==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/coverage" for 202.120.224.53 at 2021-05-02 00:05:09 +0800
  
NoMethodError (undefined method `instance_observe_duration' for nil:NilClass):
  
lib/gitlab/instrumentation/redis_interceptor.rb:23:in `ensure in call'
lib/gitlab/instrumentation/redis_interceptor.rb:30:in `call'
lib/gitlab/metrics/elasticsearch_rack_middleware.rb:16:in `call'
lib/gitlab/middleware/rails_queue_duration.rb:33:in `call'
lib/gitlab/metrics/rack_middleware.rb:16:in `block in call'
lib/gitlab/metrics/transaction.rb:56:in `run'
lib/gitlab/metrics/rack_middleware.rb:16:in `call'
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/jira/middleware.rb:19:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:21:in `call'
lib/gitlab/middleware/multipart.rb:172:in `call'
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:21:in `call'
config/initializers/fix_local_cache_middleware.rb:11:in `call'
lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:21:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:76:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'

==> /var/log/gitlab/puma/puma_stdout.log <==
E, [2021-05-02T00:09:48.287088 #128905] ERROR -- : coverage failed to store
E, [2021-05-02T00:09:48.289556 #128905] ERROR -- : Coverband Error: #<NoMethodError: undefined method `instance_observe_duration' for nil:NilClass> undefined method `instance_observe_duration' for nil:NilClass
E, [2021-05-02T00:09:48.289718 #128905] ERROR -- : Coverband: view_tracker failed to store, error NoMethodError

**Comment by czcq** [comment]
Gem file:
source 'https://rubygems.org'
**gem 'coverband', path: "/var/lib/gems/2.7.0/gems/coverband-5.1.0/", require: false**
...


mount point:
 mount Coverband::Reporters::Web.new, at: '/coverage'
# frozen_string_literal: true
  
require 'sidekiq/web'
require 'sidekiq/cron/web'
require 'product_analytics/collector_app'

Rails.application.routes.draw do

        **mount Coverband::Reporters::Web.new, at: '/coverage'**

  concern :access_requestable do
    post :request_access, on: :collection
    post :approve_access_request, on: :member
  end

  concern :awardable do
    post :toggle_award_emoji, on: :member
  end

  favicon_redirect = redirect do |_params, _request|
    ActionController::Base.helpers.asset_url(Gitlab::Favicon.main)
  end
  get 'favicon.png', to: favicon_redirect
  get 'favicon.ico', to: favicon_redirect

**Comment by czcq** [comment]
help me,please

**Comment by danmayer** [comment]
Are you using Redis anywhere else in your app... This looks like a redis configuration or incompatibility with the instrumentation library. This isn't Coverband code in the call stack, just that it bubbles up when Coverband is trying to call Redis.

I don't think this is something in the coverband code base as we no where have code calling a method like `instance_observe_duration` which looks like some issue with the instrumentation around the redis call.

Sorry @czcq I don't think there is much I can do to help or debug this issue since I believe it is not related to this code base.

**Comment by czcq** [comment]
Yes, this app and coverband are currently using the same redis. When I do not configure the coverband, it will not report this error. After the configuration and then visit the /coverage page, it will report an error, which is very wired. Do you suggest to separate here, use one for app and another for coverband?

**Comment by czcq** [comment]
> Are you using Redis anywhere else in your app... This looks like a redis configuration or incompatibility with the instrumentation library. This isn't Coverband code in the call stack, just that it bubbles up when Coverband is trying to call Redis.
> 
> I don't think this is something in the coverband code base as we no where have code calling a method like `instance_observe_duration` which looks like some issue with the instrumentation around the redis call.
> 
> Sorry @czcq I don't think there is much I can do to help or debug this issue since I believe it is not related to this code base.

Yes, this app and coverband are currently using the same redis. When I do not configure the coverband, it will not report this error. After the configuration and then visit the /coverage page, it will report an error, which is very wired. Do you suggest to separate here, use one for app and another for coverband?

**Comment by kbaum** [comment]
Try using a different redis instance. Also might be good to try without `lib/gitlab/instrumentation/redis_interceptor.rb`.

My guess would be that coverband is calling redis before the `redis_interceptor` has been properly initialized.

**Comment by harshanails** [comment]
> Try using a different redis instance. Also might be good to try without `lib/gitlab/instrumentation/redis_interceptor.rb`.
> 
> My guess would be that coverband is calling redis before the `redis_interceptor` has been properly initialized.

I am using a different redis instance for coverband and yet this occurs with Gitlab rails. What do you mean by try without `lib/gitlab/instrumentation/redis_interceptor.rb`?  I put it in the ignore config but still this error occurs.

**Comment by chluo911** [comment]
> Referenc

Hi, have you solved this?

**Comment by chluo911** [comment]
> any further info on this issue? If not thinking I will close it out

Hi, have you solved this problem?

**Comment by harshanails** [comment]
> > any further info on this issue? If not thinking I will close it out
> 
> Hi, have you solved this problem?

No, this issue still exists with Gitlab rails.
