### ISSUE TITLE
Sharing coverage report to the rest of the team

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#42]
I've noticed that actually generating and sharing the coverage report to the rest of the team can be a bit awkward.  Code coverage data is stored within our production redis.  In order to generate the report, i have to copy that data to my local redis instance.  Then i run the `coverband:coverage` task locally.  This is a bit confusing as the path to the files on my local instance is different than in production.  It seems to work but looking at the code, i think this may not work for others depending on their coverband settings.  

Once i have the coverband report locally generated, now i have to figure out how to share it.  The actual coverage data is quite sensitive data given that it has the details of our codebase.  

I am not sure of the exact solution to the problem, but i think it would be neat if we could generate and expose the report within production.  Since we are on Heroku, we cannot generate it to the local file system.  We could generate and store on s3 or another remote file system.

Curious if others have noticed this issue.

thx!

**Comment by danmayer** [comment]
So an approach similar to sidekiq web, flipper-ui, or others could work. Where we make a mountable tiny web frontend. Often just a single endpoint mountable Sintra works. I think in our case we would just have to allow the report to be generated in that front end and perhaps write the html report to redis or load the html templates that generate the report and pull them on the fly. 

https://github.com/jnunemaker/flipper/blob/master/lib/flipper/ui.rb

A thought at least

**Comment by kbaum** [comment]
@danmayer - i think we use the exact same internal tools.  Love flipper! :wink: 

I am thinking the same thing.  The problem is that the report generation tends to take a while.  We could pre-generate it with a rake task and then store it in redis like you said.

**Comment by kbaum** [comment]
@danmayer - spiked on this:

https://github.com/danmayer/coverband/compare/write_output_to_s3?w=0

Basically writes the coverage report to s3.  We could then create a little sinatra app that reads from that bucket and displays the results.

**Comment by danmayer** [comment]
nice +1
