### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by czcq** [danmayer/coverband#421]
This is a simple project.
how to reproduce:
0.rails new simpleProject
1.add coverband to gemfile
2.bundle install
3.bundle exec rake coverband:coverage_server 
4.**LoadError: cannot load such file -- coverband/version**
![image](https://user-images.githubusercontent.com/16433413/118464580-9a027700-b733-11eb-9079-989aedf8f264.png)

**Comment by kbaum** [comment]
Hi. Just tried these steps and coverband server started cleanly.

Using 
coverband 5.1.1
rails 6.1.4

**Comment by kbaum** [comment]
Going to close this for now. Please reopen if you are still having issues.
