### ISSUE TITLE
View tracker resets when deploying with capistrano

### ISSUE THREAD

**Issue by stoivo** [danmayer/coverband#426]
**Describe the bug**
I wanted to use the view tracker in production to see if there are some views which are never used. We deploy with capistrano so each deployment goes into a new directory. It seam like the trick view tracker. If you look at the screeenshot below can see that `app/views/bank_statements/index.html.erb` is listed as unused view, but the view is listed in the used views as well but will the full path with the for the release.

We could resolve this with defining multiple root directories. Is this the propper fix of you you have a nouther suggestion?

**To Reproduce**
1. Enable coverband in production 
2. Deploy  application with capistrano
2. Use a spesific view and see that its used in the view tracker
3. Deploy the app again with capistrano
4. Check the view tracker and notice that the view use used is listed as unused

**Expected behavior**
I wanted to use the view tracker to track my usage if views. 

**Screenshots**
![Screenshot 2021-08-19 at 08 15 16](https://user-images.githubusercontent.com/3492040/130019149-922a7a73-7ca7-4443-afc9-9ea6517d91e5.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1
 - Browser firefox

**Additional context**

**Comment by stoivo** [comment]
We where able to work around with  this patch to coverband.rb
```
  Dir["/var/www/apps/name/releases/*/"].each do |release|
    config.all_root_paths << release
  end
```
This work fine since we save 100 releases. If you only keept last 3 releases you would quickly delete the foldet so I this patch wouldn'd work that well.

**Comment by danmayer** [comment]
Ahh OK, yeah I haven't seen this in awhile, but if you have multiple changing paths on deploy you need to add a regex on the paths... 

You should just be able to add a regex of your top level path opposed to adding all releases.

something like below, an array or matches can be passed in

`config.root_paths = ['/var/www/apps/name/releases/*/']`

**Comment by stoivo** [comment]
That works. I had to do 
```
config.root_paths = ["/var/www/apps/name/releases/\\\d+/"]
```
