### ISSUE TITLE
First coverage report causes Redis usage spikes

### ISSUE THREAD

**Issue by dostu** [danmayer/coverband#428]
**Describe the bug**
Coverage is reported right after starting Coverband disregarding `background_reporting_sleep_seconds` or `reporting_wiggle` config. This results in Redis usage spikes during deployments to multiple servers.

**To Reproduce**

1. Set `config.reporting_wiggle = 20.minutes.to_i`.
2. Deploy your app.
3. Check Coverband coverage, it will be available right after deployment.

**Expected behavior**
I expect reporting wiggle to have effect on the first report too. It seems like it should work this way from the docs too: https://github.com/danmayer/coverband#avoiding-cache-stampede

**Screenshots**
This is how our Redis CPU usage looks like at night and when rollouts start in the morning.

<img width="996" alt="Screenshot 2021-10-28 at 10 34 19" src="https://user-images.githubusercontent.com/542213/139208920-bb52dc6a-0557-48a7-a76e-0704956e9811.png">

**Additional context**
Related code: https://github.com/danmayer/coverband/blob/635db0ecfdd2e4a41ebb38a79203a2ca7e5d0bbb/lib/coverband/integrations/background.rb#L34

**Comment by danmayer** [comment]
ok check out this PR https://github.com/danmayer/coverband/pull/429  @dostu

**Comment by danmayer** [comment]
This was shipped in 5.2.1 closing
