### ISSUE TITLE
❓ Proposed way to get report safely

### ISSUE THREAD

**Issue by fragkakis** [danmayer/coverband#432]
Hello,

Firstly thank you for this project, we've been using it for some time and has helped us a lot. Also kudos on your interaction with the community, you have been very helpful.

I want to use coverband  without exposing the `/coverage` endpoint, for security reasons. It is possible to block it through network rules etc (and ask authentication before granting access), but I don't want to go down that road.

The approach I would like to follow is something in the following lines:

1. Have a task (either scheduled or triggered by a hook or on demand) which will export a static report. Ideally, that report would be the complete report (assets + `index.html`), or just the `index.html`
2. Upload that to a secure location
3. Access it

With coverband 5, I am not sure how to do that. I could do it with this script:

```ruby
file = File.new("/directory_with_coverband_assets/#{Time.now.strftime("%Y%m%dT%H%M%SZ")}.html", "wb")
file.write(Coverband::Reporters::HTMLReport.new(Coverband.configuration.store).report)
file.close
# upload somewhere with the assets, along with the previously exported files
```

Is there a more out-of-the-box way to do it?

**Comment by fragkakis** [comment]
I just read in closed issues and in the changelog that the static report is no longer supported, as well as the all-files-included layout for the `index.html`.

I would prefer generating an all-files-included `index.html` running a rake task and upload it than opening up an endpoint with the application's source code.

We may have to stick with version 4 after all.

Please chime in if you have any suggestions.

**Comment by danmayer** [comment]
yeah, we removed the S3 feature as it was rarely used and the support became a bit annoying as the single page with embedded CSS/JS was pretty fragile and broke from time to time. It didn't have a ton of tests... The process to make it all as a single file made it harder to iterate on the UI. We did add built-in support for passwords around the web route and tried to make that as easy as possible to secure out of the box.

Sadly, at the moment I haven't had a lot of time for this project so I don't expect to add anything specific to bring this feature back... If you wanted to look at the old code that made the single file and patch it up you could run a branch for the 5.0 series or stick on the older V4 before the feature was removed.

**Comment by fragkakis** [comment]
Thank you @danmayer for looking into it.
