### ISSUE TITLE
Error Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 for Sidekiq workers

### ISSUE THREAD

**Issue by adrys-lab** [danmayer/coverband#437]
**Describe the bug**

We configured Coverband for our Ruby Rails application.

It seems that for the entire application, so `web` oriented part, it works fine, 
but for `workers` we are getting an exception trying to connect to Redis instance.

Each worker has an AWS ECS service associated,
And the error raises every X time for each worker saying:

```
E, [2022-01-08T05:13:07.958852 #1] ERROR -- : Coverband Error: #<Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)> Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
```

And as you can see, it displays the default value for REDIS_URL (localhost).

Our Redis URL Environment variable is called `REDIS_COVERBAND_HOST`.

It seems to us as a first-step raised error, where the ENV VAR has not been injected yet, because afterwards, the coverband works fine for some workers, i paste an image displaying a worker cover report.

So it seems that first, it raises this error, but then the worker works fine and the report is generated for such worker,
but it could be that at worker-initialization phase, the ENV VAR is still not injected, then somehow the initialiser is executed and initialises coverband and all works fine.

(we tried to rename initialiser with `00_coverband.rb` to order it as first initialiser but its not working neither.

Maybe we should call the initializer from our `/config/initializers/sidekiq.rb` ?

Or is it a matter of the ENV VAR name ? that should be at `COVERBAND_REDIS_URL ` instead our current name ?

Or maybe add it into `config.ru` ? 🤔 

We need to make those errors disappear for a good safe-production deployment.

our `coverband.rb` initialiser is under
`/config/initializers/coverband.rb` and looks as:

```
Coverband.configure do |config|
  config.store = Coverband::Adapters::RedisStore.new(Redis.new(url: "redis://#{ENV['REDIS_COVERBAND_HOST']}:6379"))
  config.logger = Rails.logger

  # config options false, true. (defaults to false)
  # true and debug can give helpful and interesting code usage information
  # and is safe to use if one is investigating issues in production, but it will slightly
  # hit perf.
  config.verbose = Rails.env.development?

  # default false. button at the top of the web interface which clears all data
  config.web_enable_clear = true

  # default false. Experimental support for tracking view layer tracking.
  # Does not track line-level usage, only indicates if an entire file
  # is used or not.
  config.track_views = false

  # Help not having all server report coverage at the same time (unit: seconds)
  config.reporting_wiggle = 60

  # List of ignored files. We know they are valuable.
  config.ignore += [
    'config/application.rb',
    'config/boot.rb',
    'config/puma.rb',
    'config/schedule.rb',
    'bin/*',
    'config/environments/*',
    'lib/tasks/*'
  ]
end
```

**Expected behaviour**
It works for the entire application, web + workers.

**Screenshots**
Datadog Errors
![image](https://user-images.githubusercontent.com/35842560/148632667-4297d24a-5864-442c-a88d-303811259646.png)

Workers/Consumers report
![image](https://user-images.githubusercontent.com/35842560/148632764-49d5e66e-7a69-4165-9d89-58ef627d276c.png)

Workers/Consumers coverage
![image](https://user-images.githubusercontent.com/35842560/148632794-83facd06-7299-42cf-b963-f54f574e7bbe.png)

 - Version: Ruby 2.6.5 - Rails 6

**Comment by danmayer** [comment]
What are you using to inject your ENV vars? Did you look at this section where it covers ensuring ENV vars get setup and configured before coverband boots up?

https://github.com/danmayer/coverband#working-with-environment-variables

**Comment by adrys-lab** [comment]
We have our ENV VARS in `.env.docker` and `rails.gitlab-ci.yml`.

Those ENV VARS are overrided per environment by a separate project that builds all the infra part.

So you think its a matter of preliminar error before coverband boots up ?

**Comment by danmayer** [comment]
So mostly when we have seen this somehow the ENV vars aren't available at the time of the app booting... explicitly having `dotenv` load before coverband if that is loading your `.env.docker` should help resolve that.

**Comment by adrys-lab** [comment]
ok, we will try to inject ENV VARS as soon as possible in the boot phase.

Any other tricks we could consider ? Can we disable this booting up coverband as soon in the boot phase ?

It seems it boots really soon on the runtime lifecycle, but maybe we dont need that as we are only interested on the runtime stats.

**Comment by danmayer** [comment]
yeah so it boots early to capture code loaded vs code runtime... but one can skip out of the loading stuff... For that you can do `require: false` for the coverband gem in your Gemfile. Then you can in your application.rb or just in the initializer `require 'coverband'` that will let you trigger the loading and code when ever your want to kick it off, ensuring you can defer it until after ENV vars are all loaded... This may just mean some files that are loaded and never used at runtime don't even show as loaded.

**Comment by adrys-lab** [comment]
Another possible issue is that when a worker is launched,

Coverband tries to get the REDIS URL by the default ENV VARS mentioned in the doc

```
By default Coverband will try to stored data to Redis * Redis endpoint is looked for in this order: ENV['COVERBAND_REDIS_URL'], ENV['REDIS_URL'], or localhost
```

And then, the `coverband.rb` initializer is called, and all works fine.

could that be a possibility ?

**Comment by danmayer** [comment]
hmm yeah that could be @adrys-lab i you control the naming and use `COVERBAND_REDIS_URL` instead of `REDIS_COVERBAND_HOST` that might help with the load order issue.

**Comment by danmayer** [comment]
closing assumed resolved
