### ISSUE TITLE
Showing untouched files

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#44]
I noticed that coverband only shows files that have been hit at least once.  This leaves out all of the files that were never hit and the number one candidates for deletion.  Was thinking it would be better to go through the full file system to produce the report instead of just relying on the set of files within redis.  Here is a hacked branch i used to get it done:

https://github.com/danmayer/coverband/compare/master...kbaum:show_uncovered_files?w=0

Obviously hardcoding the `Dir.glob` inclusion path is not the right way to go, but i wanted to see if others thought this is the general way to go.

thx!

**Comment by danmayer** [comment]
looking at how Rails `rake stats` finds and goes through files might be a good idea, I believe it is just `Dir.glob`

**Comment by kbaum** [comment]
@dnasseri @danmayer - looks like this kind of comes with simplecov.  The following seems to work:

https://github.com/danmayer/coverband/compare/track_all_files?w=0

**Comment by danmayer** [comment]
nice

**Comment by dnasseri** [comment]
Very cool. It doesn't seem like were testing scov style reports in the reporter_test, do you think there is anyway we can?

**Comment by danmayer** [comment]
took your change and added that in... @kbaum also added some test coverage for the scov style reports @dnasseri 

https://github.com/danmayer/coverband/pull/78

will be released as 1.3.1
