### ISSUE TITLE
Clarification of % covered versus % runtime columns

### ISSUE THREAD

**Issue by bartimez** [danmayer/coverband#441]
Hi - thanks for this wonderful project, my team is really excited about it.  

Reaching out for clarification around the columns in the report.  I've read [this previous issue](https://github.com/danmayer/coverband/issues/312), which indicates the `% covered` column is the percentage of lines eagerly loaded, while the `% runtime` is the percentage of lines executed at runtime.  What's confusing me is that the tooltip for `% covered` seems to indicate that number is inclusive of both load time and runtime:

![image](https://user-images.githubusercontent.com/17676265/157277527-063c45a6-4c9b-4725-91fd-c0753da599c3.png)

If `% covered` is inclusive of both load and runtime, that would suggest it should never be a smaller number than `% runtime`, which is not what I'm seeing in our report, e.g.:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/17676265/157277794-0fa6f7b3-3002-468b-bd48-47cdd75bf6fd.png">

Could you clarify/let me know if I'm thinking about this correctly? Happy to open a PR to adjust the tooltip if that needs to happen. 
Thanks.

**Comment by danmayer** [comment]
this all cleared up @bartimez or any further questions?

**Comment by bartimez** [comment]
Thank you @danmayer ! Sorry for the long lead time here!
