### ISSUE TITLE
Docs: Offer Guidance on Redis Instance Sizing

### ISSUE THREAD

**Issue by theturtle32** [danmayer/coverband#443]
**Is your feature request related to a problem? Please describe.**
I'm trying to decide what instance size to use for the Redis server I'm dedicating to Coverband in production, and can find no information on how much data I should expect CoverBand to store.

**Describe the solution you'd like**
I'd love to see any of:
* Historical Redis memory utilization metrics from a production deployment
* An overview of what, exactly, gets stored in Redis
* Rough, zoomed-out description of how to select an initial Redis instance size. What are the variables that can affect memory utilization in Redis?

**Comment by danmayer** [comment]
OK, I could definitely put something together... as I get a better readme level guide, do you have some info on your setup and I could likely give info about the redis used for a similar size production system...

In general, the usage is pretty low as there are throttles and controls for how long to store in memory before syncing.

**Comment by danmayer** [comment]
Also, in case it helps we have some of our largest services with hundreds of servers on `cache.m3.medium` with plenty of overhead to spare. I run most on the smallest instances available and bump up only if needed or if I am forced to be on a shared redis instance, which I try to avoid.

**Comment by theturtle32** [comment]
Ok, that gives me a really great rough idea of what to expect. Thank you! Even just that little bit of anecdotal information in the Readme would be super helpful!

**Comment by danmayer** [comment]
updated docs with some more info in 5.2.3
