### ISSUE TITLE
Explicitely disable coverband without an ENV var?

### ISSUE THREAD

**Issue by misham** [danmayer/coverband#449]
**Is your feature request related to a problem? Please describe.**
Using `COVERBAND_DISABLE_AUTO_START` requires the env var to be set before the gems are loaded. This makes it difficult to control programmatically in different environments.

For example, I can't just do `ENV["COVERBAND_DISABLE_AUTO_START] = "1"` in an initializer as the gem is already loaded.

**Describe the solution you'd like**
I don't want to change existing behavior, but would like a way to disable Coverband __after__ the gem has been loaded. This can be part of the config or a separate function call or something else.

**Describe alternatives you've considered**
Right now, we have to manually manage environment variables, this is quite error prone.

**Additional context**
N/A

**Comment by danmayer** [comment]
So the reason we can't disable it AFTER it has been required is that it will start the underlying Ruby coverage engine which will have performance impacts regardless of actually using coverband.

what you want can be achieved though...

```ruby
# in gemfile
gem 'coverband', require: false

# application.rb
...
# Require the gems listed in Gemfile, including any gems
# your various requires like require_relative "boot"
...
Bundler.require(*Rails.groups) # or require "rails"
require "coverband" if some_logic == true
...

# Then anywhere you use coverband like in the coverband/config.rb or routes, wrap the usage
if defined? Coverband
  # add your coverband routes to the routes file
  # or do any coverband configuration
end
```

This gives you full programmatic control of having coverband start in code. Let me know if you have any questions @misham
