### ISSUE TITLE
Track Gem Support, please bring back

### ISSUE THREAD

**Issue by gdlninja** [danmayer/coverband#452]
I know previous version of Coverband allowed for tracking gems to help determine what was being used and what could be removed cleanly. I am looking for this functionality to be brought back into the project or do you have an alternative?

Thanks!

**Comment by danmayer** [comment]
odd, did this get covered somewhere online recently? This just came up as another issue a few days prior to this ticket, you can read more about it there https://github.com/danmayer/coverband/issues/451

As noted, tracking a single gem isn't performant with how Coverband works, so after various experimentation and attempts to make it more performant, that feature was removed. It has an unacceptable level of overhead. I recommend instrumenting the gem directly with your aggregated logging tool or observability tool like data dog.

**Comment by danmayer** [comment]
I am closing this as there are a number of reasons tracking gem usage is a different sort of problem than app tracking.

**Comment by kbaum** [comment]
We had tried this a while back and it was absurdly slow.

**Comment by kbaum** [comment]
One idea here is to somehow only track any usage at all of the gem and then just somehow immediately stop tracking the coverage of that gem for the life of the process. We only really care if that gem is called at all. Not at all sure if that's possible or just wishful thinking.

**Comment by danmayer** [comment]
yeah, it was far to slow to track all gem usage... I think something more targetted that would only track specific gems could help, but I also think many folks are looking for gem usage across different micro-services and coverband is more setup for single service tracking... So I think probably just a different enough domain that it isn't likely something to add back in here... 

Even the old coverband approach before using Coverage.so where things tracked via tracepoint might be a better way to target a specific gem...
