### ISSUE TITLE
Issue on Coverband initializer on Ruby 3.1.2

### ISSUE THREAD

**Issue by dynelight** [danmayer/coverband#453]
I'm not sure if this is because I need to do any new or different write up for Ruby 3, but this fails: 

```
# config/coverband.rb
Coverband.configure do |config|
  config.store = Coverband::Adapters::RedisStore.new(
    Redis.new(
      url: ENV['REDIS_URL'],
      ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
    )
  )
end
```

```
/Users/dynelight/Projects/v/config/initializers/coverband.rb:2:in `<main>': uninitialized constant Coverband (NameError)
```

**Comment by danmayer** [comment]
Are you sure you have it in your gemfile, if you have `require: false` you will need to require it manually in something like `application.rb` or remove the `require: false` from your gemfile. We have this running in several Ruby 3.1.2 apps without anything like this.

**Comment by danmayer** [comment]
sorry for the delay @dynelight I was on vacation so it took a bit to get back to you on the issue.

**Comment by danmayer** [comment]
Ah... sorry, the coverband configuration file should be `config/coverband.rb` not `config/initializers/coverband.rb` This came up in another recent github issue and I will be making some changes to help avoid this issue.... move the file and you should be good.

**Comment by danmayer** [comment]
No, this shouldn't be Ruby 3 and most things use initializers, I should perhaps allow that for Coverband, but it is a bit odd in that I need to bootstrap it BEFORE most of Rails is up and running, hence the unique configuration file location.

**Comment by danmayer** [comment]
if you have bundler setup correctly it should definitely be there before routes... you can just require 'coverband' at the top of the routes file, but something seems odd about your setup.

**Comment by danmayer** [comment]
since some other folk shave also had some issues with configuration, I added an install task that makes it more clear where to add the config file.

https://github.com/danmayer/coverband/issues/450
