### ISSUE TITLE
Redis InheritedError after upgrading to Ruby 3.1.2/Rails 7.0.4

### ISSUE THREAD

**Issue by jasonperrone** [danmayer/coverband#461]
**Describe the bug**
Getting this error in the logs after upgrading to Rails 7.0.4/Ruby 3.1.2:

App 22211 output: E, [2022-10-17T14:58:11.000405 #22211] ERROR -- : coverage failed to store
App 22211 output: E, [2022-10-17T14:58:11.000491 #22211] ERROR -- : Coverband Error: #<Redis::InheritedError: Tried to use a connection from a child process without reconnecting. You need to reconnect to Redis after forking or set :inherit_socket to true.> Tried to use a connection from a child process without reconnecting. You need to reconnect to Redis after forking or set :inherit_socket to true.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Coverband: 5.2.4

Coverband is being run as Rack Middleware with this entry in routes.rb:
```
  if Rails.env.production?
    Rails.application.routes.draw do
      authenticate :user, lambda { |u| u.admin? } do
        mount Coverband::Reporters::Web.new, at: '/coverage'
      end
    end
  end
```

**Comment by danmayer** [comment]
Do you have a coverband config file, can you share the location of that file and some of the details in it around how you set it's redis?

Is this in development or production, I am assuming the `fakeredis` used for testing isn't involved... if that gem is in development and not only test I have seen this error.

**Comment by danmayer** [comment]
ah and what server are you using... puma? and version?

**Comment by jasonperrone** [comment]
This is my coverband config:

```
Coverband.configure do |config|
  config.verbose = false
  config.web_enable_clear = true
  config.track_views = true
end
```

This is in production. I didn't configure anything special for Redis... it's just hitting in on localhost port 6379, or whatever Redis' default is.

The web server is nginx 1.14.0/Passenger 6.0.15.

Hope that helps.

**Comment by mateuscruz-morningstar** [comment]
We have the exact same issue.

**Comment by danmayer** [comment]
hmm given you are both using passenger, thinking I might have an issue with how we detect our forked processes for that case... I will take a look.

**Comment by mateuscruz-morningstar** [comment]
@danmayer this seems to have worked for me (although I'm not sure it's the best way to do it):

```ruby
# app/config.ru

if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    if forked
      # We're in smart spawning mode.
      Omx.redis.disconnect!
    end
  end
end
```

**Comment by danmayer** [comment]
Nice that makes sense... Since I don't want to try to detect all app servers and handle all the on_events for all the server options. I am thinking I can `rescue InheritedError` in coverband and try to do a disconnect/reconnect or something like that...

but having apps handle this themselves is best as my method would occur at runtime on first requests causing a slower first response in the app.

**Comment by danmayer** [comment]
noting if you are using redis-rb 3.1.0 or great it will handle this for you. I prefer just letting the library handle the issue vs trying to capture it so I am going to close this out ...

 https://sorentwo.com/2015/08/25/managing-redis-reconnections-from-ruby

If you anyone is seeing this please include which redis client you are using and the version and I could revisit it... but for now calling this good.
