### ISSUE TITLE
Not able to mount Coverband with Padrino Application

### ISSUE THREAD

**Issue by vs37559** [danmayer/coverband#479]
**Describe the bug**
When the Web view is mounted to a route in Padrino application, on hitting that route getting error stating the 'call' method is not defined for the class.
### Error
    Unexpected error while processing request: undefined method `call' for Coverband::Reporters::Web:Class
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/padrino-core-0.15.3/lib/padrino-core/router.rb:84:in `block in call'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/padrino-core-0.15.3/lib/padrino-core/router.rb:75:in `each'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/padrino-core-0.15.3/lib/padrino-core/router.rb:75:in `call'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/newrelic_rpm-9.1.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/Users/developer/Desktop/testing/coverband/lib/coverband/integrations/background_middleware.rb:10:in `call'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/newrelic_rpm-9.1.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/thin-1.8.0/lib/thin/connection.rb:50:in `block in process'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/newrelic_rpm-9.1.0/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/newrelic_rpm-9.1.0/lib/new_relic/agent/tracer.rb:356:in `capture_segment_error'
	/Users/developer/.rvm/gems/ruby-2.7.3@project/gems/newrelic_rpm-9.1.0/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'

**To Reproduce**
1.  Create one basic application with Padrino Framework (any example app would do)
2. Add Coverband as per Sinatra requirements (as a middleware)
3. Add mounting for Coverband
    `Padrino.mount('Coverband', app_class: 'Coverband::Reporters::Web', app_root: Coverband.configuration.root).to('/coverage')`
4. Hit `coverage` url
5. See Error

**Expected behavior**
Coverband web view report should open.

**Libraries:**
 - Ruby: 2.7.3
 - Padrino: 0.15.3
 - Sinatra: 2.2.4

**Possible Solution**
A class method wrapper for 'call' method present in `Web` class would resolve the error.

**Comment by danmayer** [comment]
OK, so I believe this is because I instruct folks to use an instance not a class when setting up with Rails

`mount Coverband::Reporters::Web.new, at: '/coverage'`

I haven't used Padrino for years but if it requires a class opposed to an instance of an object...

It does look like the wrapper approach you suggest would word work as that is what sidekiq and other web UIs for rack do...

https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/web.rb

I am not likely to work on this anytime soon myself but if you build out a PR, I would accept it.

**Comment by vs37559** [comment]
Dan, Glad you are willing to accept the changes. This would save me from maintaining the fork at all times.
Here is the [pull request](https://github.com/danmayer/coverband/pull/482) attached.

About removing support for Ruby 2.7.x from my other [issue](https://github.com/danmayer/coverband/issues/478).
Will it be possible for you to give a minor release with these updates?

I'll eventually be moving to Ruby 3 but it might take a couple of months in doing so.

**Comment by danmayer** [comment]
I could backport and make a minor release with the rack middleware support. What version are you running with your fork and I can help out with that.

**Comment by vs37559** [comment]
I am running the main branch itself with below configurations:

- Ruby: 2.7.3
- Padrino: 0.15.3
- Sinatra: 2.2.4
- ActiveRecord: 5.1.1

**Comment by danmayer** [comment]
cool... that is helpful but I mean are you currently forked off from a tagged release of coverband?

**Comment by vs37559** [comment]
No, the fork is from the main branch itself

**Comment by vs37559** [comment]
Maybe you could use v5.2.5 itself as base reference and include this fix and the 'hash' method rename fix for a v5.2.5.1

All the RC version changes can be avoided then.

**Comment by danmayer** [comment]
OK... so this is release before I removed 2.7.3 Ruby support. `Pushed coverband 5.2.3.1 to rubygems.org` you can see the diff off the 5.2.3 release here https://github.com/danmayer/coverband/compare/2_7_3_rack_fix?expand=1

Alternatively I have a new RC on the 5.2.6.RC branch that includes the rack path and the hash version...

`Pushed coverband 5.2.6.rc.5 to rubygems.org`

If you need another 5.2.3.2 release that also includes the hash patch fix let me know and I can do that.... r I guess if you want one off 5.2.5.1, I can do that as well with both patches let me know.

**Comment by vs37559** [comment]
I have checked all my target repositories, the bundler is resolving the gem to v5.2.5 itself even for rubies v2.7.2, v2.7.3, v2.7.5, v3.1.2

I think 5.2.5.1 with both the patches would work for me for now. 
I'll push the changes to production by next week for at least two of my repositories. In case of any issues, I'll check with 5.2.3.1 and let you know on that as well.

**Comment by danmayer** [comment]
cool try the RC... if that doesn't work 

I added the hash fix and just released `Pushed coverband 5.2.3.2 to rubygems.org`

**Comment by vs37559** [comment]
Cool, I think this should work.

Thanks for the help! Closing this issue thread.
