### ISSUE TITLE
Output showing 0% or 100% in % Covered

### ISSUE THREAD

**Issue by swomo2020** [danmayer/coverband#486]
**Describe the bug**
The issue is when I view the report, it shows either 0% or 100% in the "%covered" column. When I click on one of the 0% covered files, it shows all the correct lines as red:
![image](https://github.com/danmayer/coverband/assets/15053674/3f090d6d-a39f-47df-9f1a-8b48cd506cd7)
But once that file gets used (i.e. I call one of the api endpoints). Then only the used endpoint is green and the rest of the file has no markings (appears as not reachable). Also, it shows that only the green lines are the relevant lines in the file:
![image](https://github.com/danmayer/coverband/assets/15053674/f29a809c-44ff-42e9-a74b-57cd7ce515b9)
This is occurring in our production environment but were able to duplicate it in our development environment which is in docker. Below is our config/coverband.rb config file:
```
#config/coverband.rb v2.0.3
Coverband.configure do |config|
  config.root              = Dir.pwd
  config.memory_caching    = true
  config.collector         = 'trace' # ruby 2.3.0+ uses 'coverage'
  config.redis             = Redis.new(url: "#{ENV['REDIS_URL']}/1")
  config.store             = Redis.new(url: "#{ENV['REDIS_URL']}/1")
  config.include_gems      = true
  config.root_paths        = ['/app/']
  config.ignore            = %w[vendor .erb$ .slim$ .haml$
                                config/application.rbH
                                config/initializers/secret_token.rb
                                config/initializers/sentry.rb
                                config/initializers/raven.rb]
  config.startup_delay     = 0
  config.percentage        = Rails.env.production? ? 20.0 : 100.0
  config.logger            = Logger.new("#{Rails.root}/log/coverband.log")
  config.safe_reload_files = ['config/coverband.rb']
  config.verbose           = Rails.env.production? ? false : true
end
```

We then start coverband in our config/application.rb:
```
# Coverband needs to be setup before any of the initializers to capture usage of them
    require 'coverband'
    Coverband.configure
    config.middleware.use Coverband::Middleware

    config.before_initialize do
      require 'coverage'
      Coverband::Collectors::Base.instance.start
    end
```

I am adding coverband in our Gemfile like this: `gem 'coverband', '~> 2.0.3'`

Versions:
- Coverband: 2.0.3
- Ruby: 2.2.10
- Rails: 3.2.22
- Redis: 6.2.6

The reason we are using the older coverband is because of our older ruby and rails. We want to use coverband to clean up unused code and determine priority controllers before starting a ruby/rails upgrade to current versions. So upgrading coverband isn't really an option at this point since this is the newest version compatible with our setup. 

**To Reproduce**
Implement ruby on rails application with the same versions.  

**Expected behavior**
We  are expecting the report to appear like the documentation: https://github.com/danmayer/coverband/blob/v2.0.3/README.md#example-output 

**Desktop (please complete the following information):**
N/A - Docker image `ruby:2.2.10`

**Smartphone (please complete the following information):**
N/A - Docker image `ruby:2.2.10`

**Additional context**
N/A

**Comment by christopher-engesser** [comment]
Commenting as I work at the same organization as Shawn and we are seeing this issue on several other rails projects we are trying to upgrade. Any help debugging and resolving the issue would be greatly appreciated.

**Comment by danmayer** [comment]
You look to be using Coverband `2.0.3` that is out of support and likely has some issues in it, we are now using the 5.2 / 5.3 line for any fixes and features. We have dropped support for Rails 3.2 lon again. I am unlikely to be able to help you on this issue...

https://rubygems.org/gems/coverband/versions/5.2.5?locale=en

You can try to look through the changelog to find the last version of coverband that supported your Ruby and Rails version and then try to debug it yourselves, sorry I can't be more helpful.
