### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by carlosmedrano97** [danmayer/coverband#487]
**Describe the bug**
I'm not sure if I'm missing other step for the installation but the assets and the basic authentication is not working for me, I have tried with the env and also with the config and nothing

**To Reproduce**
1. I just added the gem on the gemfile
2. Execute bundle and run the rails server

**Expected behavior**
Page should look ask for the password
Page should look like the example but its plain

**Screenshots**
![image](https://github.com/danmayer/coverband/assets/14798791/3a0f00fe-2c84-4ba0-a565-e75cf99abdf3)
![image](https://github.com/danmayer/coverband/assets/14798791/fe2d3c31-5c1b-4ad0-9de9-c48622f663ed)

**Additional context**
Ruby 2.7.6
Rails 6.0.6

**Comment by danmayer** [comment]
did you figure it out @carlosmedrano97 something is wrong with how you are loading assets and other parts of coverband so perhaps it is breaking the middleware and password check?
