### ISSUE TITLE
store clear raises TypeError on rake coverband:clear - Redis V5.0.8 

### ISSUE THREAD

**Issue by benngarcia** [danmayer/coverband#493]
**Describe the bug**
coverband:clear errors

**To Reproduce**
1. Rails 7 app, Ruby 3.2.2, Redis v5.
2. Run rake coverband:clear

**Expected behavior**
Task doesn't error

**Screenshots**

<img width="1078" alt="image" src="https://github.com/danmayer/coverband/assets/49890553/9dd2913b-bb72-4dcd-bd2b-276b18c16968">

**Additional context**
I think it's caused by the following
```ruby
      def clear!
        Coverband::TYPES.each do |type|
          @redis.del(type_base_key(type))
        end
        # temporarily clear the old namespace of coverband_3_2
        @redis.del(type_base_key(nil)) # <= this is what's causing the error
      end
```

Backtrace supports this theory. I can put together a PR just to strip this out, but I'm not entirely sure what situation this code was covering, and if this line 35 not working properly has introduced other problems.
<img width="802" alt="image" src="https://github.com/danmayer/coverband/assets/49890553/90898e60-6ae0-4bea-9dc8-5cede772549f">

**Comment by danmayer** [comment]
yeah we can remove the support for clearing old Coverband 3.2 namespaces

```
# temporarily clear the old namespace of coverband_3_2
@redis.del(type_base_key(nil)) # <= this is what's causing the error
```

I also recommend clearing via the web and not rake tasks... as I have seen more companies lock down running tasks on production I mostly work on the middleware web tasks now.

**Comment by benngarcia** [comment]
You already did this in [46673b7](https://github.com/danmayer/coverband/commit/46673b7b47b3551d7b53953862f4323da778695e).

Sorry for the confusion, thought I was on the latest version. 6.0.1 is fine.
