### ISSUE TITLE
20% increase in transaction times when used in production

### ISSUE THREAD

**Issue by DChalcraft** [danmayer/coverband#497]
This is more a question than a bug/feature, but we recently started using coverband on our production fleet and noticed a 20% increase in web transaction times across the board. Is this expected?

Also is there anything we can do to investigate it, possibly we can find a way to bring that performance impact down? Ideally we'd like to run the tool indefinitely as we clean up code, but that probably isn't possible with the current hit.

Totally understand some performance impact is expected, but just wanted to see if you or anyone else had noticed similar.

**Comment by kbaum** [comment]
Hi @DChalcraft. I haven't used coverband in a while but 20% seems like a lot to me. Coverband relies on ruby's standard library code coverage which is pretty fast and shouldn't have that much overhead. Coverband also needs to write data to redis which should also be quite fast.

I think it would be interesting to dig in and see what's happening in your case. If you can replicate the issue in development then I think we are in a good position to track this down using a flame graph. Here's a library that I have used. 

https://github.com/SamSaffron/flamegraph

As mentioned in the readme you could also use rack-mini-profiler which is a convenience library built on top of flamegraph and allows for generating the flamegraph directly in your browser with a request parameter.

In the end, you really just need to execute a code sample with coverband and without and compare the two flamegraphs. Just make sure that you've reproduced the issue in dev with that code sample before bringing in flamegraphs.

Hope that helps!

**Comment by danmayer** [comment]
yeah, I haven't seen anything that drastic in terms of performance impact. If you have more info on the size of project, rails version, ruby version, coverband version, machine memory / CPU, etc that might help.

If you haven't adjusted any of the various toggles like reporting wiggle etc it would be worth trying those out.

**Comment by danmayer** [comment]
Did you try anything else? If you have any other info I can try to look...

* rails / ruby versions
* number of files
* server: puma, unicorn, etc?
* coverband configuration file / options?

LEt me know if you are doing any other investigation or want some specific help or I will close this out.

**Comment by DChalcraft** [comment]
We've had to move onto other things for now so haven't had a chance to come back to this. If we return in the future I will post an update. Thanks for the help!

**Comment by danmayer** [comment]
yeah it can depend on various things but the overhead can be significant. In terms of the best way to do sampling generally if you run multiple processes and servers in production and have load balancing between them it is better to just enable on some percentage of the server processes and not in others. This will mean requests that are routed to the servers running coverband are a bit slower, but will gather the coverage information. This is much better than just sampling with coverband as that would still need coverband to load the module for code tracking which has a performance impact just by loading it, so sampling requests after it is loaded isn't really going to fix the performance impact.

**Comment by jjb** [comment]
@danmayer thank you for that info and suggestion! I made these two followup PRs:

* https://github.com/danmayer/coverband/issues/628
* https://github.com/danmayer/coverband/pull/629
