### ISSUE TITLE
Docs/clarification request

### ISSUE THREAD

**Issue by trivett** [danmayer/coverband#521]
As a new user of Coverband, I would like some clarification regarding how to read the data in the UI.

What I would like to see (and I would be happy to contribute to docs if possible) is a little more color to what the various bits information that Coverband surfaces. Perhaps a definition of what "% covered", "% runtime", "lines", "relevant lines", "lines covered", "lines runtime" "average hits /line" mean in detail.

**Comment by mercedesb** [comment]
@trivett I have no connection to this repo, but stumbled across this issue. [This closed issue](https://github.com/danmayer/coverband/issues/312) may answer your questions

**Comment by trivett** [comment]
@mercedesb Perfect, thank you so much! I might make a PR to make this easier to find.
