### ISSUE TITLE
Redis namespace is not used by ViewTracker

### ISSUE THREAD

**Issue by eliotsykes** [danmayer/coverband#539]
**Describe the bug**
The `redis_namespace` configuration is ignored by ViewTracker.

**Additional context**
Modifying `redis_namespace` is useful to start recording new coverage data, whilst keeping the old data around. It is also a useful technique to ignore in-memory coverage data on servers that have not been restarted with a new version of the codebase. 

I noticed that changing `redis_namespace` does not have the desired effect to record new coverage data for views. 

The issue appears to be in `AbstractTracker#class_key` which does not use `redis_namespace`.

**Comment by danmayer** [comment]
ok, fixed this in the most recent commit 437a8db85b3ea18b825991dabbc7e75b202c0a7c
