### ISSUE TITLE
Support other storage tools besides Redis

### ISSUE THREAD

**Issue by kerrizor** [danmayer/coverband#54]
Not everyone runs Redis, but are running some kind of key/value store. Would it be a huge change to abstract the Redis usage to allow for storage solutions?

**Comment by danmayer** [comment]
So it would actually be pretty easy, we already have two stores

* [RedisStore](https://github.com/danmayer/coverband/blob/master/lib/coverband/redis_store.rb)
* [MemoryCacheStore](https://github.com/danmayer/coverband/blob/master/lib/coverband/memory_cache_store.rb)

Really we only use the memory store for tests, but I could see it being helpful in dev mode. So we would just need to make another store for whatever or make a more generic key/val store that could be passed any store that supports set/get. 

Then we would just need to clean up / make the configuration a bit more robust.

[Configuration checks if you set redis](https://github.com/danmayer/coverband/blob/18e7ce2b94518a3387a59bbea98600e06339ffd3/lib/coverband/base.rb#L48), could check for a set store and then pick appropriate adapter. 

Do you have a store in mind probably easiest to work on with a more concrete example.

**Comment by oboxodo** [comment]
I would prefer to just send you a PR with MemCached support baked in, but can't take the time to work on that at the moment. I still wanted to mention MemCached here in case someone else has the time and will to do so :)

**Comment by danmayer** [comment]
The store class is completely abstracted out now in this upcoming PR, and has added file store. While I haven't added memcache yet it should be pretty simple to do so and I might follow up with that if no one else get to it first.

https://github.com/danmayer/coverband/pull/79
