### ISSUE TITLE
Unable to ignore view files with `config.ignore`.

### ISSUE THREAD

**Issue by thijsnado** [danmayer/coverband#542]
**Describe the bug**
Unable to ignore view files with `config.ignore`.

**To Reproduce**
1. Add a view `app/views/anything/ignore_me.html.erb`
2. Add `config.ignore += ["app/views/anything/ignore_me.html.erb"]`
3. Go to `/coverage/views_tracker`
4. See that view is still shown

**Expected behavior**
I would expect the view not to be included in the view tracker.

**Additional context**
We have several views which are needed for development but unused in production. I'd like to ignore these ones since they are never used and create noise.

**Comment by danmayer** [comment]
thanks @thijsnado this is fixed and should go out in the next release
