### ISSUE TITLE
Rails Version Compatibility - Coverband & Rails 2.x

### ISSUE THREAD

**Issue by chriswarren** [danmayer/coverband#546]
I've looked around a bit in hopes of figuring out which versions of Coverband support older versions of Rails, but haven't turned up anything so far. I've opened a handful of Gemfile/gemspec versions to see if I could figure it out myself first.

Hoping to use Coverband on an older Rails 2.3.x app so we can drop old code before we spend time on a long overdue upgrade - any guidance on versions to use would be appreciated.

**Comment by danmayer** [comment]
wow that is gong back... You know I am not sure anything would really work for Rails 2 anymore, I believe much of the original coverband targeted Rails 3... there is a chance original releases or very early versions would have worked, but I will warn there was some serious performance issues back then, and it mostly required sampling
