### ISSUE TITLE
What is the Default Redis Namespace? Coverband.configuration.redis_namespace is nil 

### ISSUE THREAD

**Issue by sshaw** [danmayer/coverband#547]
Documentation does not list default namespace nor TTL (though `Coverband.configuration.redis_ttl` does not return `nil` like `Coverband.configuration.redis_namespace` does). Would be good to know this information without having to look through the code or collecting data.  Although after a cursory look through the code, I could not find it!

**Comment by danmayer** [comment]
yeah, perhaps I should rename that, this isn't a redis namespace like the redis gem, but just a prepended string to the coverband keys in redis... When it is nil there is nothing extra prepended... now coverband itself will always prepend a format/version so either

* `coverband_hash_4_0`
* `coverband_3_2`

this depends if you are using the hash or tradition redis adapter, those are hard coded into the code and updated when we make breaking changes to the storage format.
