### ISSUE TITLE
Current documentation doesn't work on 1.1 version

### ISSUE THREAD

**Issue by lucianosousa** [danmayer/coverband#55]
Can you guys check this?

I've tried run here the 1.1 version and doesn't work. Installed v1.0.x and works fine.

error happening:
`uninitialized constant Coverband::Base::TracePoint`

**Comment by danmayer** [comment]
yeah I can take a look, might not get a chance until Monday. We did make quite a few changes so documentation probably fell behind. I will set it up on a clean new Ruby 2.3 Rails app.

**Comment by danmayer** [comment]
hmmm @lucianosousa can you give some additional feedback. I just went through the readme and setup a new Rails 4 app on Ruby 2.3.0 with coverband 1.1

https://github.com/danmayer/covered_rails

My commits might help you spot something different in your process /  mine

Could you tell me which versions of Ruby and Rails you have. Any other info about the steps or process you followed would also be helpful tracking it down.

**Comment by lucianosousa** [comment]
I'm using ruby 2.3.0 with rails 4.2.5

I did exactly what current documentation said. Nothing more, nothing less

**Comment by danmayer** [comment]
OK if you have a repo, I could look over it as I feel like all I did was follow the docs as well so I don't have a good suggestion without a better idea of the steps you took.

**Comment by lucianosousa** [comment]
Sure, it happened in a private repo but I'll try create the same env this week(public one).

**Comment by danmayer** [comment]
I still don't know what is needed or the issues since I was able to get it setup I am closing for now but if you have any more info on the problems or errors you faced let me know.
