### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by scottgratton** [danmayer/coverband#550]
Hello, I'm curious to know if coverband will put out a new release with recent changes. I noticed that the last release is from 2020, but there are many commits since then. Just considering if I need to point to a specific commit when adding it to our codebase or if is recommended to use the last release.

Thanks - I'm excited to give this a try in helping to clean up a large codebase!

**Comment by Drowze** [comment]
Just want to point that new releases are still being pushed to rubygems (see [here](https://rubygems.org/gems/coverband/versions/6.1.2)).
I understand it's a bit confusing though since they are not (currently) reflected in GitHub releases

**Comment by danmayer** [comment]
ahh interesting, yeah I haven't been using the github release feature so much as rubygems... I also need to cut a new release with the last few weeks of work which is soon... I will try to also update in the github releases.

**Comment by scottgratton** [comment]
No worries! Thanks for pointing out the releases on rubygems @Drowze 🙏 

Thanks for this awesome gem! Super excited to start axing some cruft 🪓

**Comment by danmayer** [comment]
ok @scottgratton a new release which has small fixes from the last few months 6.1.3 release also tagged with release notes in github https://github.com/danmayer/coverband/releases/tag/v6.1.3

If you have issues let us know there are a few active folks contributing to Coverband these days
