### ISSUE TITLE
Killswitch ENV var?

### ISSUE THREAD

**Issue by vlad-pisanov** [danmayer/coverband#551]
Not sure if I missed it in the documentation, but is there a global ENV var to disable Coverband, without having to deploy a code change?

Most analytics/apm gems have a killswitch ENV var like:

```ruby
ENV['DISABLE_COOL_ANALYTICS_GEM'] = 'true'
```
or a configuration option you can tap into
```ruby
config.enabled = # ... custom logic ...
```

**Comment by fatkodima** [comment]
There is no any, but I agree this can be useful.

**Comment by danmayer** [comment]
Does `COVERBAND_DISABLE_AUTO_START ` not work for you @vlad-pisanov I believe that does what you want

https://github.com/danmayer/coverband?tab=readme-ov-file#manually-starting-coverband

**Comment by vlad-pisanov** [comment]
That should work, thanks! Didn't occur to me to look for it under "Manually Starting Coverband".
