### ISSUE TITLE
Documentation doesn't describe how to read coverage statistics from Redis

### ISSUE THREAD

**Issue by thedrow** [danmayer/coverband#57]
Is there an API to read the coverage statistics from Redis?
Some other method?

**Comment by thedrow** [comment]
Seems like Coverband.report only fetches the coverage data from redis.
It wasn't clear from the documentation.

**Comment by danmayer** [comment]
That is correct, We could definitely make that a bit more clear in the documentation. I mostly focused on the rake tasks and how people could get the html report opposed to the API where people can grab the data in code. Do you think a small API section on the docs would be helpful?

**Comment by thedrow** [comment]
Yes it would. You can also add the documentation to the code and generate RDoc.

**Comment by danmayer** [comment]
various docs are updated, will be making another pass to make this more clear
