### ISSUE TITLE
Coverband does not set SimpleCov.root

### ISSUE THREAD

**Issue by thedrow** [danmayer/coverband#59]
This causes SimpleCov to filter out files on it's reports.
I expected that when I set Coverband's root SimpleCov's root will also be set.

**Comment by danmayer** [comment]
I need a bit more details the reports I have looked at include filters I would expect could you share part of a report and list what you are seeing that is unexpected?

**Comment by thedrow** [comment]
SimpleCov filters out what's not defined in it's root configuration variable.
See https://github.com/colszowka/simplecov/blob/master/lib/simplecov/defaults.rb#L7
That filter is added by default and it's filtering out the rest of the package.
I can share a report with you privately if you don't mind.

**Comment by danmayer** [comment]
While this never effected me or my setup, I have addressed this in the large update I am working on...

https://github.com/danmayer/coverband/pull/79
