### ISSUE TITLE
Missing documentation on why baseline is required

### ISSUE THREAD

**Issue by sthaha** [danmayer/coverband#60]
Could you please shed some light into why creating a baseline is important? The README explains what  baseline does but not why.

**Comment by danmayer** [comment]
Sure, I tried to improved the documentation let me know if this helps.

https://github.com/danmayer/coverband/commit/9ce4834104bf94645dfd33e7570297790fc6fe65

**Comment by sthaha** [comment]
Thank you, that helped.
