### ISSUE TITLE
rake coverband:baseline never exits

### ISSUE THREAD

**Issue by cayblood** [danmayer/coverband#61]
I'm just sitting here wondering what is happening when I run rake coverband:baseline. It never exits. I think there is a problem with my configuration, but I'm not sure what it is. Any ideas? Thanks in advance.

**Comment by danmayer** [comment]
sorry I never responded to this, but more information is needed to investigate... best thing to do is checkout the example apps and make sure everything is setup correctly

https://github.com/danmayer/coverband#example-apps
