### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by jaysonvirissimo** [danmayer/coverband#62]
Both the [simplecov walk through](http://www.tamingthemindmonkey.com/2011/09/27/ruby-code-coverage-using-simplecov) and [Jruby coverage bug](http://jira.codehaus.org/browse/JRUBY-6106?page=com.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel) links are broken.

**Comment by danmayer** [comment]
blah..... OK I will look for a newer simplcov walk through to replace that... The coverage bug I will just remove as it is likely out of date, sad it was a great explanation of what was happening.

**Comment by danmayer** [comment]
thanks updated
