### ISSUE TITLE
Broken compatibility with coverband_ext

### ISSUE THREAD

**Issue by TheRusskiy** [danmayer/coverband#67]
As I am sure you are aware coverband_ext is a useful addition to this gem which speeds up sampling https://github.com/danmayer/coverband_ext
They use method which was recently deleted from your codebase as no longer used
They use it here: 
https://github.com/danmayer/coverband_ext/blob/master/ext/coverband_ext/coverband_ext.c#L49
It was deleted in this commit:
https://github.com/danmayer/coverband/commit/2f80301e6d7d8e80d628be7ec2e9dbffc2545946
I am not sure whether you are the ones who should fix it, but simply adding it back does solve the problem for me (I monkey patch coverband gem)

**Comment by danmayer** [comment]
Actually I will update the readme on coverband_ext... unless you are on a very old version of Ruby we no longer recommend coverband_ext. recent versions of Ruby made similar performance achievable without requiring dropping into C extensions.

**Comment by TheRusskiy** [comment]
ok, gonna close this issue then! Thank you!

**Comment by danmayer** [comment]
thanks updated coverband_ext readme https://github.com/danmayer/coverband_ext
