### ISSUE TITLE
Latest gem code not uploaded: undefined method `s3_bucket' for #<Coverband::Configuration...>

### ISSUE THREAD

**Issue by treble37** [danmayer/coverband#68]
If I have `gem 'coverband', '~> 1.1'`, in my Rails 4.2.7 Gemfile, and I try to set up s3_bucket as follows:

``` ruby
Coverband.configure do |config|
  config.s3_bucket = ENV['AWS_BUCKET']
end
```

I get undefined method `s3_bucket' for #Coverband::Configuration...

If I use a forked copy of the master branch of this gem, then the s3_bucket method exists.  Has the latest copy of master been pushed up to rubygems?

**Comment by danmayer** [comment]
yeah sorry I had merged those changes and wanted to run it for awhile before I released the gem and then forgot to ever release. I have pulled in some other changes, cleaned up docs, and bumped the version. Everything should be in sync now. with 1.2 released.
