### ISSUE TITLE
how to ignore app/assets in rails app?

### ISSUE THREAD

**Issue by josh-m-sharpe** [danmayer/coverband#80]
Hey dude!

I noticed that this config doesn't ignore app/assets

config.root_paths = ['/app/']
config.ignore        = ['vendor', 'spec', 'test', 'app/assets']

I dug in a bit and commenting this line out "fixes" that: https://github.com/danmayer/coverband/blob/master/lib/coverband/reporter.rb#L150

I would've thought the baseline process sets the files that get tracked, no?  Do you see any immediate problems removing that line?

**Comment by josh-m-sharpe** [comment]
I ran tests w/o it - they pass.

**Comment by josh-m-sharpe** [comment]
Actually, pretty sure this is useful for most files.  The problem I'm seeing is that it's matching *js.erb and *scss.erb files and making those show up.

I suppose that's not really a big deal.  If you know another way to hide those, that'd be great, otherwise can probably just close this thing out.

**Comment by danmayer** [comment]
ha I actually ran into this a couple days ago, and fixed it basically we added that line to show files that were never touched in coverband, but failed to realize it didn't respect the users filter. 

This has actually been fixed as part of a fairly large refactoring / adding additional features: https://github.com/danmayer/coverband/pull/79

I am about to put this in a RC release and put it on an app tonight or tomorrow, to make sure all is good. I can leave you a note if you want to try that release candidate as it will respect user filters again. It also will show hit density opposed to just binary line usage. So you can find most frequently hit sections of code.

**Comment by danmayer** [comment]
resolved in merged PR, closing!
