### ISSUE TITLE
Coverband reseting on every request in RAILS_ENV=development

### ISSUE THREAD

**Issue by kevinjalbert** [danmayer/coverband#81]
I understand that rails is restarting the application on each request (so changes can be loaded) -- https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/generators/rails/app/templates/config/environments/development.rb.tt#L4-L6.

My solution to trying coverband out in a development environment is to set the `startup_delay` to 0. Otherwise it never decrements (https://github.com/danmayer/coverband/blob/master/lib/coverband/base.rb#L60) since https://github.com/danmayer/coverband/blob/master/lib/coverband/base.rb#L38-L56 is executed on each request.

Should this be mentioned in the README somewhere? Or should I be doing something different to test this in development?

**Comment by danmayer** [comment]
this is in the readme ;) I actually recently added it as someone else hit this issue... basically it does decrement and will still work with startup delay but it becomes much slower as it will count down per  thread.

https://github.com/danmayer/coverband#1-create-coverband-config-file

see the comments above the `startup_delay` line and they mention that with puma and others you probably want to set it at 0 to avoid this issue ;). If there is somewhere else that might help this stand out more in the readme let me know and I could try to update that section ;)

**Comment by kevinjalbert** [comment]
I'm currently using WEBrick and it still doesn't do the decrements (if I `puts` the `@startup_delay` it stays the same).

Like you said by setting it to 0 everything works as expected.

It probably wouldn't hurt to explicitly mention to set it to 0 in `development`. Or to have that as a condition in example config file. I would imaging everyones first step it so try this out in a development environment. With the way things are now, it doesn't work without changing the config to be 0 for `startup_delay`.

**Comment by danmayer** [comment]
hmm that is odd WEBBrick definitely works for me with no changes in dev it just ignores the 2 requests and moves on... could you tell me more about your stack? Version of Rails, did you configure via initializer or `config.ru`, any other details that might help me to track down.

**Comment by danmayer** [comment]
yeah I could make dev not have a startup delay, which makes sense since the perf difference is so low these days... but I want to make sure it doesn't end up never starting to track for folks in production ;)

**Comment by kevinjalbert** [comment]
So I tried out some stuff here and I identified my problem.

I end up using https://github.com/kevinjalbert/port_map to help do port mapping of my local web servers so I can have them mapped to reasonable domains. If I don't use this everything works as expected.

I didn't realize that simply port mapping (via nginx's `proxy_pass`) the rails server to nginx would cause the `#reset_instance` to be called on each request.

**Comment by danmayer** [comment]
odd about that having an impact but I guess other things like xip.io, pow, and the like try to restart things a bit differently... So I guess the port_map issue makes sense.  I updated defaults / documentation. closing this out.

**Comment by kevinjalbert** [comment]
Yep I'm a little confused on why it handles restarting like that, but good to know.

I agree that closing this issue out and possibly adding something in the documentation mentioning said services and tools that could cause issues due to how they handle server restarts between requests.

👍 Thanks for the quick responses.
