### ISSUE TITLE
Coverage report is generated twice with different results

### ISSUE THREAD

**Issue by jagthedrummer** [danmayer/coverband#83]
I've followed all of the README instructions for installing and configuring coverband and when I run `rake coverband:coverage` I'm seeing some weird stuff in the coverage report.

What happens is that a browser window will open that shows some amount of coverage, but if I hit refresh, the coverage drops to 0%.

In the terminal where I run the rake task I can see that two reports are being generated.

```
$ rake coverband:coverage
...
Coverage report generated for RSpec to .../my-app/coverage. 105 / 1666 LOC (6.3%) covered.
Coverage report generated for RSpec to .../my-app/coverage. 0 / 2025 LOC (0.0%) covered.
```

I've tried following the same process in two different projects, and I'm seeing the same in both.

**Comment by danmayer** [comment]
hmm odd could you share a bit more details of your setup? You are using the redis adapter or something else? Any other details you could provide would be helpful (ruby version, rails version, etc)

Sorry for the delayed response and handling this issue, we just had [our first baby](https://millermayersadventures.com/2017/02/23/theodore-harley-mayer/) so I am a bit slow to do any open source work. I will likely still take a bit of time to get to the bottom of the issue.

**Comment by danmayer** [comment]
any other details @jagthedrummer to help me debug?

**Comment by jacebrowning** [comment]
I am seeing the same issue with the Redis adapters, Ruby 2.2.5p319, and Rails 4.2.7.

**Comment by jagthedrummer** [comment]
@danmayer, sorry for the delay responding. I was using the redis adapter, Ruby 2.2.5p319, and Rails 4.2.5.

**Comment by juanibiapina** [comment]
I also see the same issue.

**Comment by juanibiapina** [comment]
I deleted `.simplecov` file from production and it started working correctly.

**Comment by jacebrowning** [comment]
@juanibiapina's solution worked for me:

```
$ mv .simplecov .simplecov.disabled
$ bundle exec rake coverband:coverage
$ mv .simplecov.disabled .simplecov
```

**Comment by danmayer** [comment]
interesting can either of you share the settings you had in your `.simplecov` file? guessing it had some ignores in place causing it to ignore everything.

**Comment by jacebrowning** [comment]
The contents of my `.simplecov`:
```
require 'simplecov'

SimpleCov.start do
  add_filter 'app/admin'
  add_filter '/spec/'
  add_filter '/config/'
  add_filter '/vendor/'
  add_filter 'userevents'
end
```

**Comment by nocivus** [comment]
config was the culprit :)

**Comment by danmayer** [comment]
Added documentation about `rake coverband:coverage_no_filters`

Which should avoid this issue, sorry this feature and this bug have been hit and seen before but it wasn't ever clearly documented.

https://github.com/danmayer/coverband/commit/bd3b2cdc5e3c8357d36826d7af918d8397a5151c
