### ISSUE TITLE
rake coverband:coverage gives error

### ISSUE THREAD

**Issue by ankuriitk** [danmayer/coverband#84]
rake aborted!
NoMethodError: undefined method `track_files' for SimpleCov:Module
/Users/ankur/.rvm/gems/ruby-2.2.2/gems/coverband-1.5.0/lib/coverband/reporters/simple_cov_report.rb:22:in `report'
/Users/ankur/.rvm/gems/ruby-2.2.2/gems/coverband-1.5.0/lib/coverband/tasks.rb:50:in `block (2 levels) in <top (required)>'
/Users/ankur/.rvm/gems/ruby-2.2.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/ankur/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/ankur/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => coverband:coverage
(See full trace by running task with --trace)

Any idea why I am getting this error?

**Comment by ankuriitk** [comment]
@danmayer : can you please help?

**Comment by igniting** [comment]
You need a simplecov version >= 0.11.0 (https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md#0110-2015-11-29-changes).

**Comment by danmayer** [comment]
Sorry for the delayed response and handling this issue, we just had [our first baby](https://millermayersadventures.com/2017/02/23/theodore-harley-mayer/) so I am a bit slow to do any open source work. I will likely still take a bit of time to get to the bottom of the issue.

but I believe @igniting has the correct response... I will update the gem requires to check for that version... previously we didn't use this feature so we didn't require this level of simplecov

**Comment by danmayer** [comment]
I updated the gemspec to require this version... this is fixed in 1.5.1 thanks
