### ISSUE TITLE
Having trouble generating a report on production...

### ISSUE THREAD

**Issue by autobrain-stanley** [danmayer/coverband#86]
We are running rails on AWS, and using redis. 
Also have a customized baseline that observes the `config.ignore` setting.
So I have everything working on my localhost, and can execute `clear`, `custom_baseline`, and `coverage` operations generating the expected results.
Yesterday we pushed this to production, but I can't seem to be able to pull coverage from production. On my localhost I have hard coded the config to match our production values for `config.redis` including the appropriate url, port, and db#. I have logged in to our redis instance, and it seems to be recording activity from production as it reflects changes as I move through the app in production. But on my localhost if I run `rake coverband:coverage` with these hard coded production settings generates output reflecting files in production. However, it generates a 0% coverage report. As I said I the redis instance has data in it like this: 
![screen shot 2017-04-26 at 11 23 19 am](https://cloud.githubusercontent.com/assets/22938983/25445086/f957f0a6-2a72-11e7-91fd-b57e6e881555.png)
That changes appropriately as I activate the corresponding code from our production app. 
Not exactly sure what I am doing wrong here...

**Comment by autobrain-stanley** [comment]
The only thing that comes to mind is the differences between my localhost (OSX) and the AWS (Ubuntu) environments effecting the `config.root` as it is currently set to `Dir.pwd`

**Comment by autobrain-stanley** [comment]
If I try to set my localhost `config.root` to the AWS dir `/home/ubuntu/web-app/` then it tries to write the coverage report to that directory on my mac where that dir doesn't exist. Given the special rules around creating directories in home I'm not really keen on trying to create one just to test if matching local and prod paths would help the issue.

**Comment by autobrain-stanley** [comment]
Upon further inspection `coverage` operation is reporting all files as "not found in project" and listing their server directories.

**Comment by autobrain-stanley** [comment]
So it seems the problem is indeed caused by my local file system not matching the production server file system. How do I avoid this?

**Comment by danmayer** [comment]
Did you see / set `config.root_paths` this takes an array so you could have the root path of multiple systems... put in both the production expected root path and your local expected root path. I think that should resolve the issue.

`config.root_paths        = ['/app/'] # /app/ is needed for heroku deployments`

**Comment by danmayer** [comment]
oops should have tagged you hope this resolves the issue  @autobrain-stanley

**Comment by autobrain-stanley** [comment]
@danmayer Thanks a ton. Worked like a charm. Feel dumb now... But perhaps it might help to have some more documentation on the `root_paths`.  Or just on the config values in general...

**Comment by danmayer** [comment]
yep no worries does seem like an opportunity for me to improve the docs. Thanks for creating a issue and following up.
