### ISSUE TITLE
Web request fails when coverband cannot access Redis

### ISSUE THREAD

**Issue by jkypet** [danmayer/coverband#87]
I'm using Coverband::Middleware with Redis. Our app is hosted on Heroku. I used smaller Redis instance and when we had bigger traffic we got `Redis::CommandError - ERR max number of clients reached` - this exception caused that the web request has failed. It was thrown by calling `Coverband::Base.instance.report_coverage` at `vendor/bundle/ruby/2.3.0/gems/coverband-1.5.1/lib/coverband/middleware.rb:13`.

I'm afraid that just upgrading the Redis instance is not the solution because when we have a spike in traffic it's possible that even the biggest instance won't help. Is it possible to rescue all these exceptions to ensure that the web request will never be affected? Maybe I missed something in the documentation so please let me know if there is anything I can do. Our priority is to ensure the request will never fail - It's okay to skip the reporting for that request.

I can provide more detailed logs if needed.

**Comment by danmayer** [comment]
What was your sample rate set to? For high traffic sites you probably don't want a sample rate of 100%, so try turning that down to start at a much lower value....

Other than that do you know what the max number of clients is set to for your redis host? In general you will have a Redis connection per each process for your webapp server. I could look a bit more at how I am or am not using redis pooling

**Comment by jkypet** [comment]
We set the sample rate just to 5%. The limit for the clients is now 40 (bigger Redis plans are quite expensive on Heorku). We don't want to use our main Redis so we are using separate Redis instance. We have a LOT of background workers and yes it's possible that the processes can exceed the client count limit. But sadly this could happen anytime with even bigger plans.

**Comment by danmayer** [comment]
I believe this is better resolved with the Coverband 2.0 branch which is more less likely to cause any production issues.  It will be merged shortly.

https://github.com/danmayer/coverband/pull/107

I am going to close this out @jkypet but let me know if you look at using Coverband 2.0 and have any other issues. The new functionality allows you to send data on a frequency vs sampling, which means even with a 0.01% frequency you can really report all data and hardly ever hit Redis.
