### ISSUE TITLE
Can the percentage be changed at runtime?

### ISSUE THREAD

**Issue by eterps** [danmayer/coverband#94]
Can the percentage be changed at runtime? If so, how?

If it can't be changed at runtime, can coverband be disabled/enabled at runtime?

**Comment by eterps** [comment]
Ah I see that disabling/enabling coverband can be done with:

```
coverband = Coverband::Base.instance

#manual
coverband.start
coverband.stop
coverband.save
```

I will check if that can be used to change the percentage as well.

**Comment by danmayer** [comment]
so the settings aren't stored in something like redis and can't be easily changed across many servers at once. You can change them by updating the configuration via code

```
>> Coverband.configuration.percentage
=> 100.0
>> Coverband.configuration.percentage=50.0
=> 50.0
>> Coverband.configuration.percentage
=> 50.0
```

but if you have multiple servers you would have to propagate that somehow. I have considered making all the configs read from the data store so you could remotely reconfigure coverband, but it hasn't been worth the effort so far.

**Comment by danmayer** [comment]
^^ @eterps let me know if you need anything else

**Comment by eterps** [comment]
Thanks @danmayer , having configs read from the data store would be nice indeed, but this will do.
