### ISSUE TITLE
Use SimpleCov profile

### ISSUE THREAD

**Issue by viktor-silakov** [danmayer/coverband#96]
Hi! How can i use simplecov profile to generate html reports, groups, filters, and so on? For example:

```
SimpleCov.profiles.define 'test' do
       add_filter '/gems/'
       add_filter '/coverage/'
       add_filter '/reports/'
       add_group 'Features', 'features'
       add_group 'Applications123', 'app'
       add_group 'Core', 'src/core'
end
    
     SimpleCov.start 'test'
```

**Comment by danmayer** [comment]
Sorry I didn't get back to you... I see you closed this, but if you still have questions let me know. I tend to end up responding to most Github stuff on the weekends so it takes me a bit to get back to people. Basically, I think you are looking for regular test coverage, which isn't what coverband is about look as the simplecov project and perhaps a tutorial.... If you are trying to add grouping to production runtime code coverage let me know more about what you are trying to do.

**Comment by viktor-silakov** [comment]
I use coverband for cucmber UI tests in rails production environment,  pure simplecov (and other) is not convinient for me. And i found a solution for grouping -  i add my own rake task and insert to it:
```
    SimpleCov.add_group "Controllers", "app/controllers"
    # add_group "Channels", "app/channels" if defined?(ActionCable)
    SimpleCov.add_group "Models", "app/models"
    SimpleCov.add_group "Mailers", "app/mailers"
    SimpleCov.add_group "Helpers", "app/helpers"
    SimpleCov.add_group "Jobs", %w(app/jobs app/workers)
    SimpleCov.add_group "Libraries", "lib"

    SimpleCov.formatters = [
        SimpleCov::Formatter::HTMLFormatter,
        SimpleCov::Formatter::RcovFormatter
    ]

```

And this work fine.

**Comment by danmayer** [comment]
awesome that is a cool use case for coverband! Glad you figured it all out and thanks for sharing the solution in case it helps anyone else, awesome to see folks getting good usage of this out in the world.
