### ISSUE TITLE
Unable to start coverband from outside the Rails project directory

### ISSUE THREAD

**Issue by ThomasOwens** [danmayer/coverband#99]
I noticed a few things, all in lib/coverband.rb.

First, CONFIG_FILE is hard coded to a relative path. This is all well and good until you try to invoke a Rails application from outside Rails.root. From what I can tell, Coverband is looking for the CONFIG_FILE relative to the location where you run your script. Although I can set my working directory before starting the application, this doesn't seem like it should be necessary.

I also noticed that the self.configure method takes in a file argument, but it is unused. It appears like it should allow a caller to, instead of passing in a block, pass in a path to a configuration file instead. This would add a great deal of flexibility into users of Coverband by allowing them to choose a location to put the configuration file, instead of requiring it to be in './config/coverband.rb'.

**Comment by ThomasOwens** [comment]
I've opened one possible solution as a PR: https://github.com/danmayer/coverband/pull/100

**Comment by danmayer** [comment]
excellent, I will address this and help get that merged in after I get the long in progress Coverband 2.0 PR released. Thanks so much for the interest and support.

https://github.com/danmayer/coverband/pull/107

**Comment by danmayer** [comment]
resolved closing this out
